"""The original 32 kin (ids 0-31), ported from the old data.h.

Owner: core. Their art lives in tools/gen_monsters.py (model = function name).
"""

from kin import KinSpec

SPECIES = [
    KinSpec(0, 'FLARIX', ('BLAZE',), 'U', base=(41, 55, 42, 58, 47, 66), catch=45, xp=62, evo=('LEVEL', 16, 'PYREFOX'),
            category='LANTERN KIT', height=5, weight=85,
            learnset=[(1, 'M_SWIPE'), (1, 'M_POUT'), (7, 'M_CINDER_FLICK'), (11, 'M_DART'), (15, 'M_SEAR_BITE'), (19, 'M_LANTERN_LURE'), (23, 'M_LAST_EMBER'), (27, 'M_KILN_BREATH'), (33, 'M_GLINT'), (39, 'M_SUNFLARE')],
            traits=('SURGE', 'EMBERSKIN'), field=('LIGHT',),
            desc='The ember in its tail cage never goes out. Travelers who follow its glow always find their way to a warm hearth.',
            model='flarix'),
    KinSpec(1, 'PYREFOX', ('BLAZE',), 'U', base=(58, 68, 55, 78, 62, 83), catch=45, xp=142, evo=('LEVEL', 34, 'INFERNOX'),
            category='TWIN FLAME', height=10, weight=210,
            learnset=[(1, 'M_SWIPE'), (1, 'M_POUT'), (1, 'M_CINDER_FLICK'), (11, 'M_DART'), (15, 'M_SEAR_BITE'), (16, 'M_SNAP'), (21, 'M_LANTERN_LURE'), (25, 'M_LAST_EMBER'), (29, 'M_KILN_BREATH'), (35, 'M_GLINT'), (42, 'M_SUNFLARE')],
            traits=('SURGE', 'EMBERSKIN'), field=('LIGHT',),
            desc='It swishes its two lantern tails to signal its pack. The steadier the glow, the calmer it feels.',
            model='pyrefox'),
    KinSpec(2, 'INFERNOX', ('BLAZE', 'DUSK'), 'U', base=(76, 98, 70, 108, 75, 103), catch=45, xp=239, evo=None,
            category='LANTERN FOX', height=18, weight=620,
            learnset=[(1, 'M_SWIPE'), (1, 'M_CINDER_FLICK'), (1, 'M_DART'), (1, 'M_SNAP'), (15, 'M_SEAR_BITE'), (21, 'M_LANTERN_LURE'), (27, 'M_KILN_BREATH'), (34, 'M_HAUNT'), (38, 'M_GLOOM_ORB'), (44, 'M_SUNFLARE'), (50, 'M_BRIM_BURST')],
            traits=('SURGE', 'GLOWER'), field=('LIGHT',),
            desc='It walks the edge of the night, cloaked in smoke. Its tail burns with light it drank from a hundred sunsets.',
            model='infernox'),
    KinSpec(3, 'AQUAPO', ('TIDE',), 'U', base=(52, 58, 50, 50, 52, 44), catch=45, xp=62, evo=('LEVEL', 16, 'AXOLURK'),
            category='AXOLOTL', height=4, weight=52,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (6, 'M_FIZZ'), (10, 'M_SLIPSTREAM'), (14, 'M_MUD_PIE'), (19, 'M_SNAP'), (23, 'M_UNDERTOW'), (28, 'M_SWELL'), (34, 'M_BELLY_FLOP'), (40, 'M_GEYSER')],
            traits=('SURGE', 'SELFMEND'), field=(),
            desc='It keeps smiling even mid-bout. Its frilly gills taste the water for the tiny ripples other kin make.',
            model='aquapo'),
    KinSpec(4, 'AXOLURK', ('TIDE',), 'U', base=(72, 78, 66, 62, 62, 66), catch=45, xp=142, evo=('LEVEL', 34, 'TIDALOTL'),
            category='AXOLOTL', height=10, weight=245,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (1, 'M_FIZZ'), (10, 'M_SLIPSTREAM'), (14, 'M_MUD_PIE'), (20, 'M_SNAP'), (24, 'M_UNDERTOW'), (29, 'M_SWELL'), (35, 'M_BELLY_FLOP'), (42, 'M_GEYSER')],
            traits=('SURGE', 'SELFMEND'), field=('SURF',),
            desc='It waits under lily pads until the water ripples just right, then lunges out on a jet of current.',
            model='axolurk'),
    KinSpec(5, 'TIDALOTL', ('TIDE', 'WYRM'), 'U', base=(94, 100, 84, 96, 88, 70), catch=45, xp=239, evo=None,
            category='RIVER DRAKE', height=30, weight=1050,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_MUD_PIE'), (20, 'M_SNAP'), (24, 'M_UNDERTOW'), (29, 'M_SWELL'), (34, 'M_WYRMBREATH'), (38, 'M_SCALE_REND'), (45, 'M_GEYSER'), (52, 'M_STARFALL')],
            traits=('SURGE', 'SELFMEND'), field=('SURF',),
            desc='Its gill crown pulls charge from the current. River towns once sang to it each spring so the floods would pass gently.',
            model='tidalotl'),
    KinSpec(6, 'DANDELAMB', ('BLOOM',), 'U', base=(48, 46, 50, 62, 64, 48), catch=45, xp=62, evo=('LEVEL', 16, 'PUFFLEECE'),
            category='PUFF LAMB', height=5, weight=64,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (7, 'M_BRAMBLE_LASH'), (11, 'M_DROWSY_POLLEN'), (15, 'M_SAP_SIP'), (19, 'M_LEAF_FLURRY'), (23, 'M_BASK'), (27, 'M_BURR_VOLLEY'), (33, 'M_BELLY_FLOP'), (39, 'M_SUNSHAFT')],
            traits=('SURGE', 'BASKER'), field=(),
            desc='Its wool is one big dandelion puff. When it sneezes, seeds scatter, and a meadow grows wherever it naps.',
            model='dandelamb'),
    KinSpec(7, 'PUFFLEECE', ('BLOOM',), 'U', base=(62, 58, 64, 80, 82, 62), catch=45, xp=142, evo=('LEVEL', 34, 'ZEPHRAM'),
            category='SEED SHEEP', height=10, weight=200,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (1, 'M_BRAMBLE_LASH'), (11, 'M_DROWSY_POLLEN'), (15, 'M_SAP_SIP'), (16, 'M_DRAFT'), (20, 'M_LEAF_FLURRY'), (25, 'M_BASK'), (29, 'M_BURR_VOLLEY'), (35, 'M_BELLY_FLOP'), (42, 'M_SUNSHAFT')],
            traits=('SURGE', 'BASKER'), field=(),
            desc='Blossoms open in its fleece on sunny days. Fields a flock has grazed grow back twice as thick.',
            model='puffleece'),
    KinSpec(8, 'ZEPHRAM', ('BLOOM', 'GALE'), 'U', base=(84, 80, 78, 104, 96, 92), catch=45, xp=236, evo=None,
            category='WIND RAM', height=19, weight=600,
            learnset=[(1, 'M_BONK'), (1, 'M_BRAMBLE_LASH'), (1, 'M_DRAFT'), (1, 'M_DROWSY_POLLEN'), (15, 'M_SAP_SIP'), (20, 'M_LEAF_FLURRY'), (25, 'M_BASK'), (30, 'M_FEATHER_CUT'), (34, 'M_REED_BLADE'), (40, 'M_UPDRAFT'), (46, 'M_SUNSHAFT'), (52, 'M_STOOP')],
            traits=('SURGE', 'DRIFTER'), field=('FLY',),
            desc='Its fleece holds so much warm air that it floats on a breeze. It leads flocks over the mountains on rising winds.',
            model='zephram'),
    KinSpec(9, 'CINDERUB', ('BLAZE',), 'C', base=(60, 68, 54, 44, 48, 40), catch=120, xp=64, evo=('LEVEL', 24, 'MAGMAUL'),
            category='EMBER CUB', height=6, weight=120,
            learnset=[(1, 'M_SWIPE'), (1, 'M_POUT'), (6, 'M_CINDER_FLICK'), (10, 'M_SNAP'), (15, 'M_SEAR_BITE'), (20, 'M_BRACE'), (26, 'M_BELLY_FLOP'), (32, 'M_KILN_BREATH')],
            traits=('THICK FUR', 'BRUISER'), field=('LIGHT',),
            desc='The ember on its brow glows brighter when it is hungry. It loves to doze in warm ashes after a bout.',
            model='cinderub'),
    KinSpec(10, 'MAGMAUL', ('BLAZE', 'STONE'), 'U', base=(98, 112, 92, 66, 72, 48), catch=60, xp=172, evo=None,
            category='MAGMA BEAR', height=19, weight=1400,
            learnset=[(1, 'M_SWIPE'), (1, 'M_CINDER_FLICK'), (1, 'M_SNAP'), (1, 'M_SEAR_BITE'), (20, 'M_BRACE'), (24, 'M_ROCKFALL'), (30, 'M_BELLY_FLOP'), (34, 'M_STONESKIN'), (38, 'M_KILN_BREATH'), (44, 'M_FAULTLINE'), (50, 'M_SUNFLARE')],
            traits=('THICK FUR', 'BRUISER'), field=('STRENGTH', 'LIGHT'),
            desc='Molten rock creeps through the cracks of its stony shoulders. One swipe splits a boulder like firewood.',
            model='magmaul'),
    KinSpec(11, 'BUBBLIN', ('TIDE',), 'C', base=(72, 38, 52, 56, 54, 40), catch=190, xp=58, evo=('ITEM', 'FROST_SHARD', 'GLACIBLOB'),
            category='DROPLET', height=3, weight=30,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (8, 'M_POUT'), (12, 'M_SLIPSTREAM'), (16, 'M_FLURRY'), (20, 'M_CATNAP'), (24, 'M_BELLY_FLOP'), (30, 'M_SWELL'), (36, 'M_GEYSER')],
            traits=('SOAKER', 'SELFMEND'), field=(),
            desc='Clean spring water wrapped around a tiny kernel. Startle it and it splits into droplets, then flows back together.',
            model='bubblin'),
    KinSpec(12, 'GLACIBLOB', ('TIDE', 'FROST'), 'U', base=(112, 58, 82, 96, 88, 54), catch=75, xp=170, evo=None,
            category='GLACIER', height=12, weight=880,
            learnset=[(1, 'M_FIZZ'), (1, 'M_FLURRY'), (1, 'M_RIME_SHOT'), (1, 'M_SWELL'), (30, 'M_WINTER_RAY'), (36, 'M_HAILSTONES'), (42, 'M_GEYSER')],
            traits=('SOAKER', 'BEDROCK'), field=('SURF',),
            desc='A FROST SHARD froze it solid from the kernel out. The spikes on its crown never melt, even in summer.',
            model='glacibloob'),
    KinSpec(13, 'THORNIP', ('BLOOM',), 'C', base=(46, 62, 44, 54, 46, 60), catch=190, xp=58, evo=('ITEM', 'BLOOM_SHARD', 'BRAMBLOR'),
            category='RADISH', height=4, weight=40,
            learnset=[(1, 'M_SWIPE'), (1, 'M_GRIT_KICK'), (5, 'M_BRAMBLE_LASH'), (9, 'M_BARB'), (13, 'M_SNAP'), (18, 'M_LEAF_FLURRY'), (24, 'M_STARE_DOWN'), (30, 'M_REED_BLADE')],
            traits=('SPORESKIN', 'KEEN EYE'), field=(),
            desc='It buries itself up to its leaves, pops out to startle passersby, then giggles and runs.',
            model='thornip'),
    KinSpec(14, 'BRAMBLOR', ('BLOOM', 'VENOM'), 'U', base=(78, 104, 76, 82, 72, 84), catch=75, xp=168, evo=None,
            category='BRAMBLE', height=16, weight=450,
            learnset=[(1, 'M_BRAMBLE_LASH'), (1, 'M_BARB'), (1, 'M_STARE_DOWN'), (1, 'M_LEAF_FLURRY'), (25, 'M_SPORE_CLOUD'), (30, 'M_FESTER'), (34, 'M_REED_BLADE'), (40, 'M_BOG_BOMB'), (46, 'M_BURR_VOLLEY')],
            traits=('SPORESKIN', 'KEEN EYE'), field=(),
            desc='A tangle of briars around a bitter kernel. Its purple berries are safe to touch, but never to eat.',
            model='bramblor'),
    KinSpec(15, 'MOSSHELL', ('BLOOM',), 'C', base=(58, 56, 74, 42, 56, 28), catch=150, xp=60, evo=('LEVEL', 26, 'TERRASHELL'),
            category='MOSS SNAIL', height=5, weight=160,
            learnset=[(1, 'M_BONK'), (1, 'M_BRACE'), (6, 'M_BRAMBLE_LASH'), (10, 'M_SNAP'), (14, 'M_SAP_SIP'), (19, 'M_PEBBLE_PELT'), (24, 'M_LEAF_FLURRY'), (30, 'M_BASK')],
            traits=('BASKER', 'STUBBORN'), field=(),
            desc='Moss grows thicker on its shell every year. It naps in sunbeams so the moss can pump its kernel for it.',
            model='mosshell'),
    KinSpec(16, 'TERRASHELL', ('BLOOM', 'STONE'), 'U', base=(98, 92, 114, 54, 82, 42), catch=60, xp=172, evo=None,
            category='CAIRN SNAIL', height=18, weight=2800,
            learnset=[(1, 'M_BONK'), (1, 'M_BRACE'), (1, 'M_BRAMBLE_LASH'), (1, 'M_SNAP'), (14, 'M_SAP_SIP'), (19, 'M_PEBBLE_PELT'), (26, 'M_MUD_PIE'), (30, 'M_STONESKIN'), (34, 'M_BELLY_FLOP'), (38, 'M_REED_BLADE'), (44, 'M_FAULTLINE')],
            traits=('BASKER', 'BEDROCK'), field=('STRENGTH',),
            desc='It has stacked stones on its shell for a thousand years. Ferns, beetles and small kin live in the cairn it carries.',
            model='terrashell'),
    KinSpec(17, 'ZAPPET', ('SPARK', 'GALE'), 'C', base=(42, 44, 40, 66, 46, 76), catch=190, xp=58, evo=('LEVEL', 22, 'STORMHAWK'),
            category='SPARK CHICK', height=3, weight=18,
            learnset=[(1, 'M_BEAK_JAB'), (1, 'M_POUT'), (5, 'M_STATIC_POP'), (9, 'M_DART'), (13, 'M_TINGLE'), (17, 'M_FEATHER_CUT'), (22, 'M_LIVE_WIRE'), (28, 'M_FORKED_BOLT')],
            traits=('STATIC FUR', 'CONDUCTOR'), field=('LIGHT',),
            desc='Static builds in its fluffy down until it crackles. It flings tiny sparks at anything that surprises it.',
            model='zappet'),
    KinSpec(18, 'STORMHAWK', ('SPARK', 'GALE'), 'U', base=(72, 78, 66, 102, 70, 104), catch=60, xp=172, evo=None,
            category='STORM', height=15, weight=320,
            learnset=[(1, 'M_BEAK_JAB'), (1, 'M_STATIC_POP'), (1, 'M_DART'), (1, 'M_TINGLE'), (17, 'M_FEATHER_CUT'), (22, 'M_LIVE_WIRE'), (28, 'M_UPDRAFT'), (32, 'M_FORKED_BOLT'), (38, 'M_STOOP'), (45, 'M_OVERCHARGE')],
            traits=('STATIC FUR', 'KEEN EYE'), field=('FLY', 'LIGHT'),
            desc='It rides the edges of thunderheads and dives faster than sound. Its crest glows white before lightning strikes.',
            model='stormhawk'),
    KinSpec(19, 'VOLTUX', ('SPARK',), 'C', base=(46, 54, 40, 58, 44, 82), catch=170, xp=60, evo=('ITEM', 'SPARK_SHARD', 'VOLTLOPE'),
            category='SPARK HARE', height=6, weight=75,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (6, 'M_STATIC_POP'), (10, 'M_DART'), (14, 'M_SNAP'), (18, 'M_TINGLE'), (23, 'M_LIVE_WIRE'), (29, 'M_GLINT'), (35, 'M_FORKED_BOLT')],
            traits=('STATIC FUR', 'MOMENTUM'), field=('LIGHT',),
            desc='It rubs its zigzag ears on dry grass to charge up. On dark nights its tail puff pops with little blue sparks.',
            model='voltux'),
    KinSpec(20, 'VOLTLOPE', ('SPARK', 'BRAWL'), 'U', base=(72, 104, 64, 78, 72, 108), catch=60, xp=175, evo=None,
            category='JACKALOPE', height=14, weight=420,
            learnset=[(1, 'M_DART'), (1, 'M_LIVE_WIRE'), (1, 'M_TINGLE'), (1, 'M_ONE_TWO'), (30, 'M_PUMMEL'), (35, 'M_WAR_CRY'), (40, 'M_HAYMAKER'), (46, 'M_OVERCHARGE'), (50, 'M_RECKLESS_RUSH')],
            traits=('MOMENTUM', 'BRUISER'), field=('STRENGTH', 'LIGHT'),
            desc='Its antlers are frozen lightning. One thump of its hind legs sends a crackle through the ground for a mile.',
            model='voltlope'),
    KinSpec(21, 'GOLEMIT', ('STONE',), 'C', base=(56, 76, 86, 30, 42, 24), catch=150, xp=60, evo=('LEVEL', 25, 'BOULDRON'),
            category='PEBBLE', height=6, weight=400,
            learnset=[(1, 'M_BONK'), (1, 'M_BRACE'), (6, 'M_PEBBLE_PELT'), (10, 'M_GRIT_KICK'), (15, 'M_MUD_PIE'), (20, 'M_HAMMER_FIST'), (26, 'M_ROCKFALL'), (31, 'M_BELLY_FLOP'), (37, 'M_FAULTLINE')],
            traits=('STUBBORN', 'BEDROCK'), field=(),
            desc='A living lump of rock. Moss grows in its cracks, and it nibbles the moss when it gets hungry.',
            model='golemit'),
    KinSpec(22, 'BOULDRON', ('STONE', 'BRAWL'), 'U', base=(92, 124, 128, 44, 66, 40), catch=60, xp=172, evo=None,
            category='BOULDER', height=21, weight=5200,
            learnset=[(1, 'M_BONK'), (1, 'M_BRACE'), (1, 'M_PEBBLE_PELT'), (1, 'M_GRIT_KICK'), (15, 'M_MUD_PIE'), (20, 'M_HAMMER_FIST'), (25, 'M_ROCKFALL'), (29, 'M_STONESKIN'), (33, 'M_PUMMEL'), (38, 'M_FAULTLINE'), (44, 'M_HAYMAKER'), (50, 'M_RECKLESS_RUSH')],
            traits=('STUBBORN', 'BRUISER'), field=('STRENGTH',),
            desc='It sleeps for months and is often mistaken for a hill. Its crystals hum when anyone nearby is brimming.',
            model='bouldron'),
    KinSpec(23, 'PUFFOWL', ('GALE',), 'C', base=(62, 40, 42, 44, 54, 56), catch=255, xp=52, evo=('LEVEL', 20, 'HOOTLORD'),
            category='OWLET', height=4, weight=60,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (5, 'M_BEAK_JAB'), (9, 'M_DRAFT'), (13, 'M_DAYDREAM'), (17, 'M_FEATHER_CUT'), (22, 'M_CATNAP'), (25, 'M_GLINT'), (29, 'M_PRISM_RAY')],
            traits=('WAKEFUL', 'KEEN EYE'), field=(),
            desc='It puffs up to twice its size when surprised. Its huge eyes can read by starlight alone.',
            model='puffowl'),
    KinSpec(24, 'HOOTLORD', ('GALE', 'DREAM'), 'U', base=(98, 62, 66, 94, 96, 80), catch=90, xp=158, evo=None,
            category='GREAT OWL', height=15, weight=380,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (1, 'M_BEAK_JAB'), (1, 'M_DRAFT'), (13, 'M_DAYDREAM'), (17, 'M_FEATHER_CUT'), (20, 'M_PRISM_RAY'), (24, 'M_CATNAP'), (28, 'M_GLINT'), (32, 'M_DREAMQUAKE'), (36, 'M_STILL_POND'), (42, 'M_STOOP'), (48, 'M_PRIMAL_ROAR')],
            traits=('WAKEFUL', 'QUICK STUDY'), field=('FLY', 'TELEPORT'),
            desc="It perches over old libraries and seems to read over people's shoulders. Its wings are speckled like the night sky.",
            model='hootlord'),
    KinSpec(25, 'SKYWISP', ('SWARM', 'GALE'), 'C', base=(46, 34, 42, 62, 54, 70), catch=190, xp=56, evo=('ITEM', 'DUSK_SHARD', 'LUMOTH'),
            category='CLOUD MOTH', height=4, weight=20,
            learnset=[(1, 'M_BONK'), (1, 'M_SILK_SNARE'), (6, 'M_DRAFT'), (10, 'M_SPORE_CLOUD'), (14, 'M_DROWSY_POLLEN'), (18, 'M_PINCER'), (23, 'M_DAYDREAM'), (28, 'M_WINGDUST')],
            traits=('DRIFTER', 'SPORESKIN'), field=(),
            desc='It drifts on warm breezes like a scrap of cloud. The dust on its wings flashes in time with every SKYWISP nearby.',
            model='skywisp'),
    KinSpec(26, 'LUMOTH', ('SWARM', 'DREAM'), 'U', base=(72, 48, 64, 112, 90, 98), catch=75, xp=170, evo=None,
            category='MOON MOTH', height=13, weight=125,
            learnset=[(1, 'M_DRAFT'), (1, 'M_DAYDREAM'), (1, 'M_WINGDUST'), (1, 'M_DROWSY_POLLEN'), (30, 'M_PRISM_RAY'), (36, 'M_STILL_POND'), (42, 'M_DREAMQUAKE')],
            traits=('DRIFTER', 'FOCUSED'), field=('TELEPORT', 'LIGHT'),
            desc='The patterns on its wings glow in the dark. Anyone who stares at them long enough starts to daydream.',
            model='lumoth'),
    KinSpec(27, 'NIBBIT', ('BEAST',), 'C', base=(44, 64, 40, 30, 42, 72), catch=255, xp=50, evo=('LEVEL', 18, 'GNAWLORD'),
            category='PACK RAT', height=3, weight=35,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (4, 'M_DART'), (8, 'M_SNAP'), (12, 'M_GRIT_KICK'), (16, 'M_ONE_TWO'), (20, 'M_STARE_DOWN'), (26, 'M_GNASH'), (32, 'M_RECKLESS_RUSH')],
            traits=('HOARDER', 'SLIPPERY'), field=(),
            desc="It collects buttons, bottle caps and lost keys. If something shiny goes missing, check the nearest NIBBIT's bundle.",
            model='nibbit'),
    KinSpec(28, 'GNAWLORD', ('BEAST', 'DUSK'), 'U', base=(76, 102, 64, 44, 66, 104), catch=127, xp=140, evo=None,
            category='RAT KING', height=9, weight=220,
            learnset=[(1, 'M_BONK'), (1, 'M_DART'), (1, 'M_SNAP'), (1, 'M_GRIT_KICK'), (16, 'M_ONE_TWO'), (18, 'M_STARE_DOWN'), (24, 'M_GNASH'), (28, 'M_CATNAP'), (32, 'M_HAUNT'), (38, 'M_RECKLESS_RUSH'), (44, 'M_BRIM_BURST')],
            traits=('HOARDER', 'GLOWER'), field=('STRENGTH',),
            desc='It wears the finest bottle cap in its hoard as a crown. Packs of NIBBIT bring it treasures every dusk.',
            model='gnawlord'),
    KinSpec(29, 'FROSTOAT', ('FROST',), 'U', base=(56, 64, 50, 78, 64, 92), catch=75, xp=150, evo=None,
            category='ERMINE', height=5, weight=70,
            learnset=[(1, 'M_SWIPE'), (1, 'M_POUT'), (5, 'M_FLURRY'), (9, 'M_DART'), (13, 'M_RIME_SHOT'), (18, 'M_SNAP'), (22, 'M_HAILSTONES'), (26, 'M_GLINT'), (30, 'M_WINTER_RAY'), (36, 'M_STILL_POND')],
            traits=('THICK FUR', 'SLIPPERY'), field=(),
            desc='It pumps its kernel by shedding heat, so the ground frosts over wherever it curls up to sleep.',
            model='frostoat'),
    KinSpec(30, 'WISPIRE', ('DUSK',), 'U', base=(64, 54, 66, 112, 94, 96), catch=60, xp=160, evo=None,
            category='MARSH LIGHT', height=10, weight=5,
            learnset=[(1, 'M_STARE_DOWN'), (1, 'M_DAYDREAM'), (8, 'M_LANTERN_LURE'), (14, 'M_HAUNT'), (20, 'M_GLOOM_ORB'), (26, 'M_PRISM_RAY'), (30, 'M_STILL_POND'), (36, 'M_DREAMQUAKE'), (42, 'M_KILN_BREATH')],
            traits=('DRIFTER', 'FOCUSED'), field=('LIGHT', 'TELEPORT'),
            desc='A flickering light over the marshes. Some say it guides travelers home; others say it leads them in circles for fun.',
            model='wispire'),
    KinSpec(31, 'DRAKORA', ('WYRM', 'GALE'), 'L', base=(96, 114, 90, 114, 92, 96), catch=15, xp=250, evo=None,
            category='STORMWYRM', height=45, weight=2100,
            learnset=[(1, 'M_WYRMBREATH'), (1, 'M_DRAFT'), (1, 'M_STARE_DOWN'), (1, 'M_FEATHER_CUT'), (30, 'M_SCALE_REND'), (36, 'M_UPDRAFT'), (40, 'M_STOOP'), (46, 'M_FAULTLINE'), (52, 'M_STARFALL')],
            traits=('GLOWER', 'MOMENTUM'), field=('FLY',),
            desc='Its kernel is so old and vast that it feels the whole sky. When DRAKORA brims, the heavens brim with it.',
            model='drakora'),
]
