"""Kin 152-173. Owner: KIN-E (fusion kin 152-173).

Fusion kin never appear in the wild: each one is woven on the Fusion Loom
from its two signature energies (docs/EXPANSION.md 4.5 and 7.4). Their art
lives in tools/kin/art_fusion_b.py (one model function per species).
"""

from kin import KinSpec
from kin.art_fusion_b import (barkolem, porcelynx, kabutorai, drownjelly, sunmane, dreamkite,
                              bognewt, rimegolem, dynamole, lullabox, kitsuflame, wyvernix,
                              trihydra, phoenex, ironhowl, nimbwhale, jollyrogue, runelith,
                              faefly, snowbrute, teslarose, noctmare)

SPECIES = [
    KinSpec(152, 'BARKOLEM', ('BLOOM', 'STONE'), 'F', base=(105, 110, 125, 55, 90, 40), catch=45, xp=205,
            category='BIRDHOUSE', height=21, weight=2400,
            learnset=[(1, 'M_BRAMBLE_LASH'), (1, 'M_PEBBLE_PELT'), (1, 'M_BRACE'), (1, 'M_BURR_VOLLEY'),
                      (8, 'M_MUD_PIE'), (14, 'M_SAP_SIP'), (20, 'M_ROCKFALL'), (26, 'M_THORN_WALL'),
                      (32, 'M_REED_BLADE'), (38, 'M_STONESKIN'), (44, 'M_BASK'), (50, 'M_FAULTLINE'),
                      (56, 'M_SUNSHAFT')],
            traits=('BASKER', 'BEDROCK'), field=('STRENGTH',), fusion=('BLOOM', 'STONE'),
            desc='Woven from BLOOM and STONE energy, its roots grip a granite heart that stores the sun. '
                 'Songbirds nest in the house on its crown; it will not budge while chicks are inside.',
            concept='stump golem with a birdhouse', model=barkolem, placeholder=False),
    KinSpec(153, 'PORCELYNX', ('RELIC', 'FROST'), 'F', base=(70, 75, 85, 115, 90, 110), catch=45, xp=205,
            category='GLAZE LYNX', height=11, weight=380,
            learnset=[(1, 'M_SWIPE'), (1, 'M_RIME_SHOT'), (1, 'M_CLATTER'), (1, 'M_TARNISH'),
                      (8, 'M_FLURRY'), (14, 'M_TRINKET_TOSS'), (20, 'M_SNOWDRIFT'), (26, 'M_GILDED_GLEAM'),
                      (32, 'M_HAILSTONES'), (38, 'M_POLTERGUST'), (44, 'M_WINTER_RAY'), (50, 'M_CURSED_CURIO')],
            traits=('KEEN EYE', 'GLOWER'), field=(), fusion=('RELIC', 'FROST'),
            desc='Woven from RELIC and FROST energy, it is glazed like old porcelain that sheds heat. '
                 'Its cracks were mended with gold, and frost ferns bloom wherever it sits still.',
            concept='porcelain lynx with frost glaze', model=porcelynx, placeholder=False),
    KinSpec(154, 'KABUTORAI', ('METAL', 'BRAWL'), 'F', base=(80, 140, 120, 45, 75, 75), catch=45, xp=210,
            category='RONIN BUG', height=17, weight=1450,
            learnset=[(1, 'M_IRON_TAP'), (1, 'M_ONE_TWO'), (1, 'M_PINCER'), (1, 'M_BRACE'),
                      (8, 'M_RIVET_SHOT'), (14, 'M_COUNTERJAB'), (20, 'M_STEEL_SHELL'), (26, 'M_HAMMER_FIST'),
                      (32, 'M_GEAR_GRIND'), (38, 'M_WAR_CRY'), (44, 'M_PUMMEL'), (50, 'M_ANVIL_DROP'),
                      (56, 'M_HAYMAKER')],
            traits=('BRUISER', 'STUBBORN'), field=('STRENGTH',), fusion=('METAL', 'BRAWL'),
            desc='Woven from METAL and BRAWL energy. Magnetite laced its shell into iron lamellae, and '
                 'the strain of every parry pumps its kernel. It bows before each bout.',
            concept='samurai beetle', model=kabutorai, placeholder=False),
    KinSpec(155, 'DROWNJELLY', ('TIDE', 'HOLLOW'), 'F', base=(125, 50, 85, 95, 115, 55), catch=45, xp=205,
            category='DROWN LAMP', height=14, weight=90,
            learnset=[(1, 'M_FIZZ'), (1, 'M_BONE_RATTLE'), (1, 'M_SHROUD'), (1, 'M_LANTERN_LURE'),
                      (8, 'M_GRAVE_CHILL'), (14, 'M_UNDERTOW'), (20, 'M_MARROW_SIP'), (26, 'M_LAST_RITES'),
                      (32, 'M_SWELL'), (38, 'M_DEATH_KNELL'), (44, 'M_GEYSER'), (50, 'M_REQUIEM')],
            traits=('DRIFTER', 'SOAKER'), field=('SURF', 'LIGHT'), fusion=('TIDE', 'HOLLOW'),
            desc='Woven from TIDE and HOLLOW energy, it pumps on the slow heat of sunken bones. The '
                 'drowned lantern in its bell guides lost boats home, or down, as it pleases.',
            concept='drowned jellyfish lantern', model=drownjelly, placeholder=False),
    KinSpec(156, 'SUNMANE', ('BLOOM', 'BLAZE'), 'F', base=(90, 100, 75, 110, 80, 95), catch=45, xp=210,
            category='SUN LION', height=16, weight=1900,
            learnset=[(1, 'M_CINDER_FLICK'), (1, 'M_BRAMBLE_LASH'), (1, 'M_SNARL'), (1, 'M_BASK'),
                      (8, 'M_SEAR_BITE'), (14, 'M_SAP_SIP'), (20, 'M_LEAF_FLURRY'), (26, 'M_KILN_BREATH'),
                      (32, 'M_EMBER_STORM'), (38, 'M_REED_BLADE'), (44, 'M_SUNSHAFT'), (50, 'M_SUNFLARE'),
                      (56, 'M_PRIMAL_ROAR')],
            traits=('BASKER', 'GLOWER'), field=('LIGHT',), fusion=('BLOOM', 'BLAZE'),
            desc='Woven from BLOOM and BLAZE energy, it drinks the sun twice: its petal mane gathers '
                 'daylight and its kernel burns it like a hearth. Its roar smells of warm honey.',
            concept='lion with a sunflower mane', model=sunmane, placeholder=False),
    KinSpec(157, 'DREAMKITE', ('DREAM', 'GALE'), 'F', base=(70, 55, 70, 120, 95, 125), catch=45, xp=205,
            category='DREAM KITE', height=15, weight=12,
            learnset=[(1, 'M_DRAFT'), (1, 'M_DAYDREAM'), (1, 'M_LULLABY'), (1, 'M_UPDRAFT'),
                      (8, 'M_PRISM_RAY'), (14, 'M_FEATHER_CUT'), (20, 'M_STILL_POND'), (26, 'M_CROSSWIND'),
                      (32, 'M_DREAMQUAKE'), (38, 'M_GLINT'), (44, 'M_STOOP')],
            traits=('DRIFTER', 'FOCUSED'), field=('FLY', 'TELEPORT'), fusion=('DREAM', 'GALE'),
            desc='Woven from DREAM and GALE energy, it rides the wind that rises off sleeping minds. '
                 'Children who dream of flying wake with its string tied round one finger.',
            concept='kite-shaped dream spirit', model=dreamkite, placeholder=False),
    KinSpec(158, 'BOGNEWT', ('VENOM', 'TIDE'), 'F', base=(100, 85, 85, 100, 105, 60), catch=45, xp=205,
            category='BOG NEWT', height=13, weight=520,
            learnset=[(1, 'M_FIZZ'), (1, 'M_BARB'), (1, 'M_SLIPSTREAM'), (1, 'M_MUD_PIE'),
                      (8, 'M_ACID_SPIT'), (14, 'M_SPORE_CLOUD'), (20, 'M_UNDERTOW'), (26, 'M_FESTER'),
                      (32, 'M_BOG_BOMB'), (38, 'M_SWELL'), (44, 'M_RIPTIDE'), (50, 'M_GEYSER')],
            traits=('SPORESKIN', 'SOAKER'), field=('SURF',), fusion=('VENOM', 'TIDE'),
            desc='Woven from VENOM and TIDE energy, it pumps on the fizz of rotting reeds. Its orange '
                 'belly warns foes off, and the pools it wallows in glow green all night.',
            concept='toxic bog newt', model=bognewt, placeholder=False),
    KinSpec(159, 'RIMEGOLEM', ('FROST', 'STONE'), 'F', base=(100, 120, 130, 50, 80, 45), catch=45, xp=210,
            category='PERMAFROST', height=24, weight=4800,
            learnset=[(1, 'M_RIME_SHOT'), (1, 'M_PEBBLE_PELT'), (1, 'M_BRACE'), (1, 'M_GRIT_KICK'),
                      (8, 'M_HAILSTONES'), (14, 'M_MUD_PIE'), (20, 'M_ROCKFALL'), (26, 'M_SNOWDRIFT'),
                      (32, 'M_STONESKIN'), (38, 'M_HAMMER_FIST'), (44, 'M_WINTER_RAY'), (50, 'M_FAULTLINE'),
                      (56, 'M_BELLY_FLOP')],
            traits=('BEDROCK', 'STUBBORN'), field=('STRENGTH',), fusion=('FROST', 'STONE'),
            desc='Woven from FROST and STONE energy. Its kernel sheds heat so fast that meltwater '
                 'freezes in its cracks, prying the rock apart and binding it again in blue ice.',
            concept='ice golem', model=rimegolem, placeholder=False),
    KinSpec(160, 'DYNAMOLE', ('METAL', 'SPARK'), 'F', base=(85, 105, 110, 95, 70, 70), catch=45, xp=205,
            category='DYNAMO', height=10, weight=780,
            learnset=[(1, 'M_SWIPE'), (1, 'M_STATIC_POP'), (1, 'M_IRON_TAP'), (1, 'M_GRIT_KICK'),
                      (8, 'M_TINGLE'), (14, 'M_RIVET_SHOT'), (20, 'M_LIVE_WIRE'), (26, 'M_MAGNET_PULL'),
                      (32, 'M_GEAR_GRIND'), (38, 'M_ARC_FLASH'), (44, 'M_STEEL_SHELL'), (50, 'M_LODE_BEAM'),
                      (56, 'M_OVERCHARGE')],
            traits=('CONDUCTOR', 'STATIC FUR'), field=('LIGHT', 'STRENGTH'), fusion=('METAL', 'SPARK'),
            desc='Woven from METAL and SPARK energy, it tunnels through magnetite lodes. The copper '
                 'coil on its back turns every dig into current, and its headlamp never goes out.',
            concept='mole with a dynamo', model=dynamole, placeholder=False),
    KinSpec(161, 'LULLABOX', ('RELIC', 'DREAM'), 'F', base=(85, 50, 100, 115, 115, 60), catch=45, xp=205,
            category='MUSIC BOX', height=8, weight=60,
            learnset=[(1, 'M_CLATTER'), (1, 'M_LULLABY'), (1, 'M_DAYDREAM'), (1, 'M_TARNISH'),
                      (8, 'M_TRINKET_TOSS'), (14, 'M_STILL_POND'), (20, 'M_POLTERGUST'), (26, 'M_PRISM_RAY'),
                      (32, 'M_GILDED_GLEAM'), (38, 'M_CATNAP'), (44, 'M_DREAMQUAKE'), (50, 'M_CURSED_CURIO')],
            traits=('FOCUSED', 'HOARDER'), field=('TELEPORT',), fusion=('RELIC', 'DREAM'),
            desc='Woven from RELIC and DREAM energy. A century of bedtime songs is pinned to its drum; '
                 'when it plays, every mind nearby falls into step and drifts off to sleep.',
            concept='music box that sings lullabies', model=lullabox, placeholder=False),
    KinSpec(162, 'KITSUFLAME', ('BLAZE', 'DREAM'), 'F', base=(75, 70, 75, 125, 100, 115), catch=45, xp=215,
            category='FOXFIRE', height=13, weight=240,
            learnset=[(1, 'M_CINDER_FLICK'), (1, 'M_DAYDREAM'), (1, 'M_DART'), (1, 'M_LANTERN_LURE'),
                      (8, 'M_SEAR_BITE'), (14, 'M_PRISM_RAY'), (20, 'M_KILN_BREATH'), (26, 'M_LULLABY'),
                      (32, 'M_STILL_POND'), (38, 'M_EMBER_STORM'), (44, 'M_DREAMQUAKE'), (50, 'M_SUNFLARE')],
            traits=('FOCUSED', 'GLOWER'), field=('LIGHT', 'TELEPORT'), fusion=('BLAZE', 'DREAM'),
            desc='Woven from BLAZE and DREAM energy, its pale foxfire glows but never scorches. Each of '
                 'its nine tails keeps one dream, and it shows them to travellers who get lost.',
            concept='nine-tailed fox of foxfire', model=kitsuflame, placeholder=False),
    KinSpec(163, 'WYVERNIX', ('GALE', 'WYRM'), 'F', base=(80, 125, 75, 80, 70, 120), catch=45, xp=210,
            category='SKY WYVERN', height=20, weight=780,
            learnset=[(1, 'M_DRAFT'), (1, 'M_WYRMBREATH'), (1, 'M_FEATHER_CUT'), (1, 'M_STARE_DOWN'),
                      (8, 'M_UPDRAFT'), (14, 'M_SCALE_REND'), (20, 'M_WYRM_DANCE'), (26, 'M_CROSSWIND'),
                      (32, 'M_STOOP'), (38, 'M_RECKLESS_RUSH'), (44, 'M_STARFALL')],
            traits=('MOMENTUM', 'KEEN EYE'), field=('FLY',), fusion=('GALE', 'WYRM'),
            desc='Woven from GALE and WYRM energy, its ancient kernel couples to the jet stream. It '
                 'hardly beats its wings; it hangs on the high wind, then stoops like a falcon.',
            concept='wyvern', model=wyvernix, placeholder=False),
    KinSpec(164, 'TRIHYDRA', ('VENOM', 'WYRM'), 'F', base=(105, 100, 85, 100, 85, 65), catch=45, xp=210,
            category='HYDRA', height=19, weight=1600,
            learnset=[(1, 'M_BARB'), (1, 'M_SNAP'), (1, 'M_WYRMBREATH'), (1, 'M_SPORE_CLOUD'),
                      (8, 'M_ACID_SPIT'), (14, 'M_SCALE_REND'), (20, 'M_FESTER'), (26, 'M_WYRM_DANCE'),
                      (32, 'M_GNASH'), (38, 'M_BOG_BOMB'), (44, 'M_CATNAP'), (50, 'M_STARFALL')],
            traits=('SELFMEND', 'SURGE'), field=('SURF',), fusion=('VENOM', 'WYRM'),
            desc='Woven from VENOM and WYRM energy, one old kernel feeds three heads that each brew '
                 'their own poison. Knock one out in a bout and its motes grow it back by dusk.',
            concept='three-headed hydra', model=trihydra, placeholder=False),
    KinSpec(165, 'PHOENEX', ('BLAZE', 'ASTRAL'), 'F', base=(80, 75, 70, 130, 90, 115), catch=45, xp=215,
            category='STARFIRE', height=20, weight=260,
            learnset=[(1, 'M_CINDER_FLICK'), (1, 'M_TWINKLE'), (1, 'M_DRAFT'), (1, 'M_STARDUST'),
                      (8, 'M_SEAR_BITE'), (14, 'M_MOONBEAM'), (20, 'M_KILN_BREATH'), (26, 'M_NEBULA_VEIL'),
                      (32, 'M_EMBER_STORM'), (38, 'M_COMET_DASH'), (44, 'M_MUON_RAIN'), (50, 'M_SUNFLARE'),
                      (56, 'M_SUPERNOVA')],
            traits=('STUBBORN', 'FOCUSED'), field=('FLY', 'LIGHT'), fusion=('BLAZE', 'ASTRAL'),
            desc='Woven from BLAZE and ASTRAL energy, it burns cosmic rays as starfire. When it dozes '
                 'it crumbles to glowing embers, and it rises again with the next dawn.',
            concept='phoenix of starfire', model=phoenex, placeholder=False),
    KinSpec(166, 'IRONHOWL', ('METAL', 'BEAST'), 'F', base=(85, 115, 105, 55, 75, 110), catch=45, xp=210,
            category='IRON WOLF', height=14, weight=1350,
            learnset=[(1, 'M_SWIPE'), (1, 'M_IRON_TAP'), (1, 'M_SNARL'), (1, 'M_DART'),
                      (8, 'M_RIVET_SHOT'), (14, 'M_GNASH'), (20, 'M_MAGNET_PULL'), (26, 'M_GEAR_GRIND'),
                      (32, 'M_STEEL_SHELL'), (38, 'M_RECKLESS_RUSH'), (44, 'M_ANVIL_DROP'),
                      (50, 'M_PRIMAL_ROAR')],
            traits=('GLOWER', 'MOMENTUM'), field=('STRENGTH',), fusion=('METAL', 'BEAST'),
            desc='Woven from METAL and BEAST energy, magnetite in its blood grows iron plates over its '
                 'fur. When a pack howls together, their plates ring like far-off bells.',
            concept='armoured wolf', model=ironhowl, placeholder=False),
    KinSpec(167, 'NIMBWHALE', ('GALE', 'TIDE'), 'F', base=(140, 85, 80, 90, 95, 55), catch=45, xp=210,
            category='SKY WHALE', height=30, weight=1800,
            learnset=[(1, 'M_FIZZ'), (1, 'M_DRAFT'), (1, 'M_SLIPSTREAM'), (1, 'M_UPDRAFT'),
                      (8, 'M_UNDERTOW'), (14, 'M_CATNAP'), (20, 'M_CROSSWIND'), (26, 'M_RIPTIDE'),
                      (32, 'M_BELLY_FLOP'), (38, 'M_SWELL'), (44, 'M_STOOP'), (50, 'M_GEYSER')],
            traits=('DRIFTER', 'SOAKER'), field=('FLY', 'SURF'), fusion=('GALE', 'TIDE'),
            desc='Woven from GALE and TIDE energy, it swims the sky on rising air. Its cloud mantle '
                 'soaks up mist until it rains, and a rainbow trails it whenever it spouts.',
            concept='cloud whale', model=nimbwhale, placeholder=False),
    KinSpec(168, 'JOLLYROGUE', ('HOLLOW', 'RELIC'), 'F', base=(80, 110, 90, 95, 80, 75), catch=45, xp=210,
            category='BONE PIRATE', height=15, weight=180,
            learnset=[(1, 'M_BONE_RATTLE'), (1, 'M_CLATTER'), (1, 'M_TRINKET_TOSS'), (1, 'M_TARNISH'),
                      (8, 'M_GRAVE_CHILL'), (14, 'M_CHEST_CHOMP'), (20, 'M_SHADE_CUT'), (26, 'M_OSSIFY'),
                      (32, 'M_GILDED_GLEAM'), (38, 'M_MARROW_SIP'), (44, 'M_CURSED_CURIO'),
                      (50, 'M_HEIRLOOM'), (56, 'M_REQUIEM')],
            traits=('HOARDER', 'STUBBORN'), field=('SURF',), fusion=('HOLLOW', 'RELIC'),
            desc='Woven from HOLLOW and RELIC energy, its bones grew around an old bottled ship. It '
                 'guards the bottle with its life, and the tiny sails fill in any wind.',
            concept='skeleton pirate with a ship in a bottle', model=jollyrogue, placeholder=False),
    KinSpec(169, 'RUNELITH', ('RELIC', 'STONE'), 'F', base=(95, 70, 135, 105, 105, 35), catch=45, xp=210,
            category='RUNESTONE', height=22, weight=3900,
            learnset=[(1, 'M_PEBBLE_PELT'), (1, 'M_CLATTER'), (1, 'M_GRIT_KICK'), (1, 'M_TARNISH'),
                      (8, 'M_MUD_PIE'), (14, 'M_POLTERGUST'), (20, 'M_STONESKIN'), (26, 'M_SANDBLAST'),
                      (32, 'M_GILDED_GLEAM'), (38, 'M_ROCKFALL'), (44, 'M_CURSED_CURIO'),
                      (50, 'M_FAULTLINE'), (56, 'M_HEIRLOOM')],
            traits=('BEDROCK', 'QUICK STUDY'), field=('STRENGTH',), fusion=('RELIC', 'STONE'),
            desc='Woven from RELIC and STONE energy, it grew into a carved standing stone. Its runes '
                 'glow as it thinks, and every hundred years they spell out one new word.',
            concept='walking rune stone', model=runelith, placeholder=False),
    KinSpec(170, 'FAEFLY', ('DREAM', 'SWARM'), 'F', base=(65, 65, 65, 120, 90, 135), catch=45, xp=205,
            category='FAIRY FLY', height=9, weight=18,
            learnset=[(1, 'M_SILK_SNARE'), (1, 'M_DAYDREAM'), (1, 'M_PINCER'), (1, 'M_LULLABY'),
                      (8, 'M_WINGDUST'), (14, 'M_PRISM_RAY'), (20, 'M_SWARM_RUSH'), (26, 'M_STILL_POND'),
                      (32, 'M_CROSSWIND'), (38, 'M_DREAMQUAKE'), (44, 'M_UPDRAFT'), (50, 'M_GLINT')],
            traits=('KEEN EYE', 'MOMENTUM'), field=('TELEPORT', 'LIGHT'), fusion=('DREAM', 'SWARM'),
            desc='Woven from DREAM and SWARM energy, its four wings flash in time with every sleeper '
                 'nearby. A field of dreamers shimmers like a pond wherever it hovers.',
            concept='fairy dragonfly', model=faefly, placeholder=False),
    KinSpec(171, 'SNOWBRUTE', ('FROST', 'BRAWL'), 'F', base=(105, 130, 85, 50, 75, 85), catch=45, xp=210,
            category='YETI', height=23, weight=2900,
            learnset=[(1, 'M_RIME_SHOT'), (1, 'M_ONE_TWO'), (1, 'M_BRACE'), (1, 'M_FLURRY'),
                      (8, 'M_HAILSTONES'), (14, 'M_PUMMEL'), (20, 'M_COUNTERJAB'), (26, 'M_WAR_CRY'),
                      (32, 'M_SNOWDRIFT'), (38, 'M_HAMMER_FIST'), (44, 'M_BELLY_FLOP'), (50, 'M_HAYMAKER')],
            traits=('THICK FUR', 'BRUISER'), field=('STRENGTH',), fusion=('FROST', 'BRAWL'),
            desc='Woven from FROST and BRAWL energy. Each punch strains its bones and pumps its kernel, '
                 'which sheds the heat as frost, so its fists grow ice gauntlets mid-bout.',
            concept='yeti brawler', model=snowbrute, placeholder=False),
    KinSpec(172, 'TESLAROSE', ('BLOOM', 'SPARK'), 'F', base=(70, 65, 80, 120, 95, 105), catch=45, xp=205,
            category='ARC ROSE', height=12, weight=95,
            learnset=[(1, 'M_STATIC_POP'), (1, 'M_BRAMBLE_LASH'), (1, 'M_TINGLE'), (1, 'M_SAP_SIP'),
                      (8, 'M_LIVE_WIRE'), (14, 'M_LEAF_FLURRY'), (20, 'M_ARC_FLASH'), (26, 'M_THORN_WALL'),
                      (32, 'M_FORKED_BOLT'), (38, 'M_BASK'), (44, 'M_SUNSHAFT'), (50, 'M_OVERCHARGE')],
            traits=('STATIC FUR', 'BASKER'), field=('LIGHT',), fusion=('BLOOM', 'SPARK'),
            desc='Woven from BLOOM and SPARK energy, its petals hold charge like a capacitor. Anyone '
                 'who stoops to smell it gets a jolt, and its thorns crackle blue in a storm.',
            concept='rose that sparks', model=teslarose, placeholder=False),
    KinSpec(173, 'NOCTMARE', ('DUSK', 'DREAM'), 'F', base=(80, 80, 70, 130, 85, 115), catch=45, xp=215,
            category='NIGHTMARE', height=17, weight=700,
            learnset=[(1, 'M_STARE_DOWN'), (1, 'M_SNAP'), (1, 'M_DAYDREAM'), (1, 'M_LULLABY'),
                      (8, 'M_HAUNT'), (14, 'M_PRISM_RAY'), (20, 'M_GLOOM_ORB'), (26, 'M_SHADE_CUT'),
                      (32, 'M_STILL_POND'), (38, 'M_DREAMQUAKE'), (44, 'M_RECKLESS_RUSH')],
            traits=('GLOWER', 'FOCUSED'), field=('TELEPORT',), fusion=('DUSK', 'DREAM'),
            desc='Woven from DUSK and DREAM energy, it drinks starlight and bad dreams. Its mane is the '
                 'smoke of nightmares it has eaten, so the sleeper it visits wakes up rested.',
            concept='the nightmare horse', model=noctmare, placeholder=False),
]
