"""Kin 130-151: the first half of the fusion kin. Owner: KIN-D.

Fusion kin never appear in the wild; each is woven on the Fusion Loom from
its two signature energies (docs/EXPANSION.md 4.5 and 7.4). Base stat totals
sit in the fusion band (490-565), learnsets draw on both woven energies, and
the art lives in tools/kin/art_fusion_a.py.
"""

from kin import KinSpec
from kin import art_fusion_a as art
from kin import art_fusion_a2 as art2


def _m(name):
    """Model function for a species, or None while it is still unpainted."""
    return getattr(art, name, None) or getattr(art2, name, None)

SPECIES = [
    KinSpec(130, 'STEAMOTH', ('GALE', 'BLAZE'), 'F', base=(72, 60, 68, 118, 82, 120), catch=45, xp=205,
            category='STEAM MOTH', height=15, weight=180,
            learnset=[(1, 'M_DRAFT'), (1, 'M_CINDER_FLICK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'),
                      (12, 'M_LANTERN_LURE'), (18, 'M_UPDRAFT'), (24, 'M_WINGDUST'), (30, 'M_CROSSWIND'),
                      (36, 'M_EMBER_STORM'), (42, 'M_SWELL'), (48, 'M_KILN_BREATH'), (55, 'M_GEYSER')],
            traits=('DRIFTER', 'EMBERSKIN'), field=('FLY', 'LIGHT'), fusion=('BLAZE', 'TIDE'),
            desc='Woven when BLAZE and TIDE motes meet, its kernel boils water into lift. Brass-hard '
                 'wing scales hold the steam, and it glides on its own warm exhaust.',
            model=art.steamoth, concept='moth of steam with brass wings'),
    KinSpec(131, 'VOLTORTLE', ('SPARK', 'STONE'), 'F', base=(100, 88, 130, 92, 82, 38), catch=45, xp=205,
            category='ROD SHELL', height=12, weight=2400,
            learnset=[(1, 'M_BONK'), (1, 'M_STATIC_POP'), (1, 'M_GRIT_KICK'), (1, 'M_BRACE'),
                      (10, 'M_PEBBLE_PELT'), (16, 'M_LIVE_WIRE'), (22, 'M_STONESKIN'), (28, 'M_MUD_PIE'),
                      (34, 'M_ARC_FLASH'), (40, 'M_ROCKFALL'), (46, 'M_FORKED_BOLT'), (52, 'M_FAULTLINE'),
                      (58, 'M_OVERCHARGE')],
            traits=('CONDUCTOR', 'BEDROCK'), field=('STRENGTH',), fusion=('SPARK', 'STONE'),
            desc='SPARK and STONE energy wove a shell of piezo-rock around a spire of native copper. '
                 'It naps on hilltops in storms and drinks the lightning it calls down.',
            model=art.voltortle, concept='tortoise with a lightning-rod shell'),
    KinSpec(132, 'EMBERIME', ('BLAZE', 'FROST'), 'F', base=(70, 68, 66, 122, 80, 116), catch=45, xp=205,
            category='FROSTFIRE', height=11, weight=240,
            learnset=[(1, 'M_SWIPE'), (1, 'M_CINDER_FLICK'), (1, 'M_FLURRY'), (1, 'M_POUT'),
                      (8, 'M_RIME_SHOT'), (14, 'M_SEAR_BITE'), (20, 'M_SNOWDRIFT'), (26, 'M_LANTERN_LURE'),
                      (32, 'M_HAILSTONES'), (38, 'M_EMBER_STORM'), (44, 'M_WINTER_RAY'), (50, 'M_KILN_BREATH'),
                      (56, 'M_SUNFLARE')],
            traits=('THICK FUR', 'SURGE'), field=('LIGHT',), fusion=('BLAZE', 'FROST'),
            desc='Woven from BLAZE and FROST, its kernel pumps heat from one tail into the other like '
                 'a living heat engine. Where it walks, frost and embers melt into mist.',
            model=art.emberime, concept='fox with one fire tail and one ice tail'),
    KinSpec(133, 'OSSIFLORA', ('HOLLOW', 'BLOOM'), 'F', base=(98, 72, 92, 88, 116, 58), catch=45, xp=205,
            category='BONE BLOOM', height=16, weight=380,
            learnset=[(1, 'M_BRAMBLE_LASH'), (1, 'M_BONE_RATTLE'), (1, 'M_BRACE'), (8, 'M_SAP_SIP'),
                      (14, 'M_GRAVE_CHILL'), (20, 'M_DROWSY_POLLEN'), (26, 'M_THORN_WALL'),
                      (32, 'M_MARROW_SIP'), (38, 'M_LAST_RITES'), (44, 'M_REED_BLADE'),
                      (50, 'M_DEATH_KNELL'), (56, 'M_SUNSHAFT')],
            traits=('BASKER', 'STUBBORN'), field=(), fusion=('HOLLOW', 'BLOOM'),
            desc='HOLLOW and BLOOM energy wove bone and blossom into one kernel. Its ribs are a garden '
                 'bed: the flowers pump sunlight while the bones keep the slow warmth of old stone.',
            model=art.ossiflora, concept='skeletal deer overgrown with flowers'),
    KinSpec(134, 'COGHIVE', ('METAL', 'SWARM'), 'F', base=(84, 108, 122, 68, 90, 50), catch=45, xp=205,
            category='CLOCK HIVE', height=13, weight=1650,
            learnset=[(1, 'M_IRON_TAP'), (1, 'M_SILK_SNARE'), (1, 'M_RIVET_SHOT'), (8, 'M_PINCER'),
                      (14, 'M_MAGNET_PULL'), (20, 'M_STEEL_SHELL'), (26, 'M_WINGDUST'), (32, 'M_GEAR_GRIND'),
                      (38, 'M_SWARM_RUSH'), (44, 'M_FORGE_FLASH'), (50, 'M_ANVIL_DROP'), (56, 'M_LODE_BEAM')],
            traits=('MOMENTUM', 'HOARDER'), field=(), fusion=('METAL', 'SWARM'),
            desc='Woven of METAL and SWARM: a magnetite queen whose iron drones flash in perfect sync. '
                 'Its gears tick once for every beat of the hive, and it winds up as it fights.',
            model=art.coghive, concept='clockwork bee hive queen'),
    KinSpec(135, 'HOARDWYRM', ('RELIC', 'WYRM'), 'F', base=(104, 82, 112, 104, 88, 48), catch=45, xp=210,
            category='TREASURE', height=20, weight=3200,
            learnset=[(1, 'M_CLATTER'), (1, 'M_TARNISH'), (1, 'M_TRINKET_TOSS'), (1, 'M_GLINT'),
                      (10, 'M_WYRMBREATH'), (16, 'M_POLTERGUST'), (22, 'M_GILDED_GLEAM'), (28, 'M_SCALE_REND'),
                      (34, 'M_CHEST_CHOMP'), (40, 'M_CURSED_CURIO'), (46, 'M_WYRM_DANCE'), (52, 'M_HEIRLOOM'),
                      (58, 'M_STARFALL')],
            traits=('HOARDER', 'BEDROCK'), field=(), fusion=('RELIC', 'WYRM'),
            desc='A WYRM kernel woven with RELIC energy grows its scales from whatever it hoards. Each '
                 'coin hums with the warmth of old hands. It sleeps coiled, counting in its dreams.',
            model=art.hoardwyrm, concept='a dragon made of a treasure hoard'),
    KinSpec(136, 'STARSQUID', ('ASTRAL', 'TIDE'), 'F', base=(92, 58, 72, 124, 96, 82), catch=45, xp=205,
            category='NEBULA', height=17, weight=310,
            learnset=[(1, 'M_FIZZ'), (1, 'M_TWINKLE'), (1, 'M_SLIPSTREAM'), (1, 'M_STARDUST'),
                      (10, 'M_UNDERTOW'), (16, 'M_MOONBEAM'), (22, 'M_NEBULA_VEIL'), (28, 'M_SWELL'),
                      (34, 'M_MUON_RAIN'), (40, 'M_COMET_DASH'), (46, 'M_GEYSER'), (52, 'M_SUPERNOVA')],
            traits=('SOAKER', 'FOCUSED'), field=('SURF', 'LIGHT'), fusion=('ASTRAL', 'TIDE'),
            desc='Woven of ASTRAL and TIDE, it catches muons in the deep and spills them as glowing '
                 'ink. Sailors who see its nebula clouds at night swear stars fell into the sea.',
            model=art.starsquid, concept='squid with nebula ink'),
    KinSpec(137, 'VOLTSHARK', ('TIDE', 'SPARK'), 'F', base=(84, 124, 74, 72, 70, 116), catch=45, xp=205,
            category='DYNAMO', height=22, weight=1200,
            learnset=[(1, 'M_SLIPSTREAM'), (1, 'M_STATIC_POP'), (1, 'M_SNAP'), (1, 'M_FIZZ'),
                      (9, 'M_LIVE_WIRE'), (15, 'M_UNDERTOW'), (21, 'M_TINGLE'), (27, 'M_GNASH'),
                      (33, 'M_RIPTIDE'), (39, 'M_ARC_FLASH'), (45, 'M_RECKLESS_RUSH'), (51, 'M_FORKED_BOLT')],
            traits=('CONDUCTOR', 'MOMENTUM'), field=('SURF',), fusion=('TIDE', 'SPARK'),
            desc='TIDE and SPARK energy wove a dynamo into its dorsal fin. The faster it swims, the '
                 'more charge it makes, so it never stops. Its wake crackles like a storm.',
            model=art.voltshark, concept='shark with a dynamo fin'),
    KinSpec(138, 'DULLAHAN', ('HOLLOW', 'BEAST'), 'F', base=(96, 122, 92, 62, 86, 82), catch=45, xp=210,
            category='HEADLESS', height=17, weight=4800,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (1, 'M_DART'), (1, 'M_LANTERN_LURE'),
                      (8, 'M_BRACE'), (14, 'M_GRAVE_CHILL'), (20, 'M_SNARL'), (26, 'M_OSSIFY'),
                      (32, 'M_BELLY_FLOP'), (38, 'M_LAST_RITES'), (44, 'M_RECKLESS_RUSH'), (50, 'M_REQUIEM'),
                      (56, 'M_PRIMAL_ROAR')],
            traits=('STUBBORN', 'GLOWER'), field=('LIGHT', 'STRENGTH'), fusion=('HOLLOW', 'BEAST'),
            desc='HOLLOW and BEAST energy wove a steed whose kernel lives in the lantern it carries, '
                 'not in its body. It sees wherever the lantern shines and guides lost riders home.',
            model=_m('dullahan'), concept='headless horse carrying its lantern-head'),
    KinSpec(139, 'CHIMERAX', ('BEAST', 'VENOM'), 'F', base=(92, 112, 84, 88, 78, 90), catch=45, xp=210,
            category='THREEFOLD', height=15, weight=1450,
            learnset=[(1, 'M_SWIPE'), (1, 'M_BARB'), (1, 'M_POUT'), (1, 'M_DART'),
                      (8, 'M_SPORE_CLOUD'), (14, 'M_SNARL'), (20, 'M_ACID_SPIT'), (26, 'M_BELLY_FLOP'),
                      (32, 'M_FESTER'), (38, 'M_GLINT'), (44, 'M_BOG_BOMB'), (50, 'M_RECKLESS_RUSH'),
                      (56, 'M_PRIMAL_ROAR')],
            traits=('SPORESKIN', 'KEEN EYE'), field=('STRENGTH',), fusion=('BEAST', 'VENOM'),
            desc='Woven from BEAST and VENOM, one kernel runs three sets of instincts. The lion leads, '
                 'the goat horns keep watch, and the serpent tail never, ever sleeps.',
            model=_m('chimerax'), concept='lion, goat and serpent in one'),
    KinSpec(140, 'RIDDLEON', ('DREAM', 'STONE'), 'F', base=(94, 68, 112, 108, 110, 46), catch=45, xp=205,
            category='RIDDLE', height=14, weight=2600,
            learnset=[(1, 'M_GRIT_KICK'), (1, 'M_DAYDREAM'), (1, 'M_STILL_POND'), (1, 'M_PEBBLE_PELT'),
                      (10, 'M_MUD_PIE'), (16, 'M_LULLABY'), (22, 'M_PRISM_RAY'), (28, 'M_STONESKIN'),
                      (34, 'M_SANDBLAST'), (40, 'M_DREAMQUAKE'), (46, 'M_ROCKFALL'), (52, 'M_FAULTLINE')],
            traits=('FOCUSED', 'BEDROCK'), field=('TELEPORT',), fusion=('DREAM', 'STONE'),
            desc='DREAM and STONE energy wove a kernel that hears thoughts through rock. It asks a '
                 'riddle of every traveler, and all who answer honestly may pass, right or wrong.',
            model=_m('riddleon'), concept='sphinx that asks riddles'),
    KinSpec(141, 'GRIFFALON', ('GALE', 'BEAST'), 'F', base=(82, 124, 76, 62, 74, 124), catch=45, xp=210,
            category='SKY LION', height=19, weight=1300,
            learnset=[(1, 'M_BEAK_JAB'), (1, 'M_SWIPE'), (1, 'M_DRAFT'), (1, 'M_POUT'),
                      (9, 'M_DART'), (15, 'M_FEATHER_CUT'), (21, 'M_SNARL'), (27, 'M_UPDRAFT'),
                      (33, 'M_CROSSWIND'), (39, 'M_BELLY_FLOP'), (45, 'M_RECKLESS_RUSH'), (49, 'M_STOOP')],
            traits=('KEEN EYE', 'MOMENTUM'), field=('FLY',), fusion=('GALE', 'BEAST'),
            desc='Woven of GALE and BEAST, it has a falcon\'s eyes and a lion\'s heart. Its kernel pumps '
                 'from wind and muscle at once, so it can fly all day and still hunt at dusk.',
            model=_m('griffalon'), concept='griffin'),
    KinSpec(142, 'MANTICLAW', ('VENOM', 'BRAWL'), 'F', base=(94, 130, 82, 58, 76, 96), catch=45, xp=210,
            category='STINGFIST', height=18, weight=1100,
            learnset=[(1, 'M_BARB'), (1, 'M_ONE_TWO'), (1, 'M_SWIPE'), (1, 'M_SPORE_CLOUD'),
                      (10, 'M_HAMMER_FIST'), (16, 'M_PUMMEL'), (22, 'M_WAR_CRY'), (28, 'M_ACID_SPIT'),
                      (34, 'M_COUNTERJAB'), (40, 'M_FESTER'), (46, 'M_BOG_BOMB'), (52, 'M_HAYMAKER')],
            traits=('BRUISER', 'SPORESKIN'), field=('STRENGTH',), fusion=('VENOM', 'BRAWL'),
            desc='VENOM and BRAWL energy wove a boxer whose every punch primes the sting in its tail. '
                 'It wraps its fists before a bout and bows to its foe after.',
            model=_m('manticlaw'), concept='manticore'),
    KinSpec(143, 'INKRAKEN', ('TIDE', 'DUSK'), 'F', base=(106, 102, 86, 96, 86, 58), catch=45, xp=205,
            category='DEEP INK', height=13, weight=900,
            learnset=[(1, 'M_FIZZ'), (1, 'M_SNAP'), (1, 'M_SLIPSTREAM'), (1, 'M_STARE_DOWN'),
                      (9, 'M_UNDERTOW'), (15, 'M_HAUNT'), (21, 'M_GLOOM_ORB'), (27, 'M_RIPTIDE'),
                      (33, 'M_GNASH'), (39, 'M_SWELL'), (45, 'M_SHADE_CUT'), (51, 'M_GEYSER')],
            traits=('SLIPPERY', 'SURGE'), field=('SURF',), fusion=('TIDE', 'DUSK'),
            desc='Woven from TIDE and DUSK, a young kraken whose ink drinks light. It hides in its own '
                 'little cloud of night and tugs at boats only to ask for a bout.',
            model=_m('inkraken'), concept='young kraken of ink and dark'),
    KinSpec(144, 'OBSIDRAKE', ('STONE', 'WYRM'), 'F', base=(94, 126, 124, 70, 76, 52), catch=45, xp=210,
            category='OBSIDIAN', height=21, weight=3800,
            learnset=[(1, 'M_GRIT_KICK'), (1, 'M_PEBBLE_PELT'), (1, 'M_WYRMBREATH'), (1, 'M_BRACE'),
                      (10, 'M_STONESKIN'), (16, 'M_SCALE_REND'), (22, 'M_ROCKFALL'), (28, 'M_WYRM_DANCE'),
                      (34, 'M_SANDBLAST'), (40, 'M_FAULTLINE'), (47, 'M_KILN_BREATH'), (54, 'M_STARFALL')],
            traits=('BEDROCK', 'SURGE'), field=('STRENGTH',), fusion=('STONE', 'WYRM'),
            desc='STONE and WYRM energy, woven beside flowing lava, cooled into living black glass. '
                 'Its edges could split a hair, yet it chips them blunt before it plays.',
            model=_m('obsidrake'), concept='obsidian drake'),
    KinSpec(145, 'AURORELK', ('FROST', 'ASTRAL'), 'F', base=(86, 70, 82, 126, 98, 82), catch=45, xp=210,
            category='AURORA', height=21, weight=2900,
            learnset=[(1, 'M_BONK'), (1, 'M_FLURRY'), (1, 'M_TWINKLE'), (1, 'M_STARDUST'),
                      (10, 'M_RIME_SHOT'), (16, 'M_MOONBEAM'), (22, 'M_SNOWDRIFT'), (28, 'M_NEBULA_VEIL'),
                      (34, 'M_HAILSTONES'), (40, 'M_MUON_RAIN'), (46, 'M_WINTER_RAY'), (52, 'M_METEOR_FALL'),
                      (58, 'M_SUPERNOVA')],
            traits=('THICK FUR', 'FOCUSED'), field=('LIGHT',), fusion=('FROST', 'ASTRAL'),
            desc='Woven from FROST and ASTRAL, its antlers catch muons and glow like the aurora. '
                 'Northern herds steer by its lights on the longest night of the year.',
            model=_m('aurorelk'), concept='elk with aurora antlers'),
    KinSpec(146, 'RAIJUKO', ('SPARK', 'BEAST'), 'F', base=(74, 88, 64, 116, 70, 132), catch=45, xp=205,
            category='THUNDER', height=12, weight=280,
            learnset=[(1, 'M_STATIC_POP'), (1, 'M_DART'), (1, 'M_SWIPE'), (1, 'M_TINGLE'),
                      (9, 'M_LIVE_WIRE'), (15, 'M_SNARL'), (21, 'M_ARC_FLASH'), (27, 'M_GLINT'),
                      (33, 'M_FORKED_BOLT'), (39, 'M_BELLY_FLOP'), (45, 'M_OVERCHARGE'), (52, 'M_PRIMAL_ROAR')],
            traits=('STATIC FUR', 'MOMENTUM'), field=('LIGHT',), fusion=('SPARK', 'BEAST'),
            desc='SPARK and BEAST energy wove a beast of ball lightning. In storms it races down the '
                 'clouds and curls up in warm hay, leaving scorched rings behind.',
            model=_m('raijuko'), concept='raiju, the thunder beast'),
    KinSpec(147, 'SPOREGHOUL', ('VENOM', 'HOLLOW'), 'F', base=(102, 78, 86, 96, 114, 52), catch=45, xp=205,
            category='GRAVECAP', height=17, weight=620,
            learnset=[(1, 'M_BARB'), (1, 'M_BONE_RATTLE'), (1, 'M_SPORE_CLOUD'), (1, 'M_SHROUD'),
                      (10, 'M_GRAVE_CHILL'), (16, 'M_ACID_SPIT'), (22, 'M_MARROW_SIP'), (28, 'M_FESTER'),
                      (34, 'M_LAST_RITES'), (40, 'M_DEATH_KNELL'), (46, 'M_BOG_BOMB'), (52, 'M_REQUIEM')],
            traits=('SPORESKIN', 'SELFMEND'), field=(), fusion=('VENOM', 'HOLLOW'),
            desc='VENOM and HOLLOW woven together: a kernel that feeds on rot and old bone. Its cap '
                 'glows faintly in crypts, and its spores turn the dead into sweet, rich soil.',
            model=_m('sporeghoul'), concept='ghoul sprouting mushrooms'),
    KinSpec(148, 'CLOCKOWL', ('METAL', 'DREAM'), 'F', base=(82, 70, 112, 104, 112, 52), catch=45, xp=205,
            category='CLOCKWORK', height=11, weight=880,
            learnset=[(1, 'M_IRON_TAP'), (1, 'M_DAYDREAM'), (1, 'M_LULLABY'), (1, 'M_MAGNET_PULL'),
                      (10, 'M_FORGE_FLASH'), (16, 'M_STILL_POND'), (22, 'M_PRISM_RAY'), (28, 'M_STEEL_SHELL'),
                      (34, 'M_GEAR_GRIND'), (40, 'M_DREAMQUAKE'), (46, 'M_LODE_BEAM'), (52, 'M_ANVIL_DROP')],
            traits=('WAKEFUL', 'QUICK STUDY'), field=('TELEPORT',), fusion=('METAL', 'DREAM'),
            desc='METAL and DREAM energy wove a kernel that keeps perfect time. The clock on its chest '
                 'shows the hour you will wake, and it hoots once before every sunrise.',
            model=_m('clockowl'), concept='owl with a clock-face chest'),
    KinSpec(149, 'CINDERANT', ('BLAZE', 'SWARM'), 'F', base=(76, 122, 92, 70, 70, 108), catch=45, xp=205,
            category='COLONY', height=10, weight=680,
            learnset=[(1, 'M_CINDER_FLICK'), (1, 'M_PINCER'), (1, 'M_BONK'), (1, 'M_LAST_EMBER'),
                      (9, 'M_SEAR_BITE'), (15, 'M_BRACE'), (21, 'M_SWARM_RUSH'), (27, 'M_EMBER_STORM'),
                      (33, 'M_WAR_CRY'), (39, 'M_KILN_BREATH'), (45, 'M_RECKLESS_RUSH'), (51, 'M_SUNFLARE')],
            traits=('EMBERSKIN', 'MOMENTUM'), field=('STRENGTH', 'LIGHT'), fusion=('BLAZE', 'SWARM'),
            desc='Woven from BLAZE and SWARM, a thousand fire ants share one armoured kernel and pump '
                 'heat in perfect sync. Break it apart and it marches back together.',
            model=_m('cinderant'), concept='fire ant colony in one armour'),
    KinSpec(150, 'STARWEAVER', ('ASTRAL', 'SWARM'), 'F', base=(82, 64, 80, 126, 96, 92), catch=45, xp=210,
            category='STAR SPIDER', height=14, weight=400,
            learnset=[(1, 'M_TWINKLE'), (1, 'M_SILK_SNARE'), (1, 'M_STARDUST'), (1, 'M_BARB'),
                      (8, 'M_PINCER'), (14, 'M_MOONBEAM'), (20, 'M_NEBULA_VEIL'), (26, 'M_SWARM_RUSH'),
                      (32, 'M_MUON_RAIN'), (38, 'M_COMET_DASH'), (44, 'M_METEOR_FALL'), (50, 'M_SUPERNOVA')],
            traits=('FOCUSED', 'KEEN EYE'), field=('TELEPORT', 'LIGHT'), fusion=('ASTRAL', 'SWARM'),
            desc='ASTRAL and SWARM energy wove a spider that spins muon-lit silk. Every knot it ties '
                 'marks a star, so its web is a chart of the night sky.',
            model=_m('starweaver'), concept='spider weaving constellations'),
    KinSpec(151, 'NOSFERBAT', ('DUSK', 'HOLLOW'), 'F', base=(92, 78, 80, 114, 92, 92), catch=45, xp=210,
            category='NIGHT NOBLE', height=16, weight=520,
            learnset=[(1, 'M_SNAP'), (1, 'M_STARE_DOWN'), (1, 'M_BONE_RATTLE'), (1, 'M_SHROUD'),
                      (9, 'M_GRAVE_CHILL'), (15, 'M_MARROW_SIP'), (21, 'M_HAUNT'), (27, 'M_GNASH'),
                      (33, 'M_DEATH_KNELL'), (39, 'M_GLOOM_ORB'), (45, 'M_LAST_RITES'), (51, 'M_REQUIEM')],
            traits=('SELFMEND', 'GLOWER'), field=('FLY',), fusion=('DUSK', 'HOLLOW'),
            desc='Woven from DUSK and HOLLOW, a noble bat that sips coherence, never blood. It bows '
                 'before every bout and takes only what it needs. Its cape drinks starlight.',
            model=_m('nosferbat'), concept='vampire bat noble'),
]
