"""Kin 130-151. Owner: KIN-D (fusion kin 130-151).

PLACEHOLDER data and art: stats, learnsets, traits and descriptions
were generated from docs/EXPANSION.md; replace every entry with the real
design (keep id, name, types, rarity and growth), give it a model, and
set placeholder=False (then its base stat total is checked by tier).
"""

from kin import KinSpec

SPECIES = [
    KinSpec(130, 'STEAMOTH', ('GALE', 'BLAZE'), 'F', base=(53, 121, 54, 81, 54, 162), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (1, 'M_CINDER_FLICK'), (1, 'M_DRAFT'), (14, 'M_LAST_EMBER'), (20, 'M_LANTERN_LURE'), (26, 'M_UPDRAFT'), (32, 'M_FEATHER_CUT'), (38, 'M_SEAR_BITE'), (44, 'M_CROSSWIND'), (50, 'M_EMBER_STORM')],
            traits=('DRIFTER', 'EMBERSKIN'), field=(), fusion=('BLAZE', 'TIDE'),
            desc='Moth of steam with brass wings.',
            concept='moth of steam with brass wings', placeholder=True),
    KinSpec(131, 'VOLTORTLE', ('SPARK', 'STONE'), 'F', base=(66, 79, 92, 105, 52, 131), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_STATIC_POP'), (1, 'M_GRIT_KICK'), (1, 'M_STONESKIN'), (14, 'M_TINGLE'), (20, 'M_PEBBLE_PELT'), (26, 'M_MUD_PIE'), (32, 'M_LIVE_WIRE'), (38, 'M_ARC_FLASH'), (44, 'M_SANDBLAST'), (50, 'M_ROCKFALL')],
            traits=('STATIC FUR', 'STUBBORN'), field=(), fusion=('SPARK', 'STONE'),
            desc='Tortoise with a lightning-rod shell.',
            concept='tortoise with a lightning-rod shell', placeholder=True),
    KinSpec(132, 'EMBERIME', ('BLAZE', 'FROST'), 'F', base=(54, 81, 67, 135, 67, 121), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (1, 'M_CINDER_FLICK'), (1, 'M_FLURRY'), (14, 'M_LAST_EMBER'), (20, 'M_RIME_SHOT'), (26, 'M_LANTERN_LURE'), (32, 'M_SNOWDRIFT'), (38, 'M_SEAR_BITE'), (44, 'M_EMBER_STORM'), (50, 'M_KILN_BREATH')],
            traits=('SURGE', 'KEEN EYE'), field=(), fusion=('BLAZE', 'FROST'),
            desc='Fox with one fire tail and one ice tail.',
            concept='fox with one fire tail and one ice tail', placeholder=True),
    KinSpec(133, 'OSSIFLORA', ('HOLLOW', 'BLOOM'), 'F', base=(94, 54, 121, 67, 135, 54), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_BONE_RATTLE'), (1, 'M_BASK'), (14, 'M_BRAMBLE_LASH'), (20, 'M_DROWSY_POLLEN'), (26, 'M_LAST_RITES'), (32, 'M_SHROUD'), (38, 'M_THORN_WALL'), (44, 'M_SAP_SIP'), (50, 'M_GRAVE_CHILL')],
            traits=('STUBBORN', 'SPORESKIN'), field=(), fusion=('HOLLOW', 'BLOOM'),
            desc='Skeletal deer overgrown with flowers.',
            concept='skeletal deer overgrown with flowers', placeholder=True),
    KinSpec(134, 'COGHIVE', ('METAL', 'SWARM'), 'F', base=(51, 128, 128, 51, 77, 90), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (1, 'M_IRON_TAP'), (1, 'M_MAGNET_PULL'), (14, 'M_SILK_SNARE'), (20, 'M_STEEL_SHELL'), (26, 'M_FORGE_FLASH'), (32, 'M_PINCER'), (38, 'M_WINGDUST'), (44, 'M_SWARM_RUSH'), (50, 'M_GEAR_GRIND')],
            traits=('BEDROCK', 'MOMENTUM'), field=(), fusion=('METAL', 'SWARM'),
            desc='Clockwork bee hive queen.',
            concept='clockwork bee hive queen', placeholder=True),
    KinSpec(135, 'HOARDWYRM', ('RELIC', 'WYRM'), 'F', base=(64, 77, 128, 128, 77, 51), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_CLATTER'), (1, 'M_TARNISH'), (14, 'M_WYRM_DANCE'), (20, 'M_WYRMBREATH'), (26, 'M_POLTERGUST'), (32, 'M_GILDED_GLEAM'), (38, 'M_CHEST_CHOMP'), (44, 'M_SCALE_REND'), (50, 'M_CURSED_CURIO')],
            traits=('HOARDER', 'SURGE'), field=(), fusion=('RELIC', 'WYRM'),
            desc='A dragon made of a treasure hoard.',
            concept='a dragon made of a treasure hoard', placeholder=True),
    KinSpec(136, 'STARSQUID', ('ASTRAL', 'TIDE'), 'F', base=(135, 54, 67, 148, 67, 54), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_TWINKLE'), (14, 'M_NEBULA_VEIL'), (20, 'M_STARDUST'), (26, 'M_MOONBEAM'), (32, 'M_UNDERTOW'), (38, 'M_RIPTIDE'), (44, 'M_COMET_DASH'), (50, 'M_MUON_RAIN')],
            traits=('FOCUSED', 'SOAKER'), field=(), fusion=('ASTRAL', 'TIDE'),
            desc='Squid with nebula ink.',
            concept='squid with nebula ink', placeholder=True),
    KinSpec(137, 'VOLTSHARK', ('TIDE', 'SPARK'), 'F', base=(107, 54, 81, 108, 81, 94), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_STATIC_POP'), (14, 'M_TINGLE'), (20, 'M_LIVE_WIRE'), (26, 'M_UNDERTOW'), (32, 'M_ARC_FLASH'), (38, 'M_RIPTIDE'), (44, 'M_FORKED_BOLT'), (50, 'M_SWELL')],
            traits=('SURGE', 'CONDUCTOR'), field=(), fusion=('TIDE', 'SPARK'),
            desc='Shark with a dynamo fin.',
            concept='shark with a dynamo fin', placeholder=True),
    KinSpec(138, 'DULLAHAN', ('HOLLOW', 'BEAST'), 'F', base=(105, 66, 105, 52, 118, 79), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (1, 'M_DART'), (1, 'M_SWIPE'), (14, 'M_BRACE'), (20, 'M_CATNAP'), (26, 'M_LAST_RITES'), (32, 'M_POUT'), (38, 'M_SHROUD'), (44, 'M_GRAVE_CHILL'), (50, 'M_SNARL')],
            traits=('STUBBORN', 'MOMENTUM'), field=(), fusion=('HOLLOW', 'BEAST'),
            desc='Headless horse carrying its lantern-head.',
            concept='headless horse carrying its lantern-head', placeholder=True),
    KinSpec(139, 'CHIMERAX', ('BEAST', 'VENOM'), 'F', base=(116, 90, 51, 64, 102, 102), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BARB'), (1, 'M_DART'), (1, 'M_SWIPE'), (14, 'M_BRACE'), (20, 'M_CATNAP'), (26, 'M_POUT'), (32, 'M_SPORE_CLOUD'), (38, 'M_SNARL'), (44, 'M_ACID_SPIT'), (50, 'M_GLINT')],
            traits=('KEEN EYE', 'SELFMEND'), field=(), fusion=('BEAST', 'VENOM'),
            desc='Lion, goat and serpent in one.',
            concept='lion, goat and serpent in one', placeholder=True),
    KinSpec(140, 'RIDDLEON', ('DREAM', 'STONE'), 'F', base=(66, 79, 92, 131, 105, 52), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_GRIT_KICK'), (1, 'M_LULLABY'), (1, 'M_STILL_POND'), (14, 'M_STONESKIN'), (20, 'M_DAYDREAM'), (26, 'M_PEBBLE_PELT'), (32, 'M_MUD_PIE'), (38, 'M_PRISM_RAY'), (44, 'M_SANDBLAST'), (50, 'M_ROCKFALL')],
            traits=('FOCUSED', 'STUBBORN'), field=(), fusion=('DREAM', 'STONE'),
            desc='Sphinx that asks riddles.',
            concept='sphinx that asks riddles', placeholder=True),
    KinSpec(141, 'GRIFFALON', ('GALE', 'BEAST'), 'F', base=(79, 118, 52, 52, 66, 158), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (1, 'M_DART'), (1, 'M_DRAFT'), (14, 'M_SWIPE'), (20, 'M_BRACE'), (26, 'M_CATNAP'), (32, 'M_POUT'), (38, 'M_UPDRAFT'), (44, 'M_SNARL'), (50, 'M_FEATHER_CUT')],
            traits=('DRIFTER', 'MOMENTUM'), field=(), fusion=('GALE', 'BEAST'),
            desc='Griffin.',
            concept='griffin', placeholder=True),
    KinSpec(142, 'MANTICLAW', ('VENOM', 'BRAWL'), 'F', base=(105, 118, 52, 79, 105, 66), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (1, 'M_ONE_TWO'), (1, 'M_BARB'), (14, 'M_SPORE_CLOUD'), (20, 'M_WAR_CRY'), (26, 'M_HAMMER_FIST'), (32, 'M_ACID_SPIT'), (38, 'M_COUNTERJAB'), (44, 'M_FESTER'), (50, 'M_BOG_BOMB')],
            traits=('SPORESKIN', 'STUBBORN'), field=(), fusion=('VENOM', 'BRAWL'),
            desc='Manticore.',
            concept='manticore', placeholder=True),
    KinSpec(143, 'INKRAKEN', ('TIDE', 'DUSK'), 'F', base=(107, 54, 81, 121, 81, 81), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_STARE_DOWN'), (14, 'M_SNAP'), (20, 'M_UNDERTOW'), (26, 'M_HAUNT'), (32, 'M_SHADE_CUT'), (38, 'M_RIPTIDE'), (44, 'M_GLOOM_ORB'), (50, 'M_GNASH')],
            traits=('SURGE', 'SLIPPERY'), field=(), fusion=('TIDE', 'DUSK'),
            desc='Young kraken of ink and dark.',
            concept='young kraken of ink and dark', placeholder=True),
    KinSpec(144, 'OBSIDRAKE', ('STONE', 'WYRM'), 'F', base=(90, 128, 128, 77, 51, 51), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_GRIT_KICK'), (1, 'M_STONESKIN'), (1, 'M_WYRM_DANCE'), (14, 'M_PEBBLE_PELT'), (20, 'M_MUD_PIE'), (26, 'M_WYRMBREATH'), (32, 'M_SANDBLAST'), (38, 'M_ROCKFALL'), (44, 'M_SCALE_REND'), (50, 'M_FAULTLINE')],
            traits=('BEDROCK', 'SURGE'), field=(), fusion=('STONE', 'WYRM'),
            desc='Obsidian drake.',
            concept='obsidian drake', placeholder=True),
    KinSpec(145, 'AURORELK', ('FROST', 'ASTRAL'), 'F', base=(80, 54, 81, 148, 81, 81), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (1, 'M_FLURRY'), (1, 'M_RIME_SHOT'), (14, 'M_TWINKLE'), (20, 'M_NEBULA_VEIL'), (26, 'M_SNOWDRIFT'), (32, 'M_STARDUST'), (38, 'M_MOONBEAM'), (44, 'M_COMET_DASH'), (50, 'M_MUON_RAIN')],
            traits=('THICK FUR', 'QUICK STUDY'), field=(), fusion=('FROST', 'ASTRAL'),
            desc='Elk with aurora antlers.',
            concept='elk with aurora antlers', placeholder=True),
    KinSpec(146, 'RAIJUKO', ('SPARK', 'BEAST'), 'F', base=(78, 66, 52, 105, 66, 158), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (1, 'M_DART'), (1, 'M_STATIC_POP'), (14, 'M_BRACE'), (20, 'M_CATNAP'), (26, 'M_POUT'), (32, 'M_TINGLE'), (38, 'M_SNARL'), (44, 'M_GLINT'), (50, 'M_LIVE_WIRE')],
            traits=('STATIC FUR', 'MOMENTUM'), field=(), fusion=('SPARK', 'BEAST'),
            desc='Raiju, the thunder beast.',
            concept='raiju, the thunder beast', placeholder=True),
    KinSpec(147, 'SPOREGHOUL', ('VENOM', 'HOLLOW'), 'F', base=(93, 81, 81, 81, 135, 54), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BARB'), (1, 'M_BONE_RATTLE'), (1, 'M_LAST_RITES'), (14, 'M_SHROUD'), (20, 'M_SPORE_CLOUD'), (26, 'M_GRAVE_CHILL'), (32, 'M_ACID_SPIT'), (38, 'M_MARROW_SIP'), (44, 'M_FESTER'), (50, 'M_OSSIFY')],
            traits=('SPORESKIN', 'SELFMEND'), field=(), fusion=('VENOM', 'HOLLOW'),
            desc='Ghoul sprouting mushrooms.',
            concept='ghoul sprouting mushrooms', placeholder=True),
    KinSpec(148, 'CLOCKOWL', ('METAL', 'DREAM'), 'F', base=(52, 102, 128, 90, 102, 51), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (1, 'M_IRON_TAP'), (1, 'M_LULLABY'), (14, 'M_MAGNET_PULL'), (20, 'M_STEEL_SHELL'), (26, 'M_STILL_POND'), (32, 'M_DAYDREAM'), (38, 'M_FORGE_FLASH'), (44, 'M_PRISM_RAY'), (50, 'M_GEAR_GRIND')],
            traits=('BEDROCK', 'WAKEFUL'), field=(), fusion=('METAL', 'DREAM'),
            desc='Owl with a clock-face chest.',
            concept='owl with a clock-face chest', placeholder=True),
    KinSpec(149, 'CINDERANT', ('BLAZE', 'SWARM'), 'F', base=(53, 108, 54, 108, 54, 148), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_CINDER_FLICK'), (1, 'M_LAST_EMBER'), (1, 'M_LANTERN_LURE'), (14, 'M_SILK_SNARE'), (20, 'M_PINCER'), (26, 'M_WINGDUST'), (32, 'M_SEAR_BITE'), (38, 'M_EMBER_STORM'), (44, 'M_SWARM_RUSH'), (50, 'M_KILN_BREATH')],
            traits=('SURGE', 'MOMENTUM'), field=(), fusion=('BLAZE', 'SWARM'),
            desc='Fire ant colony in one armour.',
            concept='fire ant colony in one armour', placeholder=True),
    KinSpec(150, 'STARWEAVER', ('ASTRAL', 'SWARM'), 'F', base=(107, 81, 54, 135, 54, 94), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TWINKLE'), (1, 'M_NEBULA_VEIL'), (1, 'M_SILK_SNARE'), (14, 'M_STARDUST'), (20, 'M_PINCER'), (26, 'M_WINGDUST'), (32, 'M_MOONBEAM'), (38, 'M_SWARM_RUSH'), (44, 'M_COMET_DASH'), (50, 'M_MUON_RAIN')],
            traits=('FOCUSED', 'MOMENTUM'), field=(), fusion=('ASTRAL', 'SWARM'),
            desc='Spider weaving constellations.',
            concept='spider weaving constellations', placeholder=True),
    KinSpec(151, 'NOSFERBAT', ('DUSK', 'HOLLOW'), 'F', base=(66, 54, 81, 135, 81, 108), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (1, 'M_LAST_RITES'), (1, 'M_SHROUD'), (14, 'M_STARE_DOWN'), (20, 'M_GRAVE_CHILL'), (26, 'M_MARROW_SIP'), (32, 'M_SNAP'), (38, 'M_HAUNT'), (44, 'M_SHADE_CUT'), (50, 'M_GLOOM_ORB')],
            traits=('FOCUSED', 'SELFMEND'), field=(), fusion=('DUSK', 'HOLLOW'),
            desc='Vampire bat noble.',
            concept='vampire bat noble', placeholder=True),
]
