"""Kin 152-173. Owner: KIN-E (fusion kin 152-173).

PLACEHOLDER data and art: stats, learnsets, traits and descriptions
were generated from docs/EXPANSION.md; replace every entry with the real
design (keep id, name, types, rarity and growth), give it a model, and
set placeholder=False (then its base stat total is checked by tier).
"""

from kin import KinSpec

SPECIES = [
    KinSpec(152, 'BARKOLEM', ('BLOOM', 'STONE'), 'F', base=(92, 79, 118, 79, 105, 52), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_BASK'), (1, 'M_BRAMBLE_LASH'), (14, 'M_DROWSY_POLLEN'), (20, 'M_GRIT_KICK'), (26, 'M_STONESKIN'), (32, 'M_THORN_WALL'), (38, 'M_PEBBLE_PELT'), (44, 'M_SAP_SIP'), (50, 'M_LEAF_FLURRY')],
            traits=('BASKER', 'STUBBORN'), field=(), fusion=('BLOOM', 'STONE'),
            desc='Stump golem with a birdhouse.',
            concept='stump golem with a birdhouse', placeholder=True),
    KinSpec(153, 'PORCELYNX', ('RELIC', 'FROST'), 'F', base=(51, 51, 141, 128, 90, 64), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_HAILSTONES'), (1, 'M_CLATTER'), (14, 'M_FLURRY'), (20, 'M_RIME_SHOT'), (26, 'M_SNOWDRIFT'), (32, 'M_TARNISH'), (38, 'M_POLTERGUST'), (44, 'M_GILDED_GLEAM'), (50, 'M_CHEST_CHOMP')],
            traits=('HOARDER', 'SURGE'), field=(), fusion=('RELIC', 'FROST'),
            desc='Porcelain lynx with frost glaze.',
            concept='porcelain lynx with frost glaze', placeholder=True),
    KinSpec(154, 'KABUTORAI', ('METAL', 'BRAWL'), 'F', base=(75, 138, 125, 50, 75, 62), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (1, 'M_RIVET_SHOT'), (1, 'M_ONE_TWO'), (14, 'M_IRON_TAP'), (20, 'M_MAGNET_PULL'), (26, 'M_STEEL_SHELL'), (32, 'M_WAR_CRY'), (38, 'M_HAMMER_FIST'), (44, 'M_COUNTERJAB'), (50, 'M_FORGE_FLASH')],
            traits=('BEDROCK', 'STUBBORN'), field=(), fusion=('METAL', 'BRAWL'),
            desc='Samurai beetle.',
            concept='samurai beetle', placeholder=True),
    KinSpec(155, 'DROWNJELLY', ('TIDE', 'HOLLOW'), 'F', base=(120, 54, 108, 81, 108, 54), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (14, 'M_LAST_RITES'), (20, 'M_SHROUD'), (26, 'M_GRAVE_CHILL'), (32, 'M_MARROW_SIP'), (38, 'M_UNDERTOW'), (44, 'M_RIPTIDE'), (50, 'M_OSSIFY')],
            traits=('SURGE', 'SELFMEND'), field=(), fusion=('TIDE', 'HOLLOW'),
            desc='Drowned jellyfish lantern.',
            concept='drowned jellyfish lantern', placeholder=True),
    KinSpec(156, 'SUNMANE', ('BLOOM', 'BLAZE'), 'F', base=(80, 67, 81, 108, 108, 81), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_CINDER_FLICK'), (1, 'M_LAST_EMBER'), (14, 'M_BASK'), (20, 'M_BRAMBLE_LASH'), (26, 'M_DROWSY_POLLEN'), (32, 'M_LANTERN_LURE'), (38, 'M_THORN_WALL'), (44, 'M_SAP_SIP'), (50, 'M_LEAF_FLURRY')],
            traits=('BASKER', 'EMBERSKIN'), field=(), fusion=('BLOOM', 'BLAZE'),
            desc='Lion with a sunflower mane.',
            concept='lion with a sunflower mane', placeholder=True),
    KinSpec(157, 'DREAMKITE', ('DREAM', 'GALE'), 'F', base=(53, 81, 54, 135, 108, 94), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (1, 'M_DRAFT'), (1, 'M_LULLABY'), (14, 'M_STILL_POND'), (20, 'M_UPDRAFT'), (26, 'M_DAYDREAM'), (32, 'M_FEATHER_CUT'), (38, 'M_PRISM_RAY'), (44, 'M_CROSSWIND'), (50, 'M_DREAMQUAKE')],
            traits=('FOCUSED', 'MOMENTUM'), field=(), fusion=('DREAM', 'GALE'),
            desc='Kite-shaped dream spirit.',
            concept='kite-shaped dream spirit', placeholder=True),
    KinSpec(158, 'BOGNEWT', ('VENOM', 'TIDE'), 'F', base=(108, 81, 67, 94, 121, 54), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BARB'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (14, 'M_SPORE_CLOUD'), (20, 'M_ACID_SPIT'), (26, 'M_FESTER'), (32, 'M_UNDERTOW'), (38, 'M_RIPTIDE'), (44, 'M_BOG_BOMB'), (50, 'M_SWELL')],
            traits=('SPORESKIN', 'SOAKER'), field=(), fusion=('VENOM', 'TIDE'),
            desc='Toxic bog newt.',
            concept='toxic bog newt', placeholder=True),
    KinSpec(159, 'RIMEGOLEM', ('FROST', 'STONE'), 'F', base=(65, 79, 118, 105, 79, 79), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (1, 'M_FLURRY'), (1, 'M_RIME_SHOT'), (14, 'M_GRIT_KICK'), (20, 'M_SNOWDRIFT'), (26, 'M_STONESKIN'), (32, 'M_PEBBLE_PELT'), (38, 'M_MUD_PIE'), (44, 'M_SANDBLAST'), (50, 'M_ROCKFALL')],
            traits=('THICK FUR', 'STUBBORN'), field=(), fusion=('FROST', 'STONE'),
            desc='Ice golem.',
            concept='ice golem', placeholder=True),
    KinSpec(160, 'DYNAMOLE', ('METAL', 'SPARK'), 'F', base=(51, 102, 128, 77, 77, 90), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (1, 'M_IRON_TAP'), (1, 'M_STATIC_POP'), (14, 'M_MAGNET_PULL'), (20, 'M_STEEL_SHELL'), (26, 'M_TINGLE'), (32, 'M_FORGE_FLASH'), (38, 'M_LIVE_WIRE'), (44, 'M_ARC_FLASH'), (50, 'M_GEAR_GRIND')],
            traits=('BEDROCK', 'CONDUCTOR'), field=(), fusion=('METAL', 'SPARK'),
            desc='Mole with a dynamo.',
            concept='mole with a dynamo', placeholder=True),
    KinSpec(161, 'LULLABOX', ('RELIC', 'DREAM'), 'F', base=(52, 51, 128, 141, 102, 51), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_CLATTER'), (1, 'M_LULLABY'), (14, 'M_STILL_POND'), (20, 'M_TARNISH'), (26, 'M_DAYDREAM'), (32, 'M_POLTERGUST'), (38, 'M_PRISM_RAY'), (44, 'M_GILDED_GLEAM'), (50, 'M_CHEST_CHOMP')],
            traits=('HOARDER', 'WAKEFUL'), field=(), fusion=('RELIC', 'DREAM'),
            desc='Music box that sings lullabies.',
            concept='music box that sings lullabies', placeholder=True),
    KinSpec(162, 'KITSUFLAME', ('BLAZE', 'DREAM'), 'F', base=(53, 81, 54, 148, 81, 108), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_CINDER_FLICK'), (1, 'M_LAST_EMBER'), (1, 'M_LANTERN_LURE'), (14, 'M_LULLABY'), (20, 'M_STILL_POND'), (26, 'M_DAYDREAM'), (32, 'M_PRISM_RAY'), (38, 'M_SEAR_BITE'), (44, 'M_EMBER_STORM'), (50, 'M_DREAMQUAKE')],
            traits=('SURGE', 'WAKEFUL'), field=(), fusion=('BLAZE', 'DREAM'),
            desc='Nine-tailed fox of foxfire.',
            concept='nine-tailed fox of foxfire', placeholder=True),
    KinSpec(163, 'WYVERNIX', ('GALE', 'WYRM'), 'F', base=(66, 135, 54, 81, 54, 135), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (1, 'M_DRAFT'), (1, 'M_UPDRAFT'), (14, 'M_WYRM_DANCE'), (20, 'M_FEATHER_CUT'), (26, 'M_WYRMBREATH'), (32, 'M_CROSSWIND'), (38, 'M_SCALE_REND'), (44, 'M_STOOP'), (50, 'M_STARFALL')],
            traits=('DRIFTER', 'SURGE'), field=(), fusion=('GALE', 'WYRM'),
            desc='Wyvern.',
            concept='wyvern', placeholder=True),
    KinSpec(164, 'TRIHYDRA', ('VENOM', 'WYRM'), 'F', base=(93, 108, 54, 108, 108, 54), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BARB'), (1, 'M_SPORE_CLOUD'), (1, 'M_WYRM_DANCE'), (14, 'M_ACID_SPIT'), (20, 'M_WYRMBREATH'), (26, 'M_FESTER'), (32, 'M_SCALE_REND'), (38, 'M_BOG_BOMB'), (44, 'M_STARFALL')],
            traits=('SPORESKIN', 'SURGE'), field=(), fusion=('VENOM', 'WYRM'),
            desc='Three-headed hydra.',
            concept='three-headed hydra', placeholder=True),
    KinSpec(165, 'PHOENEX', ('BLAZE', 'ASTRAL'), 'F', base=(80, 81, 54, 148, 54, 108), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_CINDER_FLICK'), (1, 'M_LAST_EMBER'), (1, 'M_TWINKLE'), (14, 'M_LANTERN_LURE'), (20, 'M_NEBULA_VEIL'), (26, 'M_STARDUST'), (32, 'M_MOONBEAM'), (38, 'M_SEAR_BITE'), (44, 'M_EMBER_STORM'), (50, 'M_COMET_DASH')],
            traits=('SURGE', 'QUICK STUDY'), field=(), fusion=('BLAZE', 'ASTRAL'),
            desc='Phoenix of starfire.',
            concept='phoenix of starfire', placeholder=True),
    KinSpec(166, 'IRONHOWL', ('METAL', 'BEAST'), 'F', base=(75, 112, 125, 50, 88, 75), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (1, 'M_DART'), (1, 'M_IRON_TAP'), (14, 'M_SWIPE'), (20, 'M_BRACE'), (26, 'M_CATNAP'), (32, 'M_MAGNET_PULL'), (38, 'M_POUT'), (44, 'M_STEEL_SHELL'), (50, 'M_SNARL')],
            traits=('BEDROCK', 'MOMENTUM'), field=(), fusion=('METAL', 'BEAST'),
            desc='Armoured wolf.',
            concept='armoured wolf', placeholder=True),
    KinSpec(167, 'NIMBWHALE', ('GALE', 'TIDE'), 'F', base=(81, 108, 67, 67, 67, 135), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (1, 'M_DRAFT'), (1, 'M_FIZZ'), (14, 'M_SLIPSTREAM'), (20, 'M_UPDRAFT'), (26, 'M_FEATHER_CUT'), (32, 'M_UNDERTOW'), (38, 'M_CROSSWIND'), (44, 'M_RIPTIDE'), (50, 'M_SWELL')],
            traits=('DRIFTER', 'SOAKER'), field=(), fusion=('GALE', 'TIDE'),
            desc='Cloud whale.',
            concept='cloud whale', placeholder=True),
    KinSpec(168, 'JOLLYROGUE', ('HOLLOW', 'RELIC'), 'F', base=(80, 52, 144, 79, 118, 52), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_BONE_RATTLE'), (1, 'M_CLATTER'), (14, 'M_LAST_RITES'), (20, 'M_SHROUD'), (26, 'M_TARNISH'), (32, 'M_GRAVE_CHILL'), (38, 'M_MARROW_SIP'), (44, 'M_POLTERGUST'), (50, 'M_GILDED_GLEAM')],
            traits=('STUBBORN', 'BEDROCK'), field=(), fusion=('HOLLOW', 'RELIC'),
            desc='Skeleton pirate with a ship in a bottle.',
            concept='skeleton pirate with a ship in a bottle', placeholder=True),
    KinSpec(169, 'RUNELITH', ('RELIC', 'STONE'), 'F', base=(63, 75, 162, 100, 75, 50), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_CLATTER'), (1, 'M_GRIT_KICK'), (14, 'M_STONESKIN'), (20, 'M_TARNISH'), (26, 'M_PEBBLE_PELT'), (32, 'M_MUD_PIE'), (38, 'M_POLTERGUST'), (44, 'M_GILDED_GLEAM'), (50, 'M_SANDBLAST')],
            traits=('HOARDER', 'STUBBORN'), field=(), fusion=('RELIC', 'STONE'),
            desc='Walking rune stone.',
            concept='walking rune stone', placeholder=True),
    KinSpec(170, 'FAEFLY', ('DREAM', 'SWARM'), 'F', base=(53, 81, 54, 135, 108, 94), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_LULLABY'), (1, 'M_SILK_SNARE'), (1, 'M_STILL_POND'), (14, 'M_DAYDREAM'), (20, 'M_PINCER'), (26, 'M_WINGDUST'), (32, 'M_PRISM_RAY'), (38, 'M_SWARM_RUSH'), (44, 'M_DREAMQUAKE')],
            traits=('FOCUSED', 'MOMENTUM'), field=(), fusion=('DREAM', 'SWARM'),
            desc='Fairy dragonfly.',
            concept='fairy dragonfly', placeholder=True),
    KinSpec(171, 'SNOWBRUTE', ('FROST', 'BRAWL'), 'F', base=(78, 92, 79, 105, 79, 92), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (1, 'M_HAILSTONES'), (1, 'M_ONE_TWO'), (14, 'M_FLURRY'), (20, 'M_RIME_SHOT'), (26, 'M_SNOWDRIFT'), (32, 'M_WAR_CRY'), (38, 'M_HAMMER_FIST'), (44, 'M_COUNTERJAB'), (50, 'M_WINTER_RAY')],
            traits=('THICK FUR', 'STUBBORN'), field=(), fusion=('FROST', 'BRAWL'),
            desc='Yeti brawler.',
            concept='yeti brawler', placeholder=True),
    KinSpec(172, 'TESLAROSE', ('BLOOM', 'SPARK'), 'F', base=(80, 54, 81, 108, 108, 94), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_STATIC_POP'), (1, 'M_BASK'), (14, 'M_BRAMBLE_LASH'), (20, 'M_DROWSY_POLLEN'), (26, 'M_THORN_WALL'), (32, 'M_TINGLE'), (38, 'M_SAP_SIP'), (44, 'M_LEAF_FLURRY'), (50, 'M_LIVE_WIRE')],
            traits=('BASKER', 'CONDUCTOR'), field=(), fusion=('BLOOM', 'SPARK'),
            desc='Rose that sparks.',
            concept='rose that sparks', placeholder=True),
    KinSpec(173, 'NOCTMARE', ('DUSK', 'DREAM'), 'F', base=(53, 54, 54, 175, 81, 108), catch=45, xp=210, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_LULLABY'), (1, 'M_STARE_DOWN'), (1, 'M_STILL_POND'), (14, 'M_DAYDREAM'), (20, 'M_SNAP'), (26, 'M_PRISM_RAY'), (32, 'M_HAUNT'), (38, 'M_SHADE_CUT'), (44, 'M_GLOOM_ORB'), (50, 'M_GNASH')],
            traits=('FOCUSED', 'WAKEFUL'), field=(), fusion=('DUSK', 'DREAM'),
            desc='The nightmare horse.',
            concept='the nightmare horse', placeholder=True),
]
