"""Kin 67-100. Owner: KIN-B (new common/uncommon kin 67-100).

PLACEHOLDER data and art: stats, learnsets, traits and descriptions
were generated from docs/EXPANSION.md; replace every entry with the real
design (keep id, name, types, rarity and growth), give it a model, and
set placeholder=False (then its base stat total is checked by tier).
"""

from kin import KinSpec

SPECIES = [
    KinSpec(67, 'QUARTZPEDE', ('STONE', 'SWARM'), 'U', base=(73, 122, 122, 49, 49, 85), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_GRIT_KICK'), (1, 'M_SILK_SNARE'), (1, 'M_STONESKIN'), (14, 'M_PEBBLE_PELT'), (20, 'M_MUD_PIE'), (26, 'M_PINCER'), (32, 'M_WINGDUST'), (38, 'M_SANDBLAST'), (44, 'M_ROCKFALL'), (50, 'M_SWARM_RUSH')],
            traits=('BEDROCK', 'MOMENTUM'), field=('LIGHT',),
            desc='Crystal centipede.',
            concept='crystal centipede', placeholder=True),
    KinSpec(68, 'FLYSQUIRL', ('GALE', 'BEAST'), 'C', base=(47, 71, 32, 32, 39, 94), catch=190, xp=60, evo=('LEVEL', 24, 'GALESQUIRL'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (5, 'M_DART'), (10, 'M_DRAFT'), (15, 'M_SWIPE'), (20, 'M_BRACE'), (25, 'M_CATNAP'), (30, 'M_POUT'), (35, 'M_UPDRAFT'), (40, 'M_SNARL'), (45, 'M_FEATHER_CUT')],
            traits=('DRIFTER', 'MOMENTUM'), field=(),
            desc='Flying squirrel.',
            concept='flying squirrel', placeholder=True),
    KinSpec(69, 'GALESQUIRL', ('GALE', 'BEAST'), 'U', base=(76, 112, 50, 50, 62, 150), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (1, 'M_DART'), (1, 'M_DRAFT'), (14, 'M_SWIPE'), (20, 'M_BRACE'), (26, 'M_CATNAP'), (32, 'M_POUT'), (38, 'M_UPDRAFT'), (44, 'M_SNARL'), (50, 'M_FEATHER_CUT')],
            traits=('DRIFTER', 'MOMENTUM'), field=(),
            desc='Big glider squirrel, cape-like membrane.',
            concept='big glider squirrel, cape-like membrane', placeholder=True),
    KinSpec(70, 'DOZLOTH', ('DREAM', 'BEAST'), 'C', base=(47, 39, 32, 79, 71, 47), catch=190, xp=60, evo=('LEVEL', 32, 'SOMNISLOTH'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (5, 'M_DART'), (10, 'M_BRACE'), (15, 'M_CATNAP'), (20, 'M_LULLABY'), (25, 'M_POUT'), (30, 'M_STILL_POND'), (35, 'M_DAYDREAM'), (40, 'M_SNARL'), (45, 'M_GLINT')],
            traits=('FOCUSED', 'MOMENTUM'), field=(),
            desc='Sloth that naps upside down.',
            concept='sloth that naps upside down', placeholder=True),
    KinSpec(71, 'SOMNISLOTH', ('DREAM', 'BEAST'), 'U', base=(76, 62, 50, 125, 112, 75), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (1, 'M_DART'), (1, 'M_BRACE'), (14, 'M_CATNAP'), (20, 'M_LULLABY'), (26, 'M_POUT'), (32, 'M_STILL_POND'), (38, 'M_DAYDREAM'), (44, 'M_SNARL'), (50, 'M_GLINT')],
            traits=('FOCUSED', 'MOMENTUM'), field=('TELEPORT',),
            desc='Moss-draped sloth with a sleep aura.',
            concept='moss-draped sloth with a sleep aura', placeholder=True),
    KinSpec(72, 'SCYTHLING', ('SWARM',), 'C', base=(37, 74, 37, 37, 37, 93), catch=190, xp=60, evo=('LEVEL', 30, 'REAPMANTIS'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SILK_SNARE'), (5, 'M_PINCER'), (10, 'M_WINGDUST'), (15, 'M_SWARM_RUSH')],
            traits=('KEEN EYE', 'MOMENTUM'), field=(),
            desc='Mantis nymph.',
            concept='mantis nymph', placeholder=True),
    KinSpec(73, 'REAPMANTIS', ('SWARM', 'HOLLOW'), 'U', base=(64, 103, 77, 51, 77, 128), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (1, 'M_LAST_RITES'), (1, 'M_SHROUD'), (14, 'M_SILK_SNARE'), (20, 'M_GRAVE_CHILL'), (26, 'M_MARROW_SIP'), (32, 'M_PINCER'), (38, 'M_WINGDUST'), (44, 'M_SWARM_RUSH'), (50, 'M_OSSIFY')],
            traits=('KEEN EYE', 'SELFMEND'), field=(),
            desc='Reaper mantis with bone scythes.',
            concept='reaper mantis with bone scythes', placeholder=True),
    KinSpec(74, 'MAGNITICK', ('SWARM', 'METAL'), 'C', base=(31, 79, 55, 32, 39, 79), catch=190, xp=60, evo=('LEVEL', 28, 'LODEHORN'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (5, 'M_IRON_TAP'), (10, 'M_MAGNET_PULL'), (15, 'M_SILK_SNARE'), (20, 'M_STEEL_SHELL'), (25, 'M_FORGE_FLASH'), (30, 'M_PINCER'), (35, 'M_WINGDUST'), (40, 'M_SWARM_RUSH'), (45, 'M_GEAR_GRIND')],
            traits=('KEEN EYE', 'BRUISER'), field=(),
            desc='Iron beetle grub that sticks to metal.',
            concept='iron beetle grub that sticks to metal', placeholder=True),
    KinSpec(75, 'LODEHORN', ('SWARM', 'METAL'), 'U', base=(50, 125, 88, 50, 62, 125), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (1, 'M_IRON_TAP'), (1, 'M_MAGNET_PULL'), (14, 'M_SILK_SNARE'), (20, 'M_STEEL_SHELL'), (26, 'M_FORGE_FLASH'), (32, 'M_PINCER'), (38, 'M_WINGDUST'), (44, 'M_SWARM_RUSH'), (50, 'M_GEAR_GRIND')],
            traits=('KEEN EYE', 'BRUISER'), field=('STRENGTH',),
            desc='Rhinoceros beetle with a lodestone horn.',
            concept='rhinoceros beetle with a lodestone horn', placeholder=True),
    KinSpec(76, 'HUMBEE', ('SWARM', 'BLOOM'), 'C', base=(41, 65, 40, 40, 48, 81), catch=190, xp=60, evo=('LEVEL', 26, 'COMBQUEEN'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (5, 'M_BASK'), (10, 'M_BRAMBLE_LASH'), (15, 'M_DROWSY_POLLEN'), (20, 'M_SILK_SNARE'), (25, 'M_THORN_WALL'), (30, 'M_SAP_SIP'), (35, 'M_LEAF_FLURRY'), (40, 'M_PINCER'), (45, 'M_WINGDUST')],
            traits=('KEEN EYE', 'SPORESKIN'), field=(),
            desc='Glow-bee.',
            concept='glow-bee', placeholder=True),
    KinSpec(77, 'COMBQUEEN', ('SWARM', 'BLOOM'), 'U', base=(64, 103, 64, 64, 77, 128), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_BASK'), (1, 'M_BRAMBLE_LASH'), (14, 'M_DROWSY_POLLEN'), (20, 'M_SILK_SNARE'), (26, 'M_THORN_WALL'), (32, 'M_SAP_SIP'), (38, 'M_LEAF_FLURRY'), (44, 'M_PINCER'), (50, 'M_WINGDUST')],
            traits=('KEEN EYE', 'SPORESKIN'), field=('LIGHT',),
            desc='Hive queen in a honeycomb gown.',
            concept='hive queen in a honeycomb gown', placeholder=True),
    KinSpec(78, 'WEBBIT', ('SWARM', 'VENOM'), 'C', base=(41, 73, 32, 40, 48, 81), catch=190, xp=60, evo=('LEVEL', 28, 'LACEWIDOW'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BARB'), (5, 'M_SILK_SNARE'), (10, 'M_SPORE_CLOUD'), (15, 'M_ACID_SPIT'), (20, 'M_PINCER'), (25, 'M_WINGDUST'), (30, 'M_FESTER'), (35, 'M_SWARM_RUSH'), (40, 'M_BOG_BOMB')],
            traits=('KEEN EYE', 'SELFMEND'), field=(),
            desc='Fuzzy spiderling.',
            concept='fuzzy spiderling', placeholder=True),
    KinSpec(79, 'LACEWIDOW', ('SWARM', 'VENOM'), 'U', base=(65, 115, 51, 64, 77, 128), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BARB'), (1, 'M_SILK_SNARE'), (1, 'M_SPORE_CLOUD'), (14, 'M_ACID_SPIT'), (20, 'M_PINCER'), (26, 'M_WINGDUST'), (32, 'M_FESTER'), (38, 'M_SWARM_RUSH'), (44, 'M_BOG_BOMB')],
            traits=('KEEN EYE', 'SELFMEND'), field=(),
            desc='Spider in a lace veil.',
            concept='spider in a lace veil', placeholder=True),
    KinSpec(80, 'SQUEAKLE', ('DUSK', 'GALE'), 'C', base=(33, 48, 32, 81, 32, 89), catch=190, xp=60, evo=('LEVEL', 26, 'NOCTAVE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (5, 'M_DRAFT'), (10, 'M_STARE_DOWN'), (15, 'M_UPDRAFT'), (20, 'M_FEATHER_CUT'), (25, 'M_SNAP'), (30, 'M_HAUNT'), (35, 'M_SHADE_CUT'), (40, 'M_CROSSWIND'), (45, 'M_GLOOM_ORB')],
            traits=('FOCUSED', 'MOMENTUM'), field=(),
            desc='Bat pup.',
            concept='bat pup', placeholder=True),
    KinSpec(81, 'NOCTAVE', ('DUSK', 'GALE'), 'U', base=(52, 77, 51, 128, 51, 141), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (1, 'M_DRAFT'), (1, 'M_STARE_DOWN'), (14, 'M_UPDRAFT'), (20, 'M_FEATHER_CUT'), (26, 'M_SNAP'), (32, 'M_HAUNT'), (38, 'M_SHADE_CUT'), (44, 'M_CROSSWIND'), (50, 'M_GLOOM_ORB')],
            traits=('FOCUSED', 'MOMENTUM'), field=('FLY',),
            desc='Sonar bat with tuning-fork ears.',
            concept='sonar bat with tuning-fork ears', placeholder=True),
    KinSpec(82, 'NOXKIT', ('DUSK',), 'C', base=(37, 37, 37, 93, 37, 74), catch=190, xp=60, evo=('BOND', 0, 'UMBRAKAT'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_STARE_DOWN'), (5, 'M_SNAP'), (10, 'M_HAUNT'), (15, 'M_SHADE_CUT'), (20, 'M_GLOOM_ORB'), (25, 'M_GNASH')],
            traits=('FOCUSED', 'SLIPPERY'), field=(),
            desc='Black kitten with glowing eyes.',
            concept='black kitten with glowing eyes', placeholder=True),
    KinSpec(83, 'UMBRAKAT', ('DUSK', 'BEAST'), 'U', base=(76, 62, 50, 125, 62, 125), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (1, 'M_DART'), (1, 'M_BRACE'), (14, 'M_CATNAP'), (20, 'M_POUT'), (26, 'M_STARE_DOWN'), (32, 'M_SNARL'), (38, 'M_GLINT'), (44, 'M_SNAP'), (50, 'M_HAUNT')],
            traits=('FOCUSED', 'MOMENTUM'), field=(),
            desc='Shadow panther.',
            concept='shadow panther', placeholder=True),
    KinSpec(84, 'CALCIPUP', ('HOLLOW',), 'C', base=(56, 37, 74, 37, 74, 37), catch=190, xp=60, evo=('LEVEL', 28, 'OSSIHOUND'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (5, 'M_LAST_RITES'), (10, 'M_SHROUD'), (15, 'M_GRAVE_CHILL'), (20, 'M_MARROW_SIP'), (25, 'M_OSSIFY'), (30, 'M_DEATH_KNELL'), (35, 'M_REQUIEM')],
            traits=('STUBBORN', 'SELFMEND'), field=(),
            desc='Skeletal puppy that rattles when happy.',
            concept='skeletal puppy that rattles when happy', placeholder=True),
    KinSpec(85, 'OSSIHOUND', ('HOLLOW', 'BEAST'), 'U', base=(101, 62, 100, 50, 112, 75), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (1, 'M_DART'), (1, 'M_SWIPE'), (14, 'M_BRACE'), (20, 'M_CATNAP'), (26, 'M_LAST_RITES'), (32, 'M_POUT'), (38, 'M_SHROUD'), (44, 'M_GRAVE_CHILL'), (50, 'M_SNARL')],
            traits=('STUBBORN', 'MOMENTUM'), field=('STRENGTH',),
            desc='Bone hound with ember eyes.',
            concept='bone hound with ember eyes', placeholder=True),
    KinSpec(86, 'MUDDLE', ('HOLLOW', 'TIDE'), 'C', base=(65, 32, 73, 40, 73, 32), catch=190, xp=60, evo=('LEVEL', 30, 'BOGSHAMBLE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (5, 'M_FIZZ'), (10, 'M_SLIPSTREAM'), (15, 'M_LAST_RITES'), (20, 'M_SHROUD'), (25, 'M_GRAVE_CHILL'), (30, 'M_MARROW_SIP'), (35, 'M_UNDERTOW'), (40, 'M_RIPTIDE'), (45, 'M_OSSIFY')],
            traits=('STUBBORN', 'SOAKER'), field=(),
            desc='Bog-mud zombie blob.',
            concept='bog-mud zombie blob', placeholder=True),
    KinSpec(87, 'BOGSHAMBLE', ('HOLLOW', 'BLOOM'), 'U', base=(91, 51, 115, 64, 128, 51), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_BONE_RATTLE'), (1, 'M_BASK'), (14, 'M_BRAMBLE_LASH'), (20, 'M_DROWSY_POLLEN'), (26, 'M_LAST_RITES'), (32, 'M_SHROUD'), (38, 'M_THORN_WALL'), (44, 'M_SAP_SIP'), (50, 'M_GRAVE_CHILL')],
            traits=('STUBBORN', 'SPORESKIN'), field=(),
            desc='Shambling peat zombie with mushrooms.',
            concept='shambling peat zombie with mushrooms', placeholder=True),
    KinSpec(88, 'DREGCROW', ('HOLLOW', 'GALE'), 'C', base=(48, 48, 65, 32, 65, 57), catch=190, xp=60, evo=('LEVEL', 27, 'CAWDAVER'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (5, 'M_BONE_RATTLE'), (10, 'M_DRAFT'), (15, 'M_LAST_RITES'), (20, 'M_SHROUD'), (25, 'M_UPDRAFT'), (30, 'M_GRAVE_CHILL'), (35, 'M_FEATHER_CUT'), (40, 'M_MARROW_SIP'), (45, 'M_CROSSWIND')],
            traits=('STUBBORN', 'MOMENTUM'), field=(),
            desc='Scraggly carrion crow.',
            concept='scraggly carrion crow', placeholder=True),
    KinSpec(89, 'CAWDAVER', ('HOLLOW', 'GALE'), 'U', base=(76, 77, 103, 51, 103, 90), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BEAK_JAB'), (1, 'M_BONE_RATTLE'), (1, 'M_DRAFT'), (14, 'M_LAST_RITES'), (20, 'M_SHROUD'), (26, 'M_UPDRAFT'), (32, 'M_GRAVE_CHILL'), (38, 'M_FEATHER_CUT'), (44, 'M_MARROW_SIP'), (50, 'M_CROSSWIND')],
            traits=('STUBBORN', 'MOMENTUM'), field=('FLY',),
            desc='Skeletal crow with a tattered cloak.',
            concept='skeletal crow with a tattered cloak', placeholder=True),
    KinSpec(90, 'CRANICRAB', ('TIDE', 'HOLLOW'), 'C', base=(73, 32, 65, 48, 65, 32), catch=190, xp=60, evo=('LEVEL', 29, 'CRYPTCLAW'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (5, 'M_FIZZ'), (10, 'M_SLIPSTREAM'), (15, 'M_LAST_RITES'), (20, 'M_SHROUD'), (25, 'M_GRAVE_CHILL'), (30, 'M_MARROW_SIP'), (35, 'M_UNDERTOW'), (40, 'M_RIPTIDE'), (45, 'M_OSSIFY')],
            traits=('SURGE', 'SELFMEND'), field=(),
            desc='Hermit crab living in a skull.',
            concept='hermit crab living in a skull', placeholder=True),
    KinSpec(91, 'CRYPTCLAW', ('TIDE', 'HOLLOW'), 'U', base=(115, 51, 103, 77, 103, 51), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (14, 'M_LAST_RITES'), (20, 'M_SHROUD'), (26, 'M_GRAVE_CHILL'), (32, 'M_MARROW_SIP'), (38, 'M_UNDERTOW'), (44, 'M_RIPTIDE'), (50, 'M_OSSIFY')],
            traits=('SURGE', 'SELFMEND'), field=(),
            desc='Hermit crab in a crypt urn.',
            concept='hermit crab in a crypt urn', placeholder=True),
    KinSpec(92, 'PARASOLE', ('RELIC', 'GALE'), 'C', base=(31, 46, 77, 61, 46, 54), catch=190, xp=60, evo=('LEVEL', 25, 'STORMBRELA'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (5, 'M_BEAK_JAB'), (10, 'M_CLATTER'), (15, 'M_DRAFT'), (20, 'M_TARNISH'), (25, 'M_UPDRAFT'), (30, 'M_FEATHER_CUT'), (35, 'M_POLTERGUST'), (40, 'M_GILDED_GLEAM'), (45, 'M_CROSSWIND')],
            traits=('HOARDER', 'MOMENTUM'), field=(),
            desc='One-eyed hopping umbrella (kasa-obake).',
            concept='one-eyed hopping umbrella (kasa-obake)', placeholder=True),
    KinSpec(93, 'STORMBRELA', ('RELIC', 'GALE'), 'U', base=(49, 73, 122, 98, 73, 85), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_BEAK_JAB'), (1, 'M_CLATTER'), (14, 'M_DRAFT'), (20, 'M_TARNISH'), (26, 'M_UPDRAFT'), (32, 'M_FEATHER_CUT'), (38, 'M_POLTERGUST'), (44, 'M_GILDED_GLEAM'), (50, 'M_CROSSWIND')],
            traits=('HOARDER', 'MOMENTUM'), field=('FLY',),
            desc='Storm umbrella, spokes crackling.',
            concept='storm umbrella, spokes crackling', placeholder=True),
    KinSpec(94, 'KETTLEKIN', ('RELIC', 'TIDE'), 'C', base=(45, 31, 85, 69, 54, 31), catch=190, xp=60, evo=('LEVEL', 26, 'TANUKETTLE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (5, 'M_CLATTER'), (10, 'M_FIZZ'), (15, 'M_SLIPSTREAM'), (20, 'M_TARNISH'), (25, 'M_POLTERGUST'), (30, 'M_UNDERTOW'), (35, 'M_GILDED_GLEAM'), (40, 'M_RIPTIDE'), (45, 'M_CHEST_CHOMP')],
            traits=('HOARDER', 'SOAKER'), field=(),
            desc='Teapot with a tail and paws.',
            concept='teapot with a tail and paws', placeholder=True),
    KinSpec(95, 'TANUKETTLE', ('RELIC', 'BEAST'), 'U', base=(72, 60, 119, 95, 83, 71), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_CLATTER'), (1, 'M_DART'), (14, 'M_SWIPE'), (20, 'M_BRACE'), (26, 'M_CATNAP'), (32, 'M_POUT'), (38, 'M_TARNISH'), (44, 'M_SNARL'), (50, 'M_GLINT')],
            traits=('HOARDER', 'MOMENTUM'), field=('SURF',),
            desc='Tanuki-teapot (bunbuku chagama).',
            concept='tanuki-teapot (bunbuku chagama)', placeholder=True),
    KinSpec(96, 'STRAWSPECT', ('RELIC', 'BLOOM'), 'C', base=(55, 43, 119, 98, 87, 43), catch=120, xp=160, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (4, 'M_BURR_VOLLEY'), (9, 'M_CLATTER'), (14, 'M_BASK'), (19, 'M_BRAMBLE_LASH'), (24, 'M_DROWSY_POLLEN'), (29, 'M_TARNISH'), (34, 'M_THORN_WALL'), (39, 'M_SAP_SIP'), (44, 'M_LEAF_FLURRY')],
            traits=('HOARDER', 'SPORESKIN'), field=(),
            desc='Living scarecrow (a great farm worker).',
            concept='living scarecrow (a great farm worker)', placeholder=True),
    KinSpec(97, 'RIVETILLO', ('METAL', 'STONE'), 'C', base=(37, 75, 98, 30, 45, 30), catch=190, xp=60, evo=('LEVEL', 30, 'FORTADILLO'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (5, 'M_IRON_TAP'), (10, 'M_GRIT_KICK'), (15, 'M_MAGNET_PULL'), (20, 'M_STEEL_SHELL'), (25, 'M_STONESKIN'), (30, 'M_PEBBLE_PELT'), (35, 'M_MUD_PIE'), (40, 'M_FORGE_FLASH'), (45, 'M_SANDBLAST')],
            traits=('BEDROCK', 'STUBBORN'), field=(),
            desc='Armadillo with riveted plates.',
            concept='armadillo with riveted plates', placeholder=True),
    KinSpec(98, 'FORTADILLO', ('METAL', 'STONE'), 'U', base=(59, 119, 155, 48, 71, 48), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (1, 'M_IRON_TAP'), (1, 'M_GRIT_KICK'), (14, 'M_MAGNET_PULL'), (20, 'M_STEEL_SHELL'), (26, 'M_STONESKIN'), (32, 'M_PEBBLE_PELT'), (38, 'M_MUD_PIE'), (44, 'M_FORGE_FLASH'), (50, 'M_SANDBLAST')],
            traits=('BEDROCK', 'STUBBORN'), field=('STRENGTH',),
            desc='Fortress armadillo.',
            concept='fortress armadillo', placeholder=True),
    KinSpec(99, 'SALAMBER', ('BLAZE',), 'C', base=(37, 56, 37, 74, 37, 74), catch=190, xp=60, evo=('LEVEL', 30, 'FOUNDRAKE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_CINDER_FLICK'), (5, 'M_LAST_EMBER'), (10, 'M_LANTERN_LURE'), (15, 'M_SEAR_BITE'), (20, 'M_EMBER_STORM'), (25, 'M_KILN_BREATH'), (30, 'M_SUNFLARE')],
            traits=('SURGE', 'EMBERSKIN'), field=('LIGHT',),
            desc='Ember salamander.',
            concept='ember salamander', placeholder=True),
    KinSpec(100, 'FOUNDRAKE', ('BLAZE', 'METAL'), 'U', base=(50, 100, 88, 100, 62, 100), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (1, 'M_CINDER_FLICK'), (1, 'M_IRON_TAP'), (14, 'M_LAST_EMBER'), (20, 'M_LANTERN_LURE'), (26, 'M_MAGNET_PULL'), (32, 'M_STEEL_SHELL'), (38, 'M_FORGE_FLASH'), (44, 'M_SEAR_BITE'), (50, 'M_EMBER_STORM')],
            traits=('SURGE', 'BRUISER'), field=('LIGHT', 'STRENGTH'),
            desc='Foundry drake with ingot scales.',
            concept='foundry drake with ingot scales', placeholder=True),
]
