"""Kin 32-66. Owner: KIN-A (new common/uncommon kin 32-66).

PLACEHOLDER data and art: stats, learnsets, traits and descriptions
were generated from docs/EXPANSION.md; replace every entry with the real
design (keep id, name, types, rarity and growth), give it a model, and
set placeholder=False (then its base stat total is checked by tier).
"""

from kin import KinSpec

SPECIES = [
    KinSpec(32, 'PRICKLET', ('BEAST',), 'C', base=(71, 52, 35, 35, 52, 70), catch=190, xp=60, evo=('LEVEL', 20, 'QUILLDRUM'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (5, 'M_DART'), (10, 'M_BRACE'), (15, 'M_CATNAP'), (20, 'M_POUT'), (25, 'M_SNARL'), (30, 'M_GLINT'), (35, 'M_BELLY_FLOP'), (40, 'M_RECKLESS_RUSH'), (45, 'M_PRIMAL_ROAR')],
            traits=('KEEN EYE', 'MOMENTUM'), field=(),
            desc='Hedgehog kit that rolls into a burr.',
            concept='hedgehog kit that rolls into a burr', placeholder=True),
    KinSpec(33, 'QUILLDRUM', ('BEAST', 'BRAWL'), 'U', base=(119, 107, 48, 48, 71, 107), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (1, 'M_ONE_TWO'), (1, 'M_DART'), (14, 'M_SWIPE'), (20, 'M_BRACE'), (26, 'M_CATNAP'), (32, 'M_POUT'), (38, 'M_WAR_CRY'), (44, 'M_HAMMER_FIST'), (50, 'M_SNARL')],
            traits=('KEEN EYE', 'STUBBORN'), field=('STRENGTH',),
            desc='Hedgehog that drums its quills as a warning.',
            concept='hedgehog that drums its quills as a warning', placeholder=True),
    KinSpec(34, 'SNUFFLET', ('BEAST',), 'C', base=(71, 52, 35, 35, 52, 70), catch=190, xp=60, evo=('LEVEL', 22, 'TRUFFLOAR'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (5, 'M_DART'), (10, 'M_BRACE'), (15, 'M_CATNAP'), (20, 'M_POUT'), (25, 'M_SNARL'), (30, 'M_GLINT'), (35, 'M_BELLY_FLOP'), (40, 'M_RECKLESS_RUSH'), (45, 'M_PRIMAL_ROAR')],
            traits=('KEEN EYE', 'MOMENTUM'), field=(),
            desc='Truffle piglet with a leaf on its snout.',
            concept='truffle piglet with a leaf on its snout', placeholder=True),
    KinSpec(35, 'TRUFFLOAR', ('BEAST', 'BLOOM'), 'U', base=(109, 73, 61, 61, 98, 98), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_DART'), (1, 'M_SWIPE'), (14, 'M_BASK'), (20, 'M_BRACE'), (26, 'M_BRAMBLE_LASH'), (32, 'M_CATNAP'), (38, 'M_DROWSY_POLLEN'), (44, 'M_POUT'), (50, 'M_THORN_WALL')],
            traits=('KEEN EYE', 'SPORESKIN'), field=('STRENGTH',),
            desc='Boar with a mossy garden on its back; digs up buried items.',
            concept='boar with a mossy garden on its back; digs up buried items', placeholder=True),
    KinSpec(36, 'RACCOIN', ('BEAST', 'DUSK'), 'C', base=(61, 46, 31, 54, 46, 77), catch=190, xp=60, evo=('LEVEL', 24, 'BANDIRACC'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (5, 'M_DART'), (10, 'M_BRACE'), (15, 'M_CATNAP'), (20, 'M_POUT'), (25, 'M_STARE_DOWN'), (30, 'M_SNARL'), (35, 'M_GLINT'), (40, 'M_SNAP'), (45, 'M_HAUNT')],
            traits=('KEEN EYE', 'SLIPPERY'), field=(),
            desc='Masked raccoon hoarding shiny coins.',
            concept='masked raccoon hoarding shiny coins', placeholder=True),
    KinSpec(37, 'BANDIRACC', ('BEAST', 'DUSK'), 'U', base=(98, 73, 49, 85, 73, 122), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (1, 'M_DART'), (1, 'M_BRACE'), (14, 'M_CATNAP'), (20, 'M_POUT'), (26, 'M_STARE_DOWN'), (32, 'M_SNARL'), (38, 'M_GLINT'), (44, 'M_SNAP'), (50, 'M_HAUNT')],
            traits=('KEEN EYE', 'SLIPPERY'), field=(),
            desc='Bandit raccoon with a bandana and a coin sack.',
            concept='bandit raccoon with a bandana and a coin sack', placeholder=True),
    KinSpec(38, 'PEBBOTTER', ('TIDE',), 'C', base=(73, 37, 56, 56, 56, 37), catch=190, xp=60, evo=('LEVEL', 24, 'TORRENTTER'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (5, 'M_SLIPSTREAM'), (10, 'M_UNDERTOW'), (15, 'M_RIPTIDE'), (20, 'M_SWELL'), (25, 'M_GEYSER')],
            traits=('SURGE', 'SOAKER'), field=(),
            desc='Otter juggling river stones.',
            concept='otter juggling river stones', placeholder=True),
    KinSpec(39, 'TORRENTTER', ('TIDE', 'BRAWL'), 'U', base=(125, 88, 75, 75, 75, 62), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (1, 'M_ONE_TWO'), (1, 'M_FIZZ'), (14, 'M_SLIPSTREAM'), (20, 'M_WAR_CRY'), (26, 'M_HAMMER_FIST'), (32, 'M_COUNTERJAB'), (38, 'M_UNDERTOW'), (44, 'M_RIPTIDE'), (50, 'M_SWELL')],
            traits=('SURGE', 'STUBBORN'), field=('SURF', 'STRENGTH'),
            desc='River otter with a stone club.',
            concept='river otter with a stone club', placeholder=True),
    KinSpec(40, 'JELLUME', ('TIDE', 'SPARK'), 'C', base=(65, 32, 48, 65, 48, 57), catch=190, xp=60, evo=('LEVEL', 26, 'MEDUSHOCK'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (5, 'M_SLIPSTREAM'), (10, 'M_STATIC_POP'), (15, 'M_TINGLE'), (20, 'M_LIVE_WIRE'), (25, 'M_UNDERTOW'), (30, 'M_ARC_FLASH'), (35, 'M_RIPTIDE'), (40, 'M_FORKED_BOLT'), (45, 'M_SWELL')],
            traits=('SURGE', 'CONDUCTOR'), field=('LIGHT',),
            desc='Jellyfish whose bell glows like a lamp.',
            concept='jellyfish whose bell glows like a lamp', placeholder=True),
    KinSpec(41, 'MEDUSHOCK', ('TIDE', 'SPARK'), 'U', base=(102, 51, 77, 103, 77, 90), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_STATIC_POP'), (14, 'M_TINGLE'), (20, 'M_LIVE_WIRE'), (26, 'M_UNDERTOW'), (32, 'M_ARC_FLASH'), (38, 'M_RIPTIDE'), (44, 'M_FORKED_BOLT'), (50, 'M_SWELL')],
            traits=('SURGE', 'CONDUCTOR'), field=('LIGHT', 'SURF'),
            desc='Tall jellyfish whose tendrils arc.',
            concept='tall jellyfish whose tendrils arc', placeholder=True),
    KinSpec(42, 'LURELING', ('TIDE', 'DUSK'), 'U', base=(66, 32, 48, 73, 48, 48), catch=190, xp=60, evo=('LEVEL', 30, 'ABYSSLURE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (5, 'M_SLIPSTREAM'), (10, 'M_STARE_DOWN'), (15, 'M_SNAP'), (20, 'M_UNDERTOW'), (25, 'M_HAUNT'), (30, 'M_SHADE_CUT'), (35, 'M_RIPTIDE'), (40, 'M_GLOOM_ORB'), (45, 'M_GNASH')],
            traits=('SURGE', 'SLIPPERY'), field=('LIGHT',),
            desc='Anglerfish fry; its lure is a tiny kernel.',
            concept='anglerfish fry; its lure is a tiny kernel', placeholder=True),
    KinSpec(43, 'ABYSSLURE', ('TIDE', 'DUSK'), 'U', base=(103, 51, 77, 115, 77, 77), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_STARE_DOWN'), (14, 'M_SNAP'), (20, 'M_UNDERTOW'), (26, 'M_HAUNT'), (32, 'M_SHADE_CUT'), (38, 'M_RIPTIDE'), (44, 'M_GLOOM_ORB'), (50, 'M_GNASH')],
            traits=('SURGE', 'SLIPPERY'), field=('LIGHT', 'SURF'),
            desc='Deep anglerfish, lure like a lantern.',
            concept='deep anglerfish, lure like a lantern', placeholder=True),
    KinSpec(44, 'RADISHOO', ('BLOOM',), 'C', base=(55, 37, 56, 56, 74, 37), catch=190, xp=60, evo=('LEVEL', 22, 'MANDRAGOR'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (5, 'M_BASK'), (10, 'M_BRAMBLE_LASH'), (15, 'M_DROWSY_POLLEN'), (20, 'M_THORN_WALL'), (25, 'M_SAP_SIP'), (30, 'M_LEAF_FLURRY'), (35, 'M_REED_BLADE'), (40, 'M_SUNSHAFT')],
            traits=('BASKER', 'SPORESKIN'), field=(),
            desc='Radish sprite with a leafy tuft.',
            concept='radish sprite with a leafy tuft', placeholder=True),
    KinSpec(45, 'MANDRAGOR', ('BLOOM', 'DREAM'), 'U', base=(78, 51, 77, 115, 128, 51), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_BASK'), (1, 'M_BRAMBLE_LASH'), (14, 'M_DROWSY_POLLEN'), (20, 'M_LULLABY'), (26, 'M_STILL_POND'), (32, 'M_THORN_WALL'), (38, 'M_DAYDREAM'), (44, 'M_SAP_SIP'), (50, 'M_LEAF_FLURRY')],
            traits=('BASKER', 'WAKEFUL'), field=('TELEPORT',),
            desc='Mandrake whose scream is a lullaby.',
            concept='mandrake whose scream is a lullaby', placeholder=True),
    KinSpec(46, 'PUMPKLING', ('BLOOM',), 'C', base=(55, 37, 56, 56, 74, 37), catch=190, xp=60, evo=('LEVEL', 28, 'JACKOGRIM'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (5, 'M_BASK'), (10, 'M_BRAMBLE_LASH'), (15, 'M_DROWSY_POLLEN'), (20, 'M_THORN_WALL'), (25, 'M_SAP_SIP'), (30, 'M_LEAF_FLURRY'), (35, 'M_REED_BLADE'), (40, 'M_SUNSHAFT')],
            traits=('BASKER', 'SPORESKIN'), field=(),
            desc='Pumpkin sprout with a carved grin.',
            concept='pumpkin sprout with a carved grin', placeholder=True),
    KinSpec(47, 'JACKOGRIM', ('BLOOM', 'HOLLOW'), 'U', base=(90, 51, 103, 77, 128, 51), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_BONE_RATTLE'), (1, 'M_BASK'), (14, 'M_BRAMBLE_LASH'), (20, 'M_DROWSY_POLLEN'), (26, 'M_LAST_RITES'), (32, 'M_SHROUD'), (38, 'M_THORN_WALL'), (44, 'M_SAP_SIP'), (50, 'M_GRAVE_CHILL')],
            traits=('BASKER', 'SELFMEND'), field=('LIGHT',),
            desc="Vine-bodied jack-o'-lantern with a lantern head.",
            concept="vine-bodied jack-o'-lantern with a lantern head", placeholder=True),
    KinSpec(48, 'SHROOMLET', ('BLOOM', 'VENOM'), 'C', base=(57, 40, 48, 57, 81, 32), catch=190, xp=60, evo=('LEVEL', 30, 'MYCOLOSSUS'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (5, 'M_BARB'), (10, 'M_BASK'), (15, 'M_BRAMBLE_LASH'), (20, 'M_DROWSY_POLLEN'), (25, 'M_SPORE_CLOUD'), (30, 'M_THORN_WALL'), (35, 'M_SAP_SIP'), (40, 'M_LEAF_FLURRY'), (45, 'M_ACID_SPIT')],
            traits=('BASKER', 'SELFMEND'), field=(),
            desc='Mushroom-cap tot that puffs spores.',
            concept='mushroom-cap tot that puffs spores', placeholder=True),
    KinSpec(49, 'MYCOLOSSUS', ('BLOOM', 'VENOM'), 'U', base=(90, 64, 77, 90, 128, 51), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BURR_VOLLEY'), (1, 'M_BARB'), (1, 'M_BASK'), (14, 'M_BRAMBLE_LASH'), (20, 'M_DROWSY_POLLEN'), (26, 'M_SPORE_CLOUD'), (32, 'M_THORN_WALL'), (38, 'M_SAP_SIP'), (44, 'M_LEAF_FLURRY'), (50, 'M_ACID_SPIT')],
            traits=('BASKER', 'SELFMEND'), field=('STRENGTH',),
            desc='Walking giant fungus.',
            concept='walking giant fungus', placeholder=True),
    KinSpec(50, 'BLINKET', ('SWARM', 'SPARK'), 'C', base=(33, 65, 32, 48, 32, 105), catch=190, xp=60, evo=('LEVEL', 22, 'BEACONFLY'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_STATIC_POP'), (5, 'M_SILK_SNARE'), (10, 'M_TINGLE'), (15, 'M_PINCER'), (20, 'M_WINGDUST'), (25, 'M_LIVE_WIRE'), (30, 'M_ARC_FLASH'), (35, 'M_SWARM_RUSH'), (40, 'M_FORKED_BOLT'), (45, 'M_OVERCHARGE')],
            traits=('KEEN EYE', 'CONDUCTOR'), field=('LIGHT',),
            desc='Firefly with a blinking tail.',
            concept='firefly with a blinking tail', placeholder=True),
    KinSpec(51, 'BEACONFLY', ('SWARM', 'SPARK'), 'U', base=(51, 103, 51, 77, 51, 167), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_STATIC_POP'), (1, 'M_SILK_SNARE'), (1, 'M_TINGLE'), (14, 'M_PINCER'), (20, 'M_WINGDUST'), (26, 'M_LIVE_WIRE'), (32, 'M_ARC_FLASH'), (38, 'M_SWARM_RUSH'), (44, 'M_FORKED_BOLT'), (50, 'M_OVERCHARGE')],
            traits=('KEEN EYE', 'CONDUCTOR'), field=('LIGHT',),
            desc='Big firefly with a lantern abdomen.',
            concept='big firefly with a lantern abdomen', placeholder=True),
    KinSpec(52, 'STATICKO', ('SPARK',), 'C', base=(37, 37, 37, 74, 37, 93), catch=190, xp=60, evo=('LEVEL', 25, 'FULGECKO'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_STATIC_POP'), (5, 'M_TINGLE'), (10, 'M_LIVE_WIRE'), (15, 'M_ARC_FLASH'), (20, 'M_FORKED_BOLT'), (25, 'M_OVERCHARGE')],
            traits=('STATIC FUR', 'CONDUCTOR'), field=(),
            desc='Gecko that sticks to walls with static.',
            concept='gecko that sticks to walls with static', placeholder=True),
    KinSpec(53, 'FULGECKO', ('SPARK', 'BEAST'), 'U', base=(76, 62, 50, 100, 62, 150), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (1, 'M_DART'), (1, 'M_STATIC_POP'), (14, 'M_BRACE'), (20, 'M_CATNAP'), (26, 'M_POUT'), (32, 'M_TINGLE'), (38, 'M_SNARL'), (44, 'M_GLINT'), (50, 'M_LIVE_WIRE')],
            traits=('STATIC FUR', 'MOMENTUM'), field=('LIGHT',),
            desc='Frilled lightning lizard.',
            concept='frilled lightning lizard', placeholder=True),
    KinSpec(54, 'FLURRABBIT', ('FROST',), 'C', base=(36, 37, 56, 74, 56, 56), catch=190, xp=60, evo=('ITEM', 'ASTRAL_SHARD', 'MOONHARE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (5, 'M_FLURRY'), (10, 'M_RIME_SHOT'), (15, 'M_SNOWDRIFT'), (20, 'M_WINTER_RAY')],
            traits=('THICK FUR', 'SURGE'), field=(),
            desc='Snow hare.',
            concept='snow hare', placeholder=True),
    KinSpec(55, 'MOONHARE', ('FROST', 'ASTRAL'), 'U', base=(77, 51, 77, 141, 77, 77), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (1, 'M_FLURRY'), (1, 'M_RIME_SHOT'), (14, 'M_TWINKLE'), (20, 'M_NEBULA_VEIL'), (26, 'M_SNOWDRIFT'), (32, 'M_STARDUST'), (38, 'M_MOONBEAM'), (44, 'M_COMET_DASH'), (50, 'M_MUON_RAIN')],
            traits=('THICK FUR', 'QUICK STUDY'), field=('TELEPORT',),
            desc='Moon rabbit with a mochi mallet.',
            concept='moon rabbit with a mochi mallet', placeholder=True),
    KinSpec(56, 'TUXFLAKE', ('FROST', 'TIDE'), 'C', base=(48, 32, 57, 73, 57, 48), catch=190, xp=60, evo=('LEVEL', 30, 'EMPERICE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (5, 'M_FIZZ'), (10, 'M_FLURRY'), (15, 'M_RIME_SHOT'), (20, 'M_SLIPSTREAM'), (25, 'M_SNOWDRIFT'), (30, 'M_UNDERTOW'), (35, 'M_RIPTIDE'), (40, 'M_SWELL'), (45, 'M_WINTER_RAY')],
            traits=('THICK FUR', 'SOAKER'), field=(),
            desc='Penguin chick in a snow puff.',
            concept='penguin chick in a snow puff', placeholder=True),
    KinSpec(57, 'EMPERICE', ('FROST', 'TIDE'), 'U', base=(77, 51, 90, 115, 90, 77), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (1, 'M_FIZZ'), (1, 'M_FLURRY'), (14, 'M_RIME_SHOT'), (20, 'M_SLIPSTREAM'), (26, 'M_SNOWDRIFT'), (32, 'M_UNDERTOW'), (38, 'M_RIPTIDE'), (44, 'M_SWELL'), (50, 'M_WINTER_RAY')],
            traits=('THICK FUR', 'SOAKER'), field=('SURF',),
            desc='Emperor penguin with an ice crown.',
            concept='emperor penguin with an ice crown', placeholder=True),
    KinSpec(58, 'YAKLING', ('FROST', 'BEAST'), 'C', base=(48, 39, 47, 63, 55, 63), catch=190, xp=60, evo=('LEVEL', 32, 'GLACIYAK'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (5, 'M_DART'), (10, 'M_FLURRY'), (15, 'M_RIME_SHOT'), (20, 'M_SWIPE'), (25, 'M_BRACE'), (30, 'M_CATNAP'), (35, 'M_POUT'), (40, 'M_SNOWDRIFT'), (45, 'M_SNARL')],
            traits=('THICK FUR', 'MOMENTUM'), field=(),
            desc='Shaggy yak calf.',
            concept='shaggy yak calf', placeholder=True),
    KinSpec(59, 'GLACIYAK', ('FROST', 'BEAST'), 'U', base=(75, 62, 75, 100, 88, 100), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (1, 'M_DART'), (1, 'M_FLURRY'), (14, 'M_RIME_SHOT'), (20, 'M_SWIPE'), (26, 'M_BRACE'), (32, 'M_CATNAP'), (38, 'M_POUT'), (44, 'M_SNOWDRIFT'), (50, 'M_SNARL')],
            traits=('THICK FUR', 'MOMENTUM'), field=('STRENGTH',),
            desc='Glacier yak with icicle horns.',
            concept='glacier yak with icicle horns', placeholder=True),
    KinSpec(60, 'RAMBLET', ('BRAWL',), 'C', base=(70, 88, 35, 35, 35, 52), catch=190, xp=60, evo=('LEVEL', 26, 'CRAGHORN'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (5, 'M_ONE_TWO'), (10, 'M_WAR_CRY'), (15, 'M_HAMMER_FIST'), (20, 'M_COUNTERJAB'), (25, 'M_HAYMAKER')],
            traits=('BRUISER', 'STUBBORN'), field=(),
            desc='Lamb that headbutts everything.',
            concept='lamb that headbutts everything', placeholder=True),
    KinSpec(61, 'CRAGHORN', ('BRAWL', 'STONE'), 'U', base=(107, 143, 83, 48, 48, 71), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (1, 'M_ONE_TWO'), (1, 'M_GRIT_KICK'), (14, 'M_STONESKIN'), (20, 'M_WAR_CRY'), (26, 'M_HAMMER_FIST'), (32, 'M_PEBBLE_PELT'), (38, 'M_MUD_PIE'), (44, 'M_COUNTERJAB'), (50, 'M_SANDBLAST')],
            traits=('BRUISER', 'STUBBORN'), field=('STRENGTH',),
            desc='Mountain ram with rock-hard horns.',
            concept='mountain ram with rock-hard horns', placeholder=True),
    KinSpec(62, 'STINGLET', ('VENOM',), 'C', base=(55, 56, 37, 56, 74, 37), catch=190, xp=60, evo=('LEVEL', 27, 'SCORCHION'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BARB'), (5, 'M_SPORE_CLOUD'), (10, 'M_ACID_SPIT'), (15, 'M_FESTER'), (20, 'M_BOG_BOMB')],
            traits=('SPORESKIN', 'SELFMEND'), field=(),
            desc='Scorpling.',
            concept='scorpling', placeholder=True),
    KinSpec(63, 'SCORCHION', ('VENOM', 'BLAZE'), 'U', base=(76, 90, 51, 103, 103, 77), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BARB'), (1, 'M_CINDER_FLICK'), (1, 'M_LAST_EMBER'), (14, 'M_LANTERN_LURE'), (20, 'M_SPORE_CLOUD'), (26, 'M_ACID_SPIT'), (32, 'M_FESTER'), (38, 'M_SEAR_BITE'), (44, 'M_EMBER_STORM'), (50, 'M_BOG_BOMB')],
            traits=('SPORESKIN', 'EMBERSKIN'), field=('LIGHT',),
            desc='Ember-tailed scorpion.',
            concept='ember-tailed scorpion', placeholder=True),
    KinSpec(64, 'DIGGET', ('STONE',), 'C', base=(52, 70, 88, 35, 35, 35), catch=190, xp=60, evo=('ITEM', 'HOLLOW_SHARD', 'SEXTONE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_GRIT_KICK'), (5, 'M_STONESKIN'), (10, 'M_PEBBLE_PELT'), (15, 'M_MUD_PIE'), (20, 'M_SANDBLAST'), (25, 'M_ROCKFALL'), (30, 'M_FAULTLINE')],
            traits=('BEDROCK', 'STUBBORN'), field=(),
            desc='Mole with a tiny lantern.',
            concept='mole with a tiny lantern', placeholder=True),
    KinSpec(65, 'SEXTONE', ('STONE', 'HOLLOW'), 'U', base=(85, 98, 146, 49, 73, 49), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (1, 'M_GRIT_KICK'), (1, 'M_LAST_RITES'), (14, 'M_SHROUD'), (20, 'M_STONESKIN'), (26, 'M_PEBBLE_PELT'), (32, 'M_GRAVE_CHILL'), (38, 'M_MUD_PIE'), (44, 'M_MARROW_SIP'), (50, 'M_SANDBLAST')],
            traits=('BEDROCK', 'SELFMEND'), field=('STRENGTH',),
            desc='Gravedigger mole with a spade and a lantern.',
            concept='gravedigger mole with a spade and a lantern', placeholder=True),
    KinSpec(66, 'QUARTZLING', ('STONE', 'SWARM'), 'U', base=(45, 77, 77, 31, 31, 54), catch=190, xp=60, evo=('LEVEL', 30, 'QUARTZPEDE'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_GRIT_KICK'), (5, 'M_SILK_SNARE'), (10, 'M_STONESKIN'), (15, 'M_PEBBLE_PELT'), (20, 'M_MUD_PIE'), (25, 'M_PINCER'), (30, 'M_WINGDUST'), (35, 'M_SANDBLAST'), (40, 'M_ROCKFALL'), (45, 'M_SWARM_RUSH')],
            traits=('BEDROCK', 'MOMENTUM'), field=(),
            desc='Crystal grub.',
            concept='crystal grub', placeholder=True),
]
