"""Kin 32-66. Owner: KIN-A (new common/uncommon kin 32-66).

Data for each species; the art (one model function per species) lives in
tools/kin/art_normal_a.py. Ids, names, types, rarity and growth follow the
roster in docs/EXPANSION.md 4.2.
"""

from kin import KinSpec
from kin import art_normal_a as A


def _m(name):
    """Model function for a species, or None while it is still unpainted."""
    return getattr(A, name, None)


SPECIES = [
    KinSpec(32, 'PRICKLET', ('BEAST',), 'C', base=(48, 52, 64, 32, 44, 60), catch=190, xp=58,
            evo=('LEVEL', 20, 'QUILLDRUM'),
            category='QUILL KIT', height=3, weight=18,
            learnset=[(1, 'M_BONK'), (1, 'M_BRACE'), (5, 'M_POUT'), (9, 'M_DART'), (13, 'M_BURR_VOLLEY'),
                      (17, 'M_SNARL'), (21, 'M_BELLY_FLOP'), (25, 'M_CATNAP')],
            traits=('STUBBORN', 'THICK FUR'), field=(),
            desc='When startled it curls into a spiky burr and rolls off downhill. Meadow seeds hitch rides '
                 'in its quills, so flowers spring up wherever it naps.',
            concept='hedgehog kit that rolls into a burr', model=_m('pricklet')),
    KinSpec(33, 'QUILLDRUM', ('BEAST', 'BRAWL'), 'U', base=(88, 110, 96, 46, 72, 88), catch=45, xp=172,
            evo=None,
            category='WAR DRUM', height=12, weight=380,
            learnset=[(1, 'M_BONK'), (1, 'M_BRACE'), (1, 'M_POUT'), (1, 'M_DART'), (13, 'M_BURR_VOLLEY'),
                      (17, 'M_SNARL'), (20, 'M_ONE_TWO'), (24, 'M_WAR_CRY'), (29, 'M_PUMMEL'),
                      (34, 'M_COUNTERJAB'), (40, 'M_RECKLESS_RUSH'), (46, 'M_HAYMAKER')],
            traits=('GLOWER', 'STUBBORN'), field=('STRENGTH',),
            desc='Before a bout it rattles its hollow tail quills like a war drum. It is a fair warning: '
                 'the beat strains its bones, pumping its kernel for the first punch.',
            concept='hedgehog that drums its quills as a warning', model=_m('quilldrum')),
    KinSpec(34, 'SNUFFLET', ('BEAST',), 'C', base=(64, 55, 52, 34, 46, 45), catch=190, xp=60,
            evo=('LEVEL', 22, 'TRUFFLOAR'),
            category='TRUFFLER', height=4, weight=90,
            learnset=[(1, 'M_POUT'), (1, 'M_BONK'), (5, 'M_GRIT_KICK'), (9, 'M_MUD_PIE'), (13, 'M_SWIPE'),
                      (17, 'M_BRACE'), (21, 'M_BELLY_FLOP'), (25, 'M_SAP_SIP')],
            traits=('HOARDER', 'STUBBORN'), field=(),
            desc='It can smell a truffle through a yard of soil. The leaf on its snout is a seedling '
                 'that took root there, and it droops whenever the piglet is sad.',
            concept='truffle piglet with a leaf on its snout', model=_m('snufflet')),
    KinSpec(35, 'TRUFFLOAR', ('BEAST', 'BLOOM'), 'U', base=(95, 102, 88, 60, 80, 65), catch=45, xp=175,
            evo=None,
            category='MOSS BOAR', height=12, weight=1500,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (1, 'M_GRIT_KICK'), (1, 'M_MUD_PIE'), (13, 'M_SWIPE'),
                      (17, 'M_BRACE'), (22, 'M_BRAMBLE_LASH'), (26, 'M_BELLY_FLOP'), (31, 'M_THORN_WALL'),
                      (36, 'M_SAP_SIP'), (42, 'M_RECKLESS_RUSH'), (48, 'M_SUNSHAFT')],
            traits=('HOARDER', 'BASKER'), field=('STRENGTH',),
            desc='A whole garden grows on its back, warmed by its kernel. Farmers follow it around: '
                 'wherever it roots, it turns up lost coins, old tools and fat truffles.',
            concept='boar with a mossy garden on its back; digs up buried items', model=_m('truffloar')),
    KinSpec(36, 'RACCOIN', ('BEAST', 'DUSK'), 'C', base=(48, 50, 40, 44, 40, 72), catch=190, xp=60,
            evo=('LEVEL', 24, 'BANDIRACC'),
            category='MASKED KIT', height=4, weight=55,
            learnset=[(1, 'M_SWIPE'), (1, 'M_POUT'), (5, 'M_SNAP'), (9, 'M_DART'), (13, 'M_GLINT'),
                      (17, 'M_STARE_DOWN'), (21, 'M_TRINKET_TOSS'), (25, 'M_HAUNT')],
            traits=('HOARDER', 'SLIPPERY'), field=(),
            desc='It washes every coin it finds in the creek and polishes it to a shine. Its dusk kernel '
                 'drinks even the faint glint of its hoard by starlight.',
            concept='masked raccoon hoarding shiny coins', model=_m('raccoin')),
    KinSpec(37, 'BANDIRACC', ('BEAST', 'DUSK'), 'U', base=(78, 96, 68, 82, 66, 115), catch=45, xp=170,
            evo=None,
            category='BANDIT', height=11, weight=320,
            learnset=[(1, 'M_SWIPE'), (1, 'M_POUT'), (1, 'M_SNAP'), (1, 'M_DART'), (13, 'M_GLINT'),
                      (17, 'M_STARE_DOWN'), (21, 'M_TRINKET_TOSS'), (24, 'M_SHADE_CUT'), (28, 'M_TARNISH'),
                      (33, 'M_GNASH'), (39, 'M_GILDED_GLEAM'), (46, 'M_GLOOM_ORB')],
            traits=('HOARDER', 'KEEN EYE'), field=(),
            desc='A dashing night thief that never keeps its loot for long. It leaves one bright coin on '
                 'the doorstep of every house it robs, and some towns call it rent.',
            concept='bandit raccoon with a bandana and a coin sack', model=_m('bandiracc')),
    KinSpec(38, 'PEBBOTTER', ('TIDE',), 'C', base=(52, 48, 46, 52, 44, 62), catch=190, xp=60,
            evo=('LEVEL', 24, 'TORRENTTER'),
            category='JUGGLER', height=5, weight=60,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (5, 'M_POUT'), (9, 'M_SLIPSTREAM'), (13, 'M_PEBBLE_PELT'),
                      (17, 'M_UNDERTOW'), (21, 'M_RIPTIDE'), (25, 'M_ROCKFALL')],
            traits=('SOAKER', 'QUICK STUDY'), field=(),
            desc='It juggles smooth river stones to show off and never drops one. Every splash of the '
                 'stream tops up its kernel, so it can play all day long.',
            concept='otter juggling river stones', model=_m('pebbotter')),
    KinSpec(39, 'TORRENTTER', ('TIDE', 'BRAWL'), 'U', base=(92, 112, 80, 60, 70, 86), catch=45, xp=172,
            evo=None,
            category='CLUB OTTER', height=13, weight=420,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_PEBBLE_PELT'),
                      (13, 'M_UNDERTOW'), (17, 'M_ONE_TWO'), (21, 'M_RIPTIDE'), (24, 'M_HAMMER_FIST'),
                      (29, 'M_COUNTERJAB'), (34, 'M_ROCKFALL'), (40, 'M_SWELL'), (47, 'M_HAYMAKER')],
            traits=('SOAKER', 'BRUISER'), field=('SURF', 'STRENGTH'),
            desc='It lashes its favourite river stone to a driftwood haft. The current it rides pumps its '
                 'kernel, and one swing parts the river down to its bed.',
            concept='river otter with a stone club', model=_m('torrentter')),
    KinSpec(40, 'JELLUME', ('TIDE', 'SPARK'), 'C', base=(55, 30, 45, 66, 60, 54), catch=190, xp=60,
            evo=('LEVEL', 26, 'MEDUSHOCK'),
            category='LAMP JELLY', height=4, weight=12,
            learnset=[(1, 'M_FIZZ'), (1, 'M_STATIC_POP'), (5, 'M_TINGLE'), (9, 'M_SLIPSTREAM'),
                      (13, 'M_GLINT'), (17, 'M_LIVE_WIRE'), (21, 'M_UNDERTOW'), (25, 'M_ARC_FLASH'),
                      (29, 'M_SWELL')],
            traits=('CONDUCTOR', 'DRIFTER'), field=('LIGHT',),
            desc='Its bell glows like a hanging lamp as its kernel sheds spare motes as light. Sailors '
                 'follow a drifting string of them home through the night fog.',
            concept='jellyfish whose bell glows like a lamp', model=_m('jellume')),
    KinSpec(41, 'MEDUSHOCK', ('TIDE', 'SPARK'), 'U', base=(80, 55, 70, 110, 95, 90), catch=45, xp=172,
            evo=None,
            category='ARC JELLY', height=18, weight=60,
            learnset=[(1, 'M_FIZZ'), (1, 'M_STATIC_POP'), (1, 'M_TINGLE'), (1, 'M_SLIPSTREAM'),
                      (13, 'M_GLINT'), (17, 'M_LIVE_WIRE'), (21, 'M_UNDERTOW'), (25, 'M_ARC_FLASH'),
                      (30, 'M_SWELL'), (36, 'M_FORKED_BOLT'), (42, 'M_GEYSER'), (49, 'M_OVERCHARGE')],
            traits=('CONDUCTOR', 'STATIC FUR'), field=('LIGHT', 'SURF'),
            desc='Charge builds along its trailing tendrils until the gaps between them arc and snap. '
                 'Fishers pull in their nets when the sea near shore starts to fizz.',
            concept='tall jellyfish whose tendrils arc', model=_m('medushock')),
    KinSpec(42, 'LURELING', ('TIDE', 'DUSK'), 'U', base=(55, 48, 42, 62, 45, 50), catch=180, xp=62,
            evo=('LEVEL', 30, 'ABYSSLURE'),
            category='LURE FRY', height=3, weight=15,
            learnset=[(1, 'M_FIZZ'), (1, 'M_STARE_DOWN'), (5, 'M_SNAP'), (9, 'M_LANTERN_LURE'),
                      (13, 'M_SLIPSTREAM'), (17, 'M_GLINT'), (21, 'M_UNDERTOW'), (25, 'M_HAUNT'),
                      (29, 'M_GNASH'), (33, 'M_GLOOM_ORB')],
            traits=('GLOWER', 'SLIPPERY'), field=('LIGHT',),
            desc='The bead on its lure is its own kernel, glowing to draw in prey. When a shy one hides '
                 'the light behind its fins, it simply blinks out of sight.',
            concept='anglerfish fry; its lure is a tiny kernel', model=_m('lureling')),
    KinSpec(43, 'ABYSSLURE', ('TIDE', 'DUSK'), 'U', base=(95, 100, 75, 105, 75, 60), catch=45, xp=175,
            evo=None,
            category='ABYSS LAMP', height=16, weight=900,
            learnset=[(1, 'M_FIZZ'), (1, 'M_STARE_DOWN'), (1, 'M_SNAP'), (1, 'M_LANTERN_LURE'),
                      (13, 'M_SLIPSTREAM'), (17, 'M_GLINT'), (21, 'M_UNDERTOW'), (25, 'M_HAUNT'),
                      (30, 'M_GNASH'), (35, 'M_GLOOM_ORB'), (41, 'M_SWELL'), (48, 'M_GEYSER')],
            traits=('GLOWER', 'SOAKER'), field=('LIGHT', 'SURF'),
            desc='It hangs in the black deep with its lantern lit. Its dusk kernel drinks every glimmer '
                 'around it, so all anyone ever sees is the lamp and a grin.',
            concept='deep anglerfish, lure like a lantern', model=_m('abysslure')),
    KinSpec(44, 'RADISHOO', ('BLOOM',), 'C', base=(50, 42, 50, 58, 60, 40), catch=190, xp=58,
            evo=('LEVEL', 22, 'MANDRAGOR'),
            category='ROOTLING', height=4, weight=20,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (5, 'M_SAP_SIP'), (9, 'M_GRIT_KICK'),
                      (13, 'M_BRAMBLE_LASH'), (17, 'M_DROWSY_POLLEN'), (21, 'M_LEAF_FLURRY'), (25, 'M_BASK')],
            traits=('BASKER', 'SLIPPERY'), field=(),
            desc='It shoos away anyone who tugs its leaves, then dives back into the soil. A patch it '
                 'lives in grows the sweetest radishes in the Vale.',
            concept='radish sprite with a leafy tuft', model=_m('radishoo')),
    KinSpec(45, 'MANDRAGOR', ('BLOOM', 'DREAM'), 'U', base=(82, 60, 76, 112, 110, 60), catch=45, xp=172,
            evo=None,
            category='MANDRAKE', height=10, weight=150,
            learnset=[(1, 'M_BONK'), (1, 'M_SAP_SIP'), (1, 'M_DROWSY_POLLEN'), (1, 'M_DAYDREAM'),
                      (13, 'M_BRAMBLE_LASH'), (17, 'M_LEAF_FLURRY'), (22, 'M_LULLABY'), (26, 'M_PRISM_RAY'),
                      (30, 'M_SIGIL_SNARE'), (31, 'M_STILL_POND'), (36, 'M_DREAMQUAKE'), (42, 'M_SUNSHAFT'),
                      (48, 'M_PRIMAL_ROAR')],
            traits=('WAKEFUL', 'BASKER'), field=('TELEPORT',),
            desc='Pulled from the earth, it screams a note so pure that every mind nearby falls into '
                 'step with it and dozes off. Wise diggers plug their ears with wax.',
            concept='mandrake whose scream is a lullaby', model=_m('mandragor')),
    KinSpec(46, 'PUMPKLING', ('BLOOM',), 'C', base=(55, 50, 58, 40, 60, 35), catch=190, xp=60,
            evo=('LEVEL', 28, 'JACKOGRIM'),
            category='PUMPKIN', height=4, weight=50,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (5, 'M_BRAMBLE_LASH'), (9, 'M_BRACE'),
                      (13, 'M_BURR_VOLLEY'), (17, 'M_SAP_SIP'), (21, 'M_LANTERN_LURE'), (25, 'M_THORN_WALL'),
                      (29, 'M_BELLY_FLOP')],
            traits=('BASKER', 'STUBBORN'), field=(),
            desc='It carves its own grin so the sunlight it soaks up by day can shine back out at night. '
                 'Children find their way home by the glow of a pumpkling patch.',
            concept='pumpkin sprout with a carved grin', model=_m('pumpkling')),
    KinSpec(47, 'JACKOGRIM', ('BLOOM', 'HOLLOW'), 'U', base=(85, 95, 80, 90, 95, 60), catch=45, xp=172,
            evo=None,
            category='GRIM GOURD', height=17, weight=300,
            learnset=[(1, 'M_BONK'), (1, 'M_BRAMBLE_LASH'), (1, 'M_LANTERN_LURE'), (1, 'M_BONE_RATTLE'),
                      (13, 'M_BURR_VOLLEY'), (17, 'M_SAP_SIP'), (21, 'M_GRAVE_CHILL'), (26, 'M_THORN_WALL'),
                      (30, 'M_SHROUD'), (35, 'M_REED_BLADE'), (40, 'M_DEATH_KNELL'), (47, 'M_REQUIEM')],
            traits=('SELFMEND', 'GLOWER'), field=('LIGHT',),
            desc='Its kernel outlived the vine and now pumps from the slow warmth of old bone. It walks '
                 'the burnt fields at night, its carved head lit by a hundred harvests.',
            concept="vine-bodied jack-o'-lantern with a lantern head", model=_m('jackogrim')),
    KinSpec(48, 'SHROOMLET', ('BLOOM', 'VENOM'), 'C', base=(58, 42, 55, 50, 70, 30), catch=190, xp=60,
            evo=('LEVEL', 30, 'MYCOLOSSUS'),
            category='SPORE TOT', height=3, weight=20,
            learnset=[(1, 'M_BONK'), (1, 'M_SPORE_CLOUD'), (5, 'M_BARB'), (9, 'M_SAP_SIP'),
                      (13, 'M_DROWSY_POLLEN'), (17, 'M_ACID_SPIT'), (21, 'M_BRAMBLE_LASH'), (25, 'M_FESTER'),
                      (29, 'M_BASK'), (33, 'M_BOG_BOMB')],
            traits=('SPORESKIN', 'SELFMEND'), field=(),
            desc='It sneezes out puffs of spores when it is tickled. The slow rot of fallen logs pumps '
                 'its kernel, so a damp log in the shade is its idea of a feast.',
            concept='mushroom-cap tot that puffs spores', model=_m('shroomlet')),
    KinSpec(49, 'MYCOLOSSUS', ('BLOOM', 'VENOM'), 'U', base=(110, 100, 100, 70, 90, 30), catch=45, xp=175,
            evo=None,
            category='SPORE GIANT', height=22, weight=2200,
            learnset=[(1, 'M_BONK'), (1, 'M_SPORE_CLOUD'), (1, 'M_BARB'), (1, 'M_SAP_SIP'),
                      (13, 'M_DROWSY_POLLEN'), (17, 'M_ACID_SPIT'), (21, 'M_BRAMBLE_LASH'), (25, 'M_FESTER'),
                      (32, 'M_THORN_WALL'), (37, 'M_BOG_BOMB'), (43, 'M_FAULTLINE'), (50, 'M_SUNSHAFT')],
            traits=('SPORESKIN', 'STUBBORN'), field=('STRENGTH',),
            desc='Its threads run under the whole forest floor and link the roots of every tree. When it '
                 'walks, the ground shivers and every mushroom nearby turns to watch.',
            concept='walking giant fungus', model=_m('mycolossus')),
    KinSpec(50, 'BLINKET', ('SWARM', 'SPARK'), 'C', base=(40, 45, 40, 58, 42, 80), catch=190, xp=58,
            evo=('LEVEL', 22, 'BEACONFLY'),
            category='FIREFLY', height=2, weight=3,
            learnset=[(1, 'M_STATIC_POP'), (1, 'M_POUT'), (5, 'M_PINCER'), (9, 'M_TINGLE'), (13, 'M_GLINT'),
                      (17, 'M_WINGDUST'), (21, 'M_LIVE_WIRE'), (25, 'M_SWARM_RUSH')],
            traits=('CONDUCTOR', 'KEEN EYE'), field=('LIGHT',),
            desc='Its tail blinks in time with every blinket nearby until the whole meadow flashes as '
                 'one. That shared beat is what makes a swarm kernel strong.',
            concept='firefly with a blinking tail', model=_m('blinket')),
    KinSpec(51, 'BEACONFLY', ('SWARM', 'SPARK'), 'U', base=(70, 75, 70, 105, 80, 105), catch=45, xp=172,
            evo=None,
            category='BEACON', height=12, weight=85,
            learnset=[(1, 'M_STATIC_POP'), (1, 'M_POUT'), (1, 'M_PINCER'), (1, 'M_TINGLE'), (13, 'M_GLINT'),
                      (17, 'M_WINGDUST'), (21, 'M_LIVE_WIRE'), (26, 'M_SWARM_RUSH'), (31, 'M_ARC_FLASH'),
                      (37, 'M_FORKED_BOLT'), (44, 'M_UPDRAFT'), (50, 'M_OVERCHARGE')],
            traits=('CONDUCTOR', 'FOCUSED'), field=('LIGHT',),
            desc='Its lantern body can light a whole valley. On summer nights swarms gather round it and '
                 'flash in sync, bright enough to be seen from the next town.',
            concept='big firefly with a lantern abdomen', model=_m('beaconfly')),
    KinSpec(52, 'STATICKO', ('SPARK',), 'C', base=(42, 45, 38, 62, 40, 78), catch=190, xp=58,
            evo=('LEVEL', 25, 'FULGECKO'),
            category='WALL GECKO', height=3, weight=8,
            learnset=[(1, 'M_POUT'), (1, 'M_STATIC_POP'), (5, 'M_DART'), (9, 'M_TINGLE'), (13, 'M_LIVE_WIRE'),
                      (17, 'M_SWIPE'), (21, 'M_STARE_DOWN'), (25, 'M_ARC_FLASH')],
            traits=('STATIC FUR', 'SLIPPERY'), field=(),
            desc='It rubs its toes on dry grass until they crackle, then strolls up walls and across '
                 'ceilings on static cling alone. Touch it and you get a snap.',
            concept='gecko that sticks to walls with static', model=_m('staticko')),
    KinSpec(53, 'FULGECKO', ('SPARK', 'BEAST'), 'U', base=(78, 88, 68, 100, 70, 112), catch=45, xp=172,
            evo=None,
            category='BOLT FRILL', height=14, weight=260,
            learnset=[(1, 'M_STATIC_POP'), (1, 'M_DART'), (1, 'M_TINGLE'), (1, 'M_SWIPE'),
                      (13, 'M_STARE_DOWN'), (17, 'M_LIVE_WIRE'), (21, 'M_SNARL'), (25, 'M_ARC_FLASH'),
                      (30, 'M_FORKED_BOLT'), (36, 'M_RECKLESS_RUSH'), (42, 'M_OVERCHARGE'), (48, 'M_PRIMAL_ROAR')],
            traits=('STATIC FUR', 'MOMENTUM'), field=('LIGHT',),
            desc='Cornered, it rears up on its hind legs and flares its frill. Sparks leap from spine to '
                 'spine with a crack loud enough to send a bear running.',
            concept='frilled lightning lizard', model=_m('fulgecko')),
    KinSpec(54, 'FLURRABBIT', ('FROST',), 'C', base=(48, 45, 45, 55, 50, 67), catch=190, xp=60,
            evo=('ITEM', 'ASTRAL_SHARD', 'MOONHARE'),
            category='SNOW HARE', height=4, weight=30,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (5, 'M_FLURRY'), (9, 'M_DART'), (13, 'M_RIME_SHOT'),
                      (17, 'M_SNOWDRIFT'), (21, 'M_HAILSTONES'), (26, 'M_CATNAP'), (31, 'M_WINTER_RAY'),
                      (36, 'M_BELLY_FLOP')],
            traits=('THICK FUR', 'SLIPPERY'), field=(),
            desc='Its kernel pumps by shedding heat, so the snow it hops over turns to fine powder. On '
                 'clear, cold nights it sits and stares at the moon for hours.',
            concept='snow hare', model=_m('flurrabbit')),
    KinSpec(55, 'MOONHARE', ('FROST', 'ASTRAL'), 'U', base=(80, 85, 70, 105, 80, 90), catch=45, xp=172,
            evo=None,
            category='MOON HARE', height=12, weight=180,
            learnset=[(1, 'M_BONK'), (1, 'M_FLURRY'), (1, 'M_TWINKLE'), (1, 'M_RIME_SHOT'), (13, 'M_SNOWDRIFT'),
                      (17, 'M_STARDUST'), (21, 'M_MOONBEAM'), (26, 'M_HAILSTONES'), (30, 'M_ISA_SEAL'),
                      (31, 'M_NEBULA_VEIL'), (36, 'M_COMET_DASH'), (42, 'M_WINTER_RAY'), (48, 'M_MUON_RAIN')],
            traits=('THICK FUR', 'FOCUSED'), field=('TELEPORT',),
            desc='An ASTRAL SHARD tuned it to the muons raining down from the sky. Under a full moon it '
                 'pounds rice cakes with its mallet, and the thuds ring like bells.',
            concept='moon rabbit with a mochi mallet', model=_m('moonhare')),
    KinSpec(56, 'TUXFLAKE', ('FROST', 'TIDE'), 'C', base=(55, 42, 52, 52, 55, 44), catch=190, xp=60,
            evo=('LEVEL', 30, 'EMPERICE'),
            category='FLUFF CHICK', height=4, weight=45,
            learnset=[(1, 'M_POUT'), (1, 'M_BONK'), (5, 'M_FIZZ'), (9, 'M_FLURRY'), (13, 'M_RIME_SHOT'),
                      (17, 'M_SLIPSTREAM'), (21, 'M_BELLY_FLOP'), (25, 'M_UNDERTOW'), (29, 'M_SNOWDRIFT'),
                      (33, 'M_HAILSTONES')],
            traits=('THICK FUR', 'SOAKER'), field=(),
            desc='Its down is so thick that snow clings to it in a round puff. It waddles to the water and '
                 'belly-slides the last stretch in, squeaking all the way.',
            concept='penguin chick in a snow puff', model=_m('tuxflake')),
    KinSpec(57, 'EMPERICE', ('FROST', 'TIDE'), 'U', base=(95, 75, 85, 100, 95, 60), catch=45, xp=172,
            evo=None,
            category='EMPEROR', height=14, weight=400,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_FLURRY'), (1, 'M_SLIPSTREAM'), (13, 'M_RIME_SHOT'),
                      (17, 'M_BELLY_FLOP'), (21, 'M_UNDERTOW'), (25, 'M_SNOWDRIFT'), (32, 'M_RIPTIDE'),
                      (37, 'M_WINTER_RAY'), (43, 'M_SWELL'), (49, 'M_GEYSER')],
            traits=('THICK FUR', 'SOAKER'), field=('SURF',),
            desc='Its crown of rime grows a new point every hard winter. In blizzards the colony huddles '
                 'behind it, and it never once turns its back to the wind.',
            concept='emperor penguin with an ice crown', model=_m('emperice')),
    KinSpec(58, 'YAKLING', ('FROST', 'BEAST'), 'C', base=(65, 55, 55, 40, 50, 35), catch=190, xp=62,
            evo=('LEVEL', 32, 'GLACIYAK'),
            category='YAK CALF', height=7, weight=800,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (5, 'M_FLURRY'), (9, 'M_BRACE'), (13, 'M_RIME_SHOT'),
                      (17, 'M_SWIPE'), (21, 'M_HAILSTONES'), (25, 'M_BELLY_FLOP'), (29, 'M_SNOWDRIFT'),
                      (33, 'M_RECKLESS_RUSH')],
            traits=('THICK FUR', 'STUBBORN'), field=(),
            desc='Its fringe hangs over its eyes, yet it never gets lost: it simply follows the cold. '
                 'Herders comb its shed wool into the warmest scarves in the Vale.',
            concept='shaggy yak calf', model=_m('yakling')),
    KinSpec(59, 'GLACIYAK', ('FROST', 'BEAST'), 'U', base=(115, 105, 95, 60, 85, 45), catch=45, xp=178,
            evo=None,
            category='GLACIER YAK', height=20, weight=6800,
            learnset=[(1, 'M_BONK'), (1, 'M_FLURRY'), (1, 'M_BRACE'), (1, 'M_RIME_SHOT'), (13, 'M_SWIPE'),
                      (17, 'M_HAILSTONES'), (21, 'M_BELLY_FLOP'), (25, 'M_SNOWDRIFT'), (33, 'M_STONESKIN'),
                      (38, 'M_RECKLESS_RUSH'), (44, 'M_WINTER_RAY'), (50, 'M_FAULTLINE')],
            traits=('THICK FUR', 'STUBBORN'), field=('STRENGTH',),
            desc='Its horns are ice that never melts. A herd crossing a pass pulls so much heat from the '
                 'air that the snow behind it freezes hard enough to walk on.',
            concept='glacier yak with icicle horns', model=_m('glaciyak')),
    KinSpec(60, 'RAMBLET', ('BRAWL',), 'C', base=(55, 68, 50, 30, 40, 55), catch=190, xp=60,
            evo=('LEVEL', 26, 'CRAGHORN'),
            category='RAM LAMB', height=5, weight=180,
            learnset=[(1, 'M_BONK'), (1, 'M_POUT'), (5, 'M_BRACE'), (9, 'M_ONE_TWO'), (13, 'M_DART'),
                      (17, 'M_HAMMER_FIST'), (21, 'M_WAR_CRY'), (25, 'M_COUNTERJAB'), (29, 'M_RECKLESS_RUSH')],
            traits=('BRUISER', 'STUBBORN'), field=(),
            desc='It headbutts fences, trees and its own shadow. Every bump strains its skull and pumps '
                 'its kernel, so each knock only makes it bouncier.',
            concept='lamb that headbutts everything', model=_m('ramblet')),
    KinSpec(61, 'CRAGHORN', ('BRAWL', 'STONE'), 'U', base=(90, 125, 105, 45, 65, 75), catch=45, xp=175,
            evo=None,
            category='CRAG RAM', height=13, weight=1200,
            learnset=[(1, 'M_BONK'), (1, 'M_BRACE'), (1, 'M_ONE_TWO'), (1, 'M_GRIT_KICK'), (13, 'M_DART'),
                      (17, 'M_HAMMER_FIST'), (21, 'M_PEBBLE_PELT'), (26, 'M_WAR_CRY'), (30, 'M_ROCKFALL'),
                      (35, 'M_COUNTERJAB'), (41, 'M_FAULTLINE'), (47, 'M_HAYMAKER')],
            traits=('BRUISER', 'BEDROCK'), field=('STRENGTH',),
            desc='Its horns are stone, grown from the strain of a thousand clashes. When two meet on a '
                 'ridge, the crack of their horns rolls down the valley like thunder.',
            concept='mountain ram with rock-hard horns', model=_m('craghorn')),
    KinSpec(62, 'STINGLET', ('VENOM',), 'C', base=(45, 58, 55, 40, 45, 62), catch=190, xp=60,
            evo=('LEVEL', 27, 'SCORCHION'),
            category='SCORPLING', height=2, weight=12,
            learnset=[(1, 'M_BARB'), (1, 'M_POUT'), (5, 'M_PINCER'), (9, 'M_GRIT_KICK'), (13, 'M_SPORE_CLOUD'),
                      (17, 'M_ACID_SPIT'), (21, 'M_FESTER'), (25, 'M_SNAP'), (29, 'M_BOG_BOMB')],
            traits=('SPORESKIN', 'KEEN EYE'), field=(),
            desc='The drop on its tail is sour, not deadly: fruit sugars fermented in its sting. It hides '
                 'under sun-warmed stones and pinches curious toes.',
            concept='scorpling', model=_m('stinglet')),
    KinSpec(63, 'SCORCHION', ('VENOM', 'BLAZE'), 'U', base=(80, 105, 90, 90, 70, 75), catch=45, xp=172,
            evo=None,
            category='EMBER TAIL', height=12, weight=350,
            learnset=[(1, 'M_BARB'), (1, 'M_PINCER'), (1, 'M_CINDER_FLICK'), (1, 'M_GRIT_KICK'),
                      (13, 'M_SPORE_CLOUD'), (17, 'M_ACID_SPIT'), (21, 'M_SEAR_BITE'), (26, 'M_FESTER'),
                      (30, 'M_LAST_EMBER'), (35, 'M_EMBER_STORM'), (41, 'M_BOG_BOMB'), (48, 'M_KILN_BREATH')],
            traits=('EMBERSKIN', 'SPORESKIN'), field=('LIGHT',),
            desc='Its sting burns as hot as a coal. It basks in volcanic vents until its shell glows, and '
                 'its trail through the ash is a line of little embers.',
            concept='ember-tailed scorpion', model=_m('scorchion')),
    KinSpec(64, 'DIGGET', ('STONE',), 'C', base=(55, 60, 65, 30, 40, 50), catch=190, xp=60,
            evo=('ITEM', 'HOLLOW_SHARD', 'SEXTONE'),
            category='LAMP MOLE', height=3, weight=40,
            learnset=[(1, 'M_BONK'), (1, 'M_GRIT_KICK'), (5, 'M_MUD_PIE'), (9, 'M_SWIPE'), (13, 'M_PEBBLE_PELT'),
                      (17, 'M_STONESKIN'), (21, 'M_SANDBLAST'), (26, 'M_ROCKFALL'), (31, 'M_LANTERN_LURE'),
                      (36, 'M_FAULTLINE')],
            traits=('BEDROCK', 'HOARDER'), field=(),
            desc='It carries a tiny lantern into its tunnels, though it can barely see. The strain of the '
                 'rock it digs through pumps its kernel, so it hums as it works.',
            concept='mole with a tiny lantern', model=_m('digget')),
    KinSpec(65, 'SEXTONE', ('STONE', 'HOLLOW'), 'U', base=(95, 110, 115, 50, 75, 55), catch=45, xp=175,
            evo=None,
            category='SEXTON', height=13, weight=700,
            learnset=[(1, 'M_BONK'), (1, 'M_GRIT_KICK'), (1, 'M_MUD_PIE'), (1, 'M_BONE_RATTLE'),
                      (13, 'M_PEBBLE_PELT'), (17, 'M_STONESKIN'), (21, 'M_GRAVE_CHILL'), (26, 'M_ROCKFALL'),
                      (30, 'M_THURS_SPIKE'), (31, 'M_OSSIFY'), (36, 'M_LAST_RITES'), (42, 'M_FAULTLINE'),
                      (48, 'M_DEATH_KNELL')],
            traits=('BEDROCK', 'HOARDER'), field=('STRENGTH',),
            desc='A HOLLOW SHARD tied its kernel to the slow warmth of old bone. It tends graveyards by '
                 'lantern light and sets a stone wherever it turns up bones.',
            concept='gravedigger mole with a spade and a lantern', model=_m('sextone')),
    KinSpec(66, 'QUARTZLING', ('STONE', 'SWARM'), 'U', base=(50, 55, 70, 40, 45, 40), catch=180, xp=62,
            evo=('LEVEL', 30, 'QUARTZPEDE'),
            category='GEM GRUB', height=3, weight=60,
            learnset=[(1, 'M_BONK'), (1, 'M_SILK_SNARE'), (5, 'M_GRIT_KICK'), (9, 'M_PINCER'),
                      (13, 'M_PEBBLE_PELT'), (17, 'M_STONESKIN'), (21, 'M_SANDBLAST'), (25, 'M_SWARM_RUSH'),
                      (29, 'M_ROCKFALL'), (33, 'M_GLINT')],
            traits=('BEDROCK', 'STUBBORN'), field=(),
            desc='It eats gravel and grows a new quartz point on its back each time it moults. Squeezed, '
                 'the crystals spit sparks, so its back glitters as it squirms.',
            concept='crystal grub', model=_m('quartzling')),
]
