"""Kin 101-120. Owner: KIN-C (rare kin 101-120).

PLACEHOLDER data and art: stats, learnsets, traits and descriptions
were generated from docs/EXPANSION.md; replace every entry with the real
design (keep id, name, types, rarity and growth), give it a model, and
set placeholder=False (then its base stat total is checked by tier).
"""

from kin import KinSpec

SPECIES = [
    KinSpec(101, 'KOIRIN', ('TIDE',), 'R', base=(80, 40, 60, 60, 60, 40), catch=190, xp=60, evo=('LEVEL', 35, 'RYUKOI'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (5, 'M_SLIPSTREAM'), (10, 'M_UNDERTOW'), (15, 'M_RIPTIDE'), (20, 'M_SWELL'), (25, 'M_GEYSER')],
            traits=('SURGE', 'SOAKER'), field=(),
            desc='Koi that climbs waterfalls.',
            concept='koi that climbs waterfalls', placeholder=True),
    KinSpec(102, 'RYUKOI', ('TIDE', 'WYRM'), 'R', base=(119, 79, 79, 106, 79, 53), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_WYRM_DANCE'), (14, 'M_WYRMBREATH'), (20, 'M_UNDERTOW'), (26, 'M_RIPTIDE'), (32, 'M_SCALE_REND'), (38, 'M_SWELL'), (44, 'M_GEYSER'), (50, 'M_STARFALL')],
            traits=('SURGE', 'KEEN EYE'), field=('SURF', 'FLY'),
            desc='The koi became a dragon.',
            concept='the koi became a dragon', placeholder=True),
    KinSpec(103, 'TRINKIT', ('RELIC',), 'R', base=(37, 38, 94, 76, 57, 38), catch=190, xp=60, evo=('ITEM', 'RELIC_SHARD', 'HOARDMAW'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (5, 'M_CLATTER'), (10, 'M_TARNISH'), (15, 'M_POLTERGUST'), (20, 'M_GILDED_GLEAM'), (25, 'M_CHEST_CHOMP'), (30, 'M_CURSED_CURIO'), (35, 'M_HEIRLOOM')],
            traits=('HOARDER', 'BEDROCK'), field=(),
            desc='A jewellery box with teeth (mimic).',
            concept='a jewellery box with teeth (mimic)', placeholder=True),
    KinSpec(104, 'HOARDMAW', ('RELIC', 'BEAST'), 'R', base=(73, 61, 123, 98, 86, 74), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_CLATTER'), (1, 'M_TARNISH'), (14, 'M_SWIPE'), (20, 'M_POLTERGUST'), (26, 'M_CATNAP'), (31, 'M_RAIDO_RUSH'), (32, 'M_CHEST_CHOMP'), (38, 'M_GILDED_GLEAM'), (44, 'M_SNARL'), (50, 'M_CURSED_CURIO')],
            traits=('HOARDER', 'MOMENTUM'), field=(),
            desc='A treasure-chest mimic on legs.',
            concept='a treasure-chest mimic on legs', placeholder=True),
    KinSpec(105, 'RATTLEBONE', ('HOLLOW',), 'R', base=(60, 40, 80, 40, 80, 40), catch=190, xp=60, evo=('ITEM', 'METAL_SHARD', 'OSSIGUARD'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_BONE_RATTLE'), (5, 'M_LAST_RITES'), (10, 'M_SHROUD'), (15, 'M_GRAVE_CHILL'), (20, 'M_MARROW_SIP'), (25, 'M_OSSIFY'), (30, 'M_DEATH_KNELL'), (35, 'M_REQUIEM')],
            traits=('STUBBORN', 'SELFMEND'), field=(),
            desc='Skeleton squire with a pot helmet.',
            concept='skeleton squire with a pot helmet', placeholder=True),
    KinSpec(106, 'OSSIGUARD', ('HOLLOW', 'METAL'), 'R', base=(77, 78, 140, 52, 116, 52), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_RIVET_SHOT'), (1, 'M_BONE_RATTLE'), (1, 'M_IRON_TAP'), (14, 'M_LAST_RITES'), (20, 'M_MAGNET_PULL'), (26, 'M_SHROUD'), (32, 'M_STEEL_SHELL'), (38, 'M_GRAVE_CHILL'), (44, 'M_FORGE_FLASH'), (50, 'M_MARROW_SIP')],
            traits=('STUBBORN', 'BRUISER'), field=('STRENGTH',),
            desc='Skeleton knight.',
            concept='skeleton knight', placeholder=True),
    KinSpec(107, 'GAUNTLING', ('RELIC', 'METAL'), 'R', base=(32, 49, 105, 65, 57, 32), catch=190, xp=60, evo=('LEVEL', 36, 'HOLLOWHELM'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (5, 'M_RIVET_SHOT'), (10, 'M_CLATTER'), (15, 'M_IRON_TAP'), (20, 'M_MAGNET_PULL'), (25, 'M_STEEL_SHELL'), (27, 'M_RAIDO_RUSH'), (30, 'M_TARNISH'), (35, 'M_FORGE_FLASH'), (40, 'M_POLTERGUST'), (45, 'M_GILDED_GLEAM')],
            traits=('HOARDER', 'BRUISER'), field=(),
            desc='A gauntlet that walks on its fingers.',
            concept='a gauntlet that walks on its fingers', placeholder=True),
    KinSpec(108, 'HOLLOWHELM', ('RELIC', 'METAL'), 'R', base=(53, 78, 140, 102, 90, 52), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_RIVET_SHOT'), (1, 'M_CLATTER'), (14, 'M_IRON_TAP'), (20, 'M_MAGNET_PULL'), (26, 'M_STEEL_SHELL'), (29, 'M_RAIDO_RUSH'), (31, 'M_ALGIZ_WARD'), (32, 'M_TARNISH'), (38, 'M_FORGE_FLASH'), (44, 'M_POLTERGUST'), (50, 'M_GILDED_GLEAM')],
            traits=('HOARDER', 'BRUISER'), field=('STRENGTH',),
            desc='An empty suit of armour.',
            concept='an empty suit of armour', placeholder=True),
    KinSpec(109, 'WICKLET', ('RELIC', 'BLAZE'), 'R', base=(33, 41, 83, 83, 50, 50), catch=190, xp=60, evo=('LEVEL', 32, 'LAMPGHAST'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (5, 'M_CINDER_FLICK'), (10, 'M_CLATTER'), (15, 'M_LAST_EMBER'), (20, 'M_LANTERN_LURE'), (25, 'M_TARNISH'), (27, 'M_KENAZ_FLARE'), (30, 'M_POLTERGUST'), (35, 'M_SEAR_BITE'), (40, 'M_GILDED_GLEAM'), (45, 'M_EMBER_STORM')],
            traits=('HOARDER', 'EMBERSKIN'), field=('LIGHT',),
            desc='A candle wick sprite.',
            concept='a candle wick sprite', placeholder=True),
    KinSpec(110, 'LAMPGHAST', ('RELIC', 'BLAZE'), 'R', base=(50, 63, 126, 126, 75, 75), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_CINDER_FLICK'), (1, 'M_CLATTER'), (14, 'M_LAST_EMBER'), (20, 'M_LANTERN_LURE'), (26, 'M_TARNISH'), (29, 'M_KENAZ_FLARE'), (32, 'M_POLTERGUST'), (38, 'M_SEAR_BITE'), (44, 'M_GILDED_GLEAM'), (50, 'M_EMBER_STORM')],
            traits=('HOARDER', 'EMBERSKIN'), field=('LIGHT',),
            desc='Paper lantern ghost (chochin-obake).',
            concept='paper lantern ghost (chochin-obake)', placeholder=True),
    KinSpec(111, 'METEORB', ('ASTRAL', 'STONE'), 'R', base=(76, 51, 60, 85, 34, 34), catch=190, xp=60, evo=('LEVEL', 38, 'BOLIDON'),
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TWINKLE'), (5, 'M_GRIT_KICK'), (10, 'M_NEBULA_VEIL'), (12, 'M_RUNE_BOLT'), (15, 'M_STARDUST'), (20, 'M_STONESKIN'), (25, 'M_PEBBLE_PELT'), (29, 'M_THURS_SPIKE'), (30, 'M_MUD_PIE'), (35, 'M_MOONBEAM'), (40, 'M_SANDBLAST'), (45, 'M_ROCKFALL')],
            traits=('FOCUSED', 'STUBBORN'), field=(),
            desc='A meteorite with stubby legs.',
            concept='a meteorite with stubby legs', placeholder=True),
    KinSpec(112, 'BOLIDON', ('ASTRAL', 'STONE'), 'R', base=(115, 77, 90, 129, 52, 52), catch=45, xp=220, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TWINKLE'), (1, 'M_GRIT_KICK'), (1, 'M_NEBULA_VEIL'), (12, 'M_RUNE_BOLT'), (14, 'M_STARDUST'), (20, 'M_STONESKIN'), (26, 'M_PEBBLE_PELT'), (32, 'M_MUD_PIE'), (37, 'M_THURS_SPIKE'), (38, 'M_MOONBEAM'), (44, 'M_SANDBLAST'), (50, 'M_ROCKFALL'), (46, 'M_METEOR_FALL'), (56, 'M_RUNE_ORBIT')],
            traits=('FOCUSED', 'STUBBORN'), field=('STRENGTH', 'LIGHT'),
            desc='Fireball meteor beast.',
            concept='fireball meteor beast', placeholder=True),
    KinSpec(113, 'KELPYRE', ('TIDE', 'DUSK'), 'R', base=(103, 51, 77, 115, 77, 77), catch=30, xp=190, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_FIZZ'), (1, 'M_SLIPSTREAM'), (1, 'M_STARE_DOWN'), (14, 'M_SNAP'), (20, 'M_UNDERTOW'), (26, 'M_HAUNT'), (32, 'M_SHADE_CUT'), (38, 'M_RIPTIDE'), (44, 'M_GLOOM_ORB'), (50, 'M_GNASH')],
            traits=('SURGE', 'SLIPPERY'), field=('SURF',),
            desc='Kelpie water horse.',
            concept='kelpie water horse', placeholder=True),
    KinSpec(114, 'TENGALE', ('GALE', 'BRAWL'), 'R', base=(74, 138, 50, 50, 50, 138), catch=30, xp=190, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (1, 'M_ONE_TWO'), (1, 'M_BEAK_JAB'), (14, 'M_DRAFT'), (20, 'M_UPDRAFT'), (26, 'M_WAR_CRY'), (32, 'M_HAMMER_FIST'), (38, 'M_COUNTERJAB'), (44, 'M_FEATHER_CUT'), (50, 'M_CROSSWIND')],
            traits=('DRIFTER', 'STUBBORN'), field=('FLY',),
            desc='Tengu, long nose and a feather fan.',
            concept='tengu, long nose and a feather fan', placeholder=True),
    KinSpec(115, 'SLUMBAKU', ('DREAM', 'BEAST'), 'R', base=(76, 62, 50, 125, 112, 75), catch=30, xp=190, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_SWIPE'), (1, 'M_DART'), (1, 'M_BRACE'), (14, 'M_CATNAP'), (20, 'M_LULLABY'), (26, 'M_POUT'), (32, 'M_STILL_POND'), (38, 'M_DAYDREAM'), (44, 'M_SNARL'), (50, 'M_GLINT')],
            traits=('FOCUSED', 'MOMENTUM'), field=('TELEPORT',),
            desc='Baku dream-eater tapir.',
            concept='baku dream-eater tapir', placeholder=True),
    KinSpec(116, 'WENDIGAUNT', ('FROST', 'HOLLOW'), 'R', base=(63, 51, 103, 103, 103, 77), catch=30, xp=190, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_HAILSTONES'), (1, 'M_BONE_RATTLE'), (1, 'M_FLURRY'), (14, 'M_RIME_SHOT'), (20, 'M_LAST_RITES'), (26, 'M_SNOWDRIFT'), (32, 'M_SHROUD'), (35, 'M_ISA_SEAL'), (36, 'M_GRAVE_CHILL'), (40, 'M_MARROW_SIP'), (45, 'M_OSSIFY'), (50, 'M_WINTER_RAY')],
            traits=('THICK FUR', 'SELFMEND'), field=(),
            desc='Wendigo, antlered and gaunt.',
            concept='wendigo, antlered and gaunt', placeholder=True),
    KinSpec(117, 'LAMPJINN', ('RELIC', 'GALE'), 'R', base=(49, 73, 122, 98, 73, 85), catch=30, xp=190, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_TRINKET_TOSS'), (1, 'M_BEAK_JAB'), (1, 'M_CLATTER'), (14, 'M_DRAFT'), (20, 'M_TARNISH'), (23, 'M_ALGIZ_WARD'), (26, 'M_UPDRAFT'), (29, 'M_RUNE_SIPHON'), (31, 'M_SOWILO_BEAM'), (32, 'M_FEATHER_CUT'), (38, 'M_POLTERGUST'), (44, 'M_GILDED_GLEAM'), (50, 'M_CROSSWIND')],
            traits=('HOARDER', 'MOMENTUM'), field=('TELEPORT',),
            desc='A genie rising from an oil lamp.',
            concept='a genie rising from an oil lamp', placeholder=True),
    KinSpec(118, 'GARGOLITH', ('STONE', 'DUSK'), 'R', base=(73, 98, 122, 85, 49, 73), catch=30, xp=190, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_GRIT_KICK'), (1, 'M_STARE_DOWN'), (1, 'M_STONESKIN'), (14, 'M_PEBBLE_PELT'), (20, 'M_MUD_PIE'), (26, 'M_SNAP'), (29, 'M_THURS_SPIKE'), (31, 'M_SIGIL_SNARE'), (32, 'M_HAUNT'), (38, 'M_SANDBLAST'), (44, 'M_SHADE_CUT'), (50, 'M_ROCKFALL')],
            traits=('BEDROCK', 'SLIPPERY'), field=('FLY',),
            desc='Gargoyle.',
            concept='gargoyle', placeholder=True),
    KinSpec(119, 'HOPSHI', ('HOLLOW', 'BRAWL'), 'R', base=(100, 88, 100, 50, 100, 62), catch=30, xp=190, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_PUMMEL'), (1, 'M_ONE_TWO'), (1, 'M_BONE_RATTLE'), (14, 'M_LAST_RITES'), (20, 'M_SHROUD'), (26, 'M_WAR_CRY'), (32, 'M_HAMMER_FIST'), (38, 'M_GRAVE_CHILL'), (44, 'M_COUNTERJAB'), (50, 'M_MARROW_SIP')],
            traits=('STUBBORN', 'KEEN EYE'), field=(),
            desc='Hopping vampire (jiangshi).',
            concept='hopping vampire (jiangshi)', placeholder=True),
    KinSpec(120, 'QILUMEN', ('ASTRAL', 'SPARK'), 'R', base=(106, 54, 54, 140, 54, 92), catch=30, xp=190, evo=None,
            category='KIN', height=10, weight=100,
            learnset=[(1, 'M_BONK'), (1, 'M_STATIC_POP'), (1, 'M_TWINKLE'), (1, 'M_NEBULA_VEIL'), (8, 'M_RUNE_BOLT'), (14, 'M_TINGLE'), (20, 'M_LIVE_WIRE'), (26, 'M_MOONBEAM'), (29, 'M_RAIDO_RUSH'), (31, 'M_SOWILO_BEAM'), (32, 'M_ARC_FLASH'), (38, 'M_COMET_DASH'), (44, 'M_STARDUST'), (50, 'M_FORKED_BOLT')],
            traits=('FOCUSED', 'CONDUCTOR'), field=('TELEPORT', 'LIGHT'),
            desc='Kirin with a star-lit mane.',
            concept='kirin with a star-lit mane', placeholder=True),
]
