/* Event IDs are available to world NPC condition data. */
enum { EV_NONE, EV_CARAVAN, EV_OUTBREAK, EV_LOST_KIN, EV_SURGE,
       EV_METEOR, EV_NIGHT_MARKET, EV_FISH_MARKET, EV_WASHOUT,
       EV_TOURNEY, EV_TALES, EV_FESTIVAL, EV_COUNT };
enum { FEST_NONE, FEST_KINDLING, FEST_MILLRACE, FEST_LANTERN, FEST_FROST, FEST_STARFALL, FEST_COUNT };
enum { ER_HOME, ER_EAST, ER_WEST, ER_FORGE, ER_NORTH, ER_ASH, ER_DREAM, ER_COUNT };

enum { EV_CARAVAN_STOP_BASE = 32, EV_FEST_KINDLING = 44 };
