#!/usr/bin/env python3
"""Build the second-generation tile sheets (docs/TILES2.md).

    python3 tools/tiles2/build.py [set ...]      default: every set

Writes assets/tiles2/<set>/ (sheet PNGs, manifest JSON, sample scenes),
assets/tiles2/stats.json (budgets), assets/tiles2/README.md (index) and
assets/tiles2/overview.png (every sample scene). Standard library only.
"""

import importlib
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, 'assets', 'tiles2')

# Registry order = the order sets appear in docs and the overview.
SETS = ['verdant', 'hamlet', 'farm', 'coast', 'snow', 'cave', 'volcanic', 'desert', 'jungle',
        'grim', 'dusk', 'dream', 'crypt', 'tide', 'city', 'interior']

# Which old tileset each replaces (src/game/world/*/maps.inc TS_*).
REPLACES = {
    'verdant': 'wild', 'hamlet': 'town', 'farm': 'farm', 'coast': 'coast', 'snow': 'snow', 'cave': 'cave',
    'volcanic': 'volcanic', 'desert': 'desert', 'jungle': 'jungle', 'grim': 'grim', 'dusk': 'dusk',
    'dream': 'dream', 'crypt': 'crypt', 'tide': 'tide', 'city': 'city', 'interior': 'interior',
}

RESIDENT_MAX = 768     # engine scene tile budget (docs/AREA_TILESETS.md)
CATALOG_MAX = 1024     # 10-bit terrain catalogue ids


def main(argv):
    names = argv[1:] or SETS
    for n in names:
        if n not in SETS:
            raise SystemExit('unknown set %s (known: %s)' % (n, ', '.join(SETS)))
    os.makedirs(OUT, exist_ok=True)
    stats_path = os.path.join(OUT, 'stats.json')
    stats = {}
    if os.path.exists(stats_path):
        with open(stats_path) as f:
            stats = json.load(f)
    bad = 0
    for n in names:
        t0 = time.time()
        mod = importlib.import_module('sets.' + n)
        sheet = mod.build()
        man, scenes = sheet.write(OUT)
        st = man['stats']
        terrain = sum(v for k, v in st['by_kind'].items() if k != 'object')
        stats[n] = {'title': man['title'], 'replaces': REPLACES[n], 'entries': st['entries'],
                    'unique_tiles8': st['unique_tiles8'], 'terrain_tiles8': terrain,
                    'object_tiles8': st['by_kind'].get('object', 0), 'banks': len(man['banks']),
                    'colours': st['colours'], 'variants': sorted(man['variants']),
                    'scenes': [dict(s, title=sc.title) for s, sc in zip(scenes, sheet.scenes)]}
        print('%-9s %3d entries  %4d tiles (terrain %4d)  %d banks  %2d colours  scenes %s  (%.1fs)' % (
            n, st['entries'], st['unique_tiles8'], terrain, len(man['banks']), st['colours'],
            ', '.join('%s=%d' % (s['scene'], s['resident_tiles8']) for s in scenes), time.time() - t0))
        for s in scenes:
            if s['resident_tiles8'] > RESIDENT_MAX:
                print('  ERROR: scene %s needs %d resident tiles (> %d)' % (s['scene'], s['resident_tiles8'],
                                                                            RESIDENT_MAX))
                bad += 1
        if terrain > CATALOG_MAX:
            print('  ERROR: terrain catalogue %d > %d' % (terrain, CATALOG_MAX))
            bad += 1
    ordered = {n: stats[n] for n in SETS if n in stats}
    with open(stats_path, 'w') as f:
        json.dump(ordered, f, indent=1)
        f.write('\n')
    write_readme(ordered)
    if all(n in ordered for n in SETS):
        write_overview(ordered)
        import legacy
        m = legacy.build_map()
        with open(os.path.join(OUT, 'legacy_map.json'), 'w') as f:
            json.dump(m, f, indent=1)
            f.write('\n')
        miss = sum(len(v) for v in m['missing'].values())
        print('legacy map: %d old decor kinds, %d stamps; %d unresolved' % (
            sum(len(v['decor']) for v in m['tilesets'].values()), len(m['stamps']), miss))
        bad += 1 if miss else 0
    return 1 if bad else 0


def write_readme(stats):
    lines = ['# Second-generation tile sets', '',
             'Generated by `python3 tools/tiles2/build.py`; do not edit by hand. The format, '
             'palette rules and integration plan are in [docs/TILES2.md](../../docs/TILES2.md).', '',
             '![Every sample map](overview.png)', '',
             '| Set | Replaces | Entries | 8x8 tiles (terrain) | Banks | Colours | Palette variants | Sample maps (resident tiles / 768) |',
             '| --- | --- | ---: | ---: | ---: | ---: | --- | --- |']
    for n, s in stats.items():
        sc = ', '.join('[%s](%s/scene_%s_x2.png) %d' % (x['title'], n, x['scene'], x['resident_tiles8'])
                       for x in s['scenes'])
        lines.append('| [%s](%s/%s_sheet_x3.png) | `%s` | %d | %d (%d) | %d | %d | %s | %s |' % (
            n, n, n, s['replaces'], s['entries'], s['unique_tiles8'], s['terrain_tiles8'], s['banks'],
            s['colours'], ', '.join(s['variants']) or '-', sc))
    lines += ['', 'Each set directory holds `<set>.png` (the sheet, exact GBA colours), `<set>.json` '
              '(manifest), `<set>@<variant>.png` (palette variants), `<set>_sheet_x3.png` (labelled '
              'review sheet) and `scene_*.png` sample maps (1x, 2x and per variant).', '']
    with open(os.path.join(OUT, 'README.md'), 'w') as f:
        f.write('\n'.join(lines))


def write_overview(stats):
    """All sample scenes on one page (scaled to fit 480 px wide cards)."""
    from core import read_png_rgba, write_png_rgba, draw_text
    cards = []
    for n, s in stats.items():
        for sc in s['scenes']:
            w, h, rows = read_png_rgba(os.path.join(OUT, n, 'scene_%s.png' % sc['scene']))
            cards.append(('%s - %s' % (n, sc['title']), w, h, rows))
    CW, CH, PAD, TOP = 480, 320, 12, 18
    cols = 3
    nrows = (len(cards) + cols - 1) // cols
    W = cols * (CW + PAD) + PAD
    H = nrows * (CH + TOP + PAD) + PAD
    bg = (22, 24, 32, 255)
    out = [[bg] * W for _ in range(H)]
    for i, (title, w, h, rows) in enumerate(cards):
        cx = PAD + (i % cols) * (CW + PAD)
        cy = PAD + (i // cols) * (CH + TOP + PAD)
        draw_text(out, cx, cy + 4, title, (240, 220, 160, 255))
        # crop the top-left CW x CH of the map (1x, exact pixels)
        for y in range(min(CH, h)):
            for x in range(min(CW, w)):
                out[cy + TOP + y][cx + x] = rows[y][x]
    write_png_rgba(os.path.join(OUT, 'overview.png'), W, H, out)


if __name__ == '__main__':
    sys.exit(main(sys.argv))
