/* Frontier biome rows: authored curved corridors and wider encounter clearings. */
static const char *const RIMEWIND_TUNDRA_ROWS[] = {
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /*  0 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /*  1 */
    "RRRRRRRRRRRRRRRRRRRRRRRR~~~RRRRRRRRRRRRR", /*  2 */
    "RRRRRRRRRRRRRRRRRRRRRRR.~.~.RRRRRRRRRRRR", /*  3 */
    "RRRRRRRRRRRRRRRRRRRRRRR.,,,.RRRRRRRRRRRR", /*  4 */
    "RRRRRRRRRRRRRRRRRRRRRR.......RRRRRRRRRRR", /*  5 */
    "RRRRRRRRRRRRRRRRRRRRRRR.ii.,,.RRRRRRRRRR", /*  6 */
    "RRRRRRRRRRRRRR.RRRRRRR.........RRRRRRRRR", /*  7 */
    "RRRRRRRRRRRR,,,,.RRRR.....RR....RRRRRRRR", /*  8 */
    "RRRRRRRRRRR.,,,,.RRRR...RRRRR...RRRRRRRR", /*  9 */
    "RRRRRRRRRR..,,,,....R....RRRR...RRRRRRRR", /* 10 */
    "RRRRR.RRR.===,,,...=.......RR....RRRRRRR", /* 11 */
    "RRR.................==......RR....RRRRRR", /* 12 */
    "RR.........RRR.RRRR.........RRR......RRR", /* 13 */
    "R........RRRRRRRRRRR.........RR.......RR", /* 14 */
    "RR......RRRRRRRRRRRRR.......R........RRR", /* 15 */
    "RRR.....RRRRRRRRRRRRR.....==........RRRR", /* 16 */
    "RRRRR.RRRRRRRRRRRRRRRR......,,......RRRR", /* 17 */
    "RRRRRRRRRRRRRRRRRRRRRRRR.RR...RRR.RRRRRR", /* 18 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 19 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 20 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 21 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 22 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 23 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 24 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 25 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 26 */
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR", /* 27 */
};

static const char *const SPORELIGHT_HOLLOW_ROWS[] = {
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /*  0 */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /*  1 */
    "XXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXX", /*  2 */
    "XXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXX", /*  3 */
    "XXXXXXXXXXXXXXXXXXXX.,,,,.XXXXXXXXXX", /*  4 */
    "XXXXXXXXXXXXXX.XXXX........XXXXXXXXX", /*  5 */
    "XXXXXXXXXXXX,,,,.X..........XXXXXXXX", /*  6 */
    "XXXXXXXXXXX.,,,,.............XXXXXXX", /*  7 */
    "XXXXXXXXXXX.,,,,.....XX.XX....XXXXXX", /*  8 */
    "XXXXXXXXXX..,,,,,,,.XXXXXXX...XXXXXX", /*  9 */
    "XXXXX.XXX.===.....==.XX.XXX...XXXXXX", /* 10 */
    "XXX...............X.......X...X..XXX", /* 11 */
    "XXX........X.....XXX..............XX", /* 12 */
    "XX........XXXX.XXXXX.....==......XXX", /* 13 */
    "XXX.....XXXXXXXXXXX..............XXX", /* 14 */
    "XXX.....XXXXXXXXXXXX.....,,.....XXXX", /* 15 */
    "XXXXX.XXXXXXXXXXXXXX............XXXX", /* 16 */
    "XXXXXXXXXXXXXXXXXXXXX.~~~.XXX.XXXXXX", /* 17 */
    "XXXXXXXXXXXXXXXXXXXXXXX~XXXXXXXXXXXX", /* 18 */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /* 19 */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /* 20 */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /* 21 */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /* 22 */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /* 23 */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /* 24 */
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", /* 25 */
};
#include "data_extra.h"
