/* world/all_data.h -- every region's data.h (do not edit). */
#include "village/data.h"
#include "east/data.h"
#include "west/data.h"
#include "north/data.h"
#include "grim/data.h"
#include "far/data.h"
#include "farm/data.h"
#include "craft/data.h"
#include "fusion/data.h"
#include "travel/data.h"
#include "elev/data.h"
#include "ui/data.h"
#include "story/data.h"
#include "links/data.h"
#include "debug/data.h"
