/* world/all_scripts.c -- every region's scripts.c (do not edit). */
#include "village/scripts.c"
#include "east/scripts.c"
#include "west/scripts.c"
#include "north/scripts.c"
#include "grim/scripts.c"
#include "far/scripts.c"
#include "farm/scripts.c"
#include "craft/scripts.c"
#include "fusion/scripts.c"
#include "travel/scripts.c"
#include "ui/scripts.c"
#include "debug/scripts.c"
