#!/usr/bin/env python3
"""Decor of the FAR region (owner: W-FAR): transparent objects for the
'volcanic' (Cinder Road, Cindermoor, the Forge, Ember Tunnel, Caldera
Heart, Anvil Hall) and 'dream' (Moonveil Path, Dreamspire, Mirror Hall,
Dust Library) tilesets. Registered in gen_field_gfx.all_decor().

Palette plan (every 8x8 quadrant fits one bank; see ts_volcanic.py and
ts_dream.py):

  volcanic 1 lava      basalt + molten glow   (EMBER_ROCK)
  volcanic 2 rock      basalt, obsidian, charred wood (OBSIDIAN, COAL_PILE,
                       TOOL_RACK, SALAMANDER_STATUE)
  volcanic 4 decor     steam, stone, rust copper, fire, sulfur (STEAM_VENT,
                       FURNACE, BIG_BELL, BRAZIER, SMOKE)
  volcanic 5 iron      iron and brick (LAVA_ORE_CART, FORGE_ANVIL)
  volcanic 6 rust      rust cloth (HALL_BANNER)
  dream    0 ground    moonstone (DREAM_STATUE)
  dream    2 blossom   petals, mirror glass, moonstone crystal (PETALS,
                       MOONSTONE)
  dream    4 library   plum wood, books, paper, lantern light (MOON_LANTERN,
                       FLOAT_PAGES, BOOK_PILE, READING_DESK, BOOKCASE,
                       SCRIPT_PEDESTAL)
  dream    5 indigo    indigo frame + silver glass (STANDING_MIRROR)

Light comes from the top-left; objects have a 1px dark outline and never a
baked-in ground (the art lint checks).
"""

import math
from pixelart import Img, G, hash2, Decor
from decor_outdoor import SG, outline

VO = ['volcanic']
DR = ['dream']

# ---------------------------------------------------------------------------
# legends
# ---------------------------------------------------------------------------

# volcanic bank 4
DL = {'.': None, 'O': 'b_out', 'w': 'white', 'l': 'st_lt', 'm': 'st_mid', 'd': 'st_dk',
      'H': 'ru_hi', 'B': 'ru_base', 'D': 'ru_dk', 'y': 'lv_y', 'o': 'lv_o', 'r': 'lv_r',
      'P': 'ob_hi', 'Q': 'ob_base', 's': 'su_y', 'i': 'ir_dk'}
# volcanic bank 5 (iron)
IL = {'.': None, 'O': 'b_out', '1': 'ir_hi', '2': 'ir_lt', '3': 'ir_base', '4': 'ir_dk',
      '5': 'ir_dkr', 'h': 'bk_hi', 'b': 'bk_base', 'k': 'bk_dk', 'H': 'st_hi', 'L': 'st_lt',
      'M': 'st_mid', 'g': 'gl_dk'}
# volcanic bank 2 (rock)
RL = {'.': None, 'O': 'b_out', 'h': 'vb_hi', 'l': 'vb_lt', 'b': 'vb_base', 'd': 'vb_dk',
      'P': 'ob_hi', 'Q': 'ob_base', 'q': 'ob_dk', 'W': 'vcw_lt', 'V': 'vcw_base', 'v': 'vcw_dk',
      'a': 'va_lt', 'A': 'va_base'}
# volcanic bank 1 (lava)
LL = {'.': None, 'O': 'vb_out', 'l': 'vb_lt', 'b': 'vb_base', 'd': 'vb_dk', 'w': 'lv_w',
      'y': 'lv_y', 'o': 'lv_o', 'r': 'lv_r', 'R': 'lv_dr'}
# volcanic bank 6 (rust)
UL = {'.': None, 'O': 'b_out', '1': 'rr_hi', '2': 'rr_lt', '3': 'rr_base', '4': 'rr_dk',
      '5': 'rr_dkr', 'H': 'st_hi', 'L': 'st_lt', 'M': 'st_mid'}
# dream bank 4 (library)
BL = {'.': None, 'O': 'lw_out', 'h': 'vlw_hi', 'l': 'vlw_lt', 'b': 'vlw_base', 'd': 'vlw_dk',
      'r': 'bo_r', 'g': 'bo_g', 'u': 'bo_b', 'y': 'bo_y', 'P': 'pg_hi', 'p': 'pg_base',
      'q': 'pg_dk', 'Y': 'lg_y', 'o': 'lg_o', 'R': 'lp_r'}
# dream bank 2 (blossom / mirror glass / moonstone)
ML = {'.': None, 'O': 'bt_out', 'h': 'bt_hi', 'l': 'bt_lt', 'b': 'bt_base', 'd': 'bt_dk',
      'a': 'mf_hi', 'A': 'mf_lt', 'm': 'mf_base', 'M': 'mf_dk', 'c': 'vcr_hi', 'C': 'vcr_base',
      'k': 'vcr_dk'}
# dream bank 5 (indigo + silver)
NL = {'.': None, 'O': 'b_out', '1': 'ri_hi', '2': 'ri_lt', '3': 'ri_base', '4': 'ri_dk',
      '5': 'ri_dkr', 'H': 'st_hi', 'L': 'st_lt', 'M': 'st_mid'}
# dream bank 0 (moonstone)
SL = {'.': None, 'O': 'b_out', 'h': 'ds_hi', 'l': 'ds_lt', 'b': 'ds_base', 'm': 'ds_mid',
      'd': 'ds_dk', 'C': 'vcr_base', 'p': 'dp_base', 'P': 'dp_hi'}


# ===========================================================================
# VOLCANIC
# ===========================================================================

VENT = SG('''
................
................
................
................
................
................
................
................
................
...OOOOOOOOOO...
..OmllllmmmmdO..
.OmlsOOOOOOsmdO.
.OlsOddddddOsdO.
.OmdOOOOOOOOddO.
..OmdddddddddO..
...OOOOOOOOOO...
''', DL)


def steam_vent_frames():
    """A fumarole: a sulfur-crusted stone ring with steam puffing up through
    the cell above (4 frames). 1x2, the top cell over people."""
    frames = []
    for f in range(4):
        img = Img(16, 32)
        img.paste(VENT, 0, 16)
        # puffs rising: each puff is a soft blob moving up 6px per frame
        for (k, x0) in enumerate((6.5, 9.0, 7.5)):
            yc = 26 - ((f * 6 + k * 8) % 24)
            r = 1.6 + (26 - yc) * 0.12
            xc = x0 + math.sin((yc + k) * 0.35) * 1.5
            for y in range(32):
                for x in range(16):
                    d = math.hypot(x + 0.5 - xc, (y + 0.5 - yc) * 1.2)
                    if d <= r and img.p[y][x] is None:
                        img.p[y][x] = 'white' if d < r * 0.55 else 'st_lt'
                    elif d <= r + 0.8 and img.p[y][x] is None and y < 26:
                        img.p[y][x] = 'st_mid' if (x + y + f) % 2 else None
        frames.append(img)
    return frames


OBSIDIAN = SG('''
................
................
................
........O.......
.......OPO......
...O...OPqO.....
..OPO.OPQqO..O..
..OPqOOPQQqOOPO.
.OPQqOPPQQqOPQO.
.OPQQqPQQQqOPqqO
OPPQQqPQQqqOPQqO
OPQQQqPQQQqPQQqO
OPQQqqPQQqqPQqqO
.OOOOOOOOOOOOOO.
................
................
''', RL)


EMBER = SG('''
................
................
................
....OOOOOO......
...OllbbbbOO....
..OlbbdrbbbbO...
.OlbbdrrdbbdO...
.OlbbroodbbbdO..
.OlbdryodbbrdO..
.ObbdrodbbrydO..
.ObddRdbbdroddO.
..ObdddbbdRdddO.
..OOddddddddOO..
....OOOOOOOO....
................
................
''', LL)


def ember_rock_frames():
    """A cooling lava boulder; its cracks pulse (2 frames)."""
    a = EMBER.copy()
    b = EMBER.replace({'lv_y': 'lv_w', 'lv_o': 'lv_y', 'lv_r': 'lv_o'})
    return [a, a, b, a]


LAVA_ORE_CART = SG('''
................
................
................
...O..O.O..O....
..OMOOLOOMOHO...
.OLMLHMLOLMOLO..
.O11111111111O..
.O12222222223O..
.O2hbbhbbhbb3O..
.O23333333334O..
.O23LL333LL34O..
.OO4444444444O..
..O55555555O....
..OO4O..O4OO....
...OO....OO.....
................
''', IL)


ANVIL = SG('''
................
................
................
................
.OOOOOOOOOOOO...
O111111111111OO.
O2222222222224O.
.OO3333333333OO.
...OO33333OO....
....O3333O......
....O2334O......
...OkbbbbkO.....
..OhbbbbbbkO....
..ObbkbbkbbO....
..OOOOOOOOOO....
................
''', IL)


def furnace_frames():
    """A copper-banded brick furnace: its mouth breathes fire (3 frames).
    2x2; the chimney row is drawn over people."""
    base = SG('''
................................
................................
............OOOOOOOO............
............OlllmmdO............
............OmmmmmdO............
...........OOOOOOOOOO...........
...........OHBBBBBBDO...........
...........OBDBBDBBDO...........
...........OHBBBBBBDO...........
...........OBBDBBBDDO...........
........OOOOOOOOOOOOOOOO........
.......OllllllllllllmmmdO.......
......OHHHHHHHHHHHHHHBBBDO......
......OHBBBBBDBBBBBBBBBBDO......
......OHBBDBBBBBBBDBBBBDDO......
......OHBBBBBBBBBBBBBBBBDO......
......OHBDBBOOOOOOOOBBDBDO......
......OHBBBO........OBBBDO......
......OHBBO..........OBBDO......
......OHBBO..........OBDDO......
......OHBDO..........OBBDO......
......OHBBO..........OBBDO......
......OHBBOOOOOOOOOOOOBBDO......
......OlllllllllllllllmmdO......
......OmmmmmmmmmmmmmmmmddO......
......OOOOOOOOOOOOOOOOOOOO......
................................
................................
................................
................................
................................
................................
''', DL, w=32)
    frames = []
    for f in range(3):
        img = base.copy()
        for y in range(17, 22):
            for x in range(11, 21):
                if img.p[y][x] is not None:
                    continue
                t = (y - 17) / 4.0
                flick = math.sin(x * 1.3 + f * 2.1) * 0.35
                v = t + flick + (0.25 if (hash2(x, y, f) & 3) == 0 else 0)
                c = 'lv_y' if v > 0.9 else ('lv_o' if v > 0.45 else ('lv_r' if v > 0.1 else 'b_out'))
                img.p[y][x] = c
        for x in range(11, 21):
            img.p[21][x] = 'lv_y' if (x + f) % 3 else 'lv_o'
        frames.append(img)
    return frames


BELL = SG('''
................................
................................
..OOOOOOOOOOOOOOOOOOOOOOOOOOOO..
..OllllllllllllllllllllllllmdO..
..OOOOOOOOOOOOOOOOOOOOOOOOOOOO..
...Oid.........OO.........idO...
...Oid.........OO.........idO...
...Oid.......OOOOOO.......idO...
...Oid.....OOHHBBBDOO.....idO...
...Oid....OHHBBBBBBDDO....idO...
...Oid...OHHBBBBBBBBDDO...idO...
...Oid...OHBBBBBOBBBBDO...idO...
...Oid...OHBBBBBBOBBBDO...idO...
...Oid..OHHBBBBBOBBBBDDO..idO...
...Oid..OHBBBBBBBOBBBBDO..idO...
...Oid..OHBBBBBBOBBBBBDO..idO...
...Oid.OHHBBBBBBBOBBBBDDO.idO...
...Oid.OHBBBBBBBBBBBBBBDO.idO...
...Oid.ODDDDDDDDDDDDDDDDO.idO...
...Oid..OOOOOOOOOOOOOOOO..idO...
...Oid.......OOOOO........idO...
...Oid.......OmmdO........idO...
...Oid........OOO.........idO...
...Oid....................idO...
..OlidO..................OlidO..
..OmmdO..................OmmdO..
..OOOOO..................OOOOO..
................................
................................
................................
................................
................................
''', DL, w=32)


BRAZIER_BOWL = SG('''
................
................
................
................
................
................
................
................
.OOOOOOOOOOOOOO.
.OlllllllllllmO.
..OmmmmmmmmmdO..
...OOidddddOO...
.....OidO.......
....OidOiO......
...OidO.OiO.....
...OOO...OOO....
''', DL)


def brazier_frames():
    """An iron fire bowl on a tripod; its flames dance (3 frames)."""
    frames = []
    for f in range(3):
        img = BRAZIER_BOWL.copy()
        for y in range(0, 9):
            for x in range(2, 14):
                if img.p[y][x] is not None:
                    continue
                h = 8 - y
                w = 5.2 - h * 0.6 + math.sin(y * 1.1 + f * 2.0) * 0.8
                cx = 7.5 + math.sin(y * 0.7 + f * 1.7) * 0.9
                d = abs(x + 0.5 - cx)
                if d < w * 0.35 and h < 6:
                    img.p[y][x] = 'lv_y'
                elif d < w * 0.7:
                    img.p[y][x] = 'lv_o'
                elif d < w:
                    img.p[y][x] = 'lv_r'
        frames.append(img)
    return frames


COAL = SG('''
................
................
................
................
................
................
.......OOO......
.....OOhlbOO....
....OhlbbdbdO...
...OlbdOhlbddO..
..OhlbdhlbbdbdO.
.OhlbbdlbdddObO.
.OlbddOhlbdhlbdO
.OOOOOOOOOOOOOOO
................
................
''', RL)


TOOL_RACK = SG('''
................
................
.OOOOOOOOOOOOOO.
.OWWWWWWWWWWWWVO
.OVVVVVVVVVVVVvO
.OO.O..O..O..OO.
..O.O.OhO.O.....
.OhOO.OhO.OO....
.OlO..OlO.OhO...
.OlO..OhO.OlO...
OhbdO.OlO.OlO...
OlbdO.ObO.ObO...
.OdO..OdO.OhbO..
..O..OhldO.OdO..
.....OOOO...O...
................
''', RL)


SALAMANDER = SG('''
................
................
................
......OOOOO.....
.....OhllbbO....
....OhlPlbPdO...
....OllllbbdO...
.....OlbbbdO....
....OOhlbbdOO...
...OhlOhlbdObO..
...OlO.hlbd.OdO.
....O.OhlbdO.O..
......OhlbbdO...
.....OhlbbbdO...
....OhlbbbbbdO..
....OlbbbbbbdO..
...OhlbbbbbbbdO.
...OlbbbbObbbdO.
..OhlbbbOOObbbdO
..OOOOOOO.OOOOOO
..OhhhhhhhhhhhlO
..OlllllllllllbO
..ObbbbbbbbbbbdO
..OOOOOOOOOOOOOO
................
................
................
................
................
................
................
................
''', RL)


def salamander_statue():
    """A basalt statue of a fire salamander on a plinth (1x2)."""
    img = Img(16, 32)
    img.paste(SALAMANDER, 0, 8)
    return img


def smoke_frames():
    """Chimney smoke drifting up and east (4 frames; over people)."""
    frames = []
    for f in range(4):
        img = Img(16, 16)
        for k in range(3):
            t = ((f + k * 1.33) % 4) / 4.0
            yc = 14 - t * 13
            xc = 5 + t * 6 + math.sin(t * 6.0) * 1.2
            r = 1.5 + t * 2.4
            for y in range(16):
                for x in range(16):
                    d = math.hypot(x + 0.5 - xc, y + 0.5 - yc)
                    if d <= r and img.p[y][x] is None:
                        img.p[y][x] = 'st_lt' if d < r * 0.5 and t < 0.6 else 'st_mid'
        frames.append(img)
    return frames


BANNER = SG('''
................
.OOOOOOOOOOOOOO.
OHLLLLLLLLLLLLMO
.OOOOOOOOOOOOOO.
..O2111111111O..
..O2333333334O..
..O2333333334O..
..O23HHHHHH34O..
..O233HHHH334O..
..O2333HH3334O..
..O233HHHH334O..
..O23HHHHHH34O..
..O2333333334O..
..O2333333334O..
..O2333333334O..
..O4333333344O..
..O2333333334O..
..O2333333334O..
..O2333333334O..
..O2333333334O..
..O233344333O...
..O2334OO4334O..
..O234O..O434O..
..O24O....O44O..
..OOO......OOO..
................
................
................
................
................
................
................
''', UL)


# ===========================================================================
# DREAM
# ===========================================================================

def moon_lantern_frames():
    """A round paper lantern on a plum post; its glow flickers (2 frames).
    1x2, the lantern cell over people."""
    art = SG('''
................
.......OO.......
......OddO......
.....OOOOOO.....
....ORRoYoRO....
...ORoYYYYoRO...
...ORYYYYYYoO...
...ORoYYYYoRO...
....ORRoooRO....
.....OOOOOO.....
......OddO......
.......Od.......
.......Od.......
.......Od.......
.......Od.......
.......Od.......
.......Ob.......
.......Od.......
.......Ob.......
.......Od.......
.......Ob.......
.......Od.......
.......Od.......
.......Ob.......
......OhbdO.....
.....OhbbddO....
.....OOOOOOO....
................
................
................
................
................
''', BL)
    art2 = art.replace({'lg_y': 'lg_o', 'lg_o': 'lp_r'})
    for (x, y) in ((6, 6), (7, 5), (8, 6), (7, 6)):
        art2.set(x, y, 'lg_y')
    return [art, art, art2, art]


def float_pages_frames():
    """Loose pages drifting in the air, bobbing (4 frames, over people)."""
    page = G('''
    OOOOO
    OPPpO
    OPqpO
    OppqO
    OOOOO
    ''', BL)
    page2 = G('''
    OOOO
    OPpO
    OpqO
    OOOO
    ''', BL)
    frames = []
    for f in range(4):
        img = Img(16, 16)
        bob = [0, 1, 2, 1][f]
        img.paste(page, 2, 3 + bob)
        img.paste(page2, 10, 7 - bob)
        img.paste(page2, 7, 1 + [1, 0, 0, 1][f])
        frames.append(img)
    return frames


BOOK_PILE = SG('''
................
................
................
................
................
................
.....OOOOOOO....
....OyyyyyyyO...
....OPPPPPPPyO..
...OOOOOOOOOOO..
..OrrrrrrrrrrO..
..OPPPPPPPPPrO..
.OOOOOOOOOOOOO..
.OuuuuuuuuuuuuO.
.OPPPPPPPPPPPuO.
.OOOOOOOOOOOOOO.
''', BL)


READING_DESK = SG('''
................................
................................
............OOO.................
...........OYoYO................
...........OoYoO................
............ORO.......OOOOOOOO..
....OOOOOOOOOhOOOOO..OPPPOqPPPO.
...OhhhhhhhhhhhhhhhOOPpPOPpPqO..
...OllllllllllllllllOOOOOOOOO...
..OhhhhhhhhhhhhhhhhhhhhhhhhhhO..
..OllllllllllllllllllllllllldO..
..ObbbbbbbbbbbbbbbbbbbbbbbbbdO..
..OdddddddddddddddddddddddddddO.
..ObdO..................ObdO....
..ObdO..................ObdO....
................................
''', BL, w=32)


BOOKCASE = SG('''
................
.OOOOOOOOOOOOOO.
OhhhhhhhhhhhhhhO
OllllllllllllldO
OdOOOOOOOOOOOOdO
OdOrrOgOuuyOrOdO
OdOrrOgOuuyOrOdO
OdOPrOgOuPyOrOdO
OdOrrOgOuuyOrOdO
OdhhhhhhhhhhhhdO
OdOOOOOOOOOOOOdO
OdOuOyyOrrOggOdO
OdOuOyyOrrOgPOdO
OdOuOyPOrrOggOdO
OdOuOyyOrPOggOdO
OdhhhhhhhhhhhhdO
OdOOOOOOOOOOOOdO
OdOggOrOyyyOuOdO
OdOgPOrOyyyOuOdO
OdOggOrOPyyOuOdO
OdOggOrOyyyOuOdO
OdhhhhhhhhhhhhdO
OllllllllllllldO
ObbbbbbbbbbbbbdO
OOOOOOOOOOOOOOOO
................
................
................
................
................
................
................
''', BL)


def moonstone_frames():
    """A cluster of pale moonstone crystals; a glint runs over them."""
    base = SG('''
................
................
................
.......Ok.......
......OccOk.....
.....OcCCkO.....
..Ok.OcCCkO.Ok..
.OcCkOcCCkOOcCk.
.OcCkOcCCkkOcCkO
OccCkOcCCkkOcCCO
OcCCkkcCCCkOcCkO
OcCCkkcCCCkkcCkO
.OcCkkcCCCkkCkO.
..OOOOOOOOOOOOO.
................
................
''', ML)
    frames = []
    for (x, y) in ((7, 5), (2, 9), (13, 8), (8, 9)):
        fr = base.copy()
        fr.set(x, y, 'mf_hi')
        for (dx, dy) in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            if fr.get(x + dx, y + dy) not in (None, 'bt_out'):
                fr.set(x + dx, y + dy, 'vcr_hi')
        frames.append(fr)
    return [base, frames[0], base, frames[1], base, frames[2], base, frames[3]]


def petals_frames():
    """Blossom petals drifting down (4 frames, over people, walkable)."""
    pts = [(3, 1), (11, 4), (6, 9), (13, 12), (1, 13)]
    frames = []
    for f in range(4):
        img = Img(16, 16)
        for i, (x, y) in enumerate(pts):
            yy = (y + f * 4) % 16
            xx = (x + int(round(math.sin((yy + i) * 0.6) * 1.5))) % 16
            img.set(xx, yy, 'bt_lt' if (i + f) % 2 else 'bt_hi')
            img.set((xx + 1) % 16, yy, 'bt_base')
        frames.append(img)
    return frames


MIRROR_ART = SG('''
................
.....OOOOOO.....
....O211112O....
...O21HHLL14O...
..O21HHLLLM14O..
..O2HHLLLLMM4O..
..O2HLLLLMMM4O..
..O2HLLLLMMM4O..
..O2LLLLHMMM4O..
..O2LLLHMMMM4O..
..O2LLHMMMMM4O..
..O2LHMMMMLM4O..
..O2LMMMMLHM4O..
..O2MMMMLHLM4O..
..O2MMMLHLMM4O..
..O2MMMMMMMM4O..
..O24MMMMMM44O..
...O24MMMM44O...
....O244442O....
.....OO44OO.....
.......44.......
.......34.......
.......34.......
.....OO34OO.....
....O233444O....
....OOOOOOOO....
................
................
................
................
................
................
''', NL)


STATUE = SG('''
................
................
.....OOOO.......
....OhllbO......
...OhllllbO.....
..OhlOllOlbO....
..OhlllllllbOOO.
.OhllllllllbbbdO
.OhlmllllllbbbdO
.OhllmmllllbbddO
OhlllllmmmbbbddO
OhllllllbbbbddO.
OhlllllbbbbdddO.
.OhlllbbbbbddO..
..OOhlbbbddOO...
....OOOOOOO.....
..OOOOOOOOOOOO..
.OhhhhhhhhhhhlO.
.OlllCllllCllbO.
.OlllllllllllbO.
.ObbbbbbbbbbbdO.
.OOOOOOOOOOOOOO.
................
................
................
................
................
................
................
................
................
................
''', SL)


def dream_statue():
    """A moonstone statue of a sleeping SLUMBAKU curled on a plinth (1x2)."""
    img = Img(16, 32)
    img.paste(STATUE, 0, 8)
    return img


def script_pedestal_frames():
    """A plum pedestal holding an open tome whose letters glow (2 frames)."""
    art = SG('''
................
..OOOOOO.OOOOOO.
.OPPPPPPOPPPPPPO
.OPqqPqPOPqPqqPO
.OPPPPPPOPPPPPPO
.OPqPqqPOPqqPqPO
..OOOOOOOOOOOOO.
....OhhhhhhhO...
.....OlllllO....
.....OlbbbdO....
.....OlbbbdO....
.....OlbbbdO....
....OhlbbbddO...
...OhhhhhhhhhO..
...OddddddddddO.
...OOOOOOOOOOO..
''', BL)
    glow = art.replace({'pg_dk': 'lg_o'})
    return [art, art, glow, glow]


# ===========================================================================
# the catalogue
# ===========================================================================

FAR_DECOR = [
    # --- volcanic -----------------------------------------------------------
    Decor('STEAM_VENT', VO, frames=steam_vent_frames(), period=10, top='X/.', solid='./X',
          doc='fumarole: sulfur-crusted ring puffing steam into the cell above',
          examine='A fumarole. Hot steam hisses out of the ground and smells of rotten eggs.'),
    Decor('OBSIDIAN', VO, OBSIDIAN, doc='shards of black volcanic glass',
          examine='Obsidian: lava that cooled so fast it turned to glass. The edges are sharp.'),
    Decor('EMBER_ROCK', VO, frames=ember_rock_frames(), period=20,
          doc='a cooling lava boulder with glowing cracks',
          examine='A lump of cooling lava. It is still glowing inside, and far too hot to touch.'),
    Decor('LAVA_ORE_CART', VO, LAVA_ORE_CART, doc='mine cart heaped with iron ore',
          examine='A mine cart full of iron ore, waiting for the Forge.'),
    Decor('FORGE_ANVIL', VO, ANVIL, doc='iron anvil on a brick block',
          examine='A heavy anvil, polished by a thousand hammer blows.'),
    Decor('FURNACE', VO, frames=furnace_frames(), period=9, top='XX/..',
          doc='copper-banded brick furnace, the mouth breathing fire (2x2)',
          examine='The furnace roars. A sleepy BLAZE kin inside keeps it at a steady white heat.'),
    Decor('BIG_BELL', VO, BELL, top='XX/..', doc="Cindermoor's great bell on an iron frame (2x2)",
          examine="Cindermoor's warning bell. A long crack runs down one side."),
    Decor('BRAZIER', VO, frames=brazier_frames(), period=8, doc='iron fire bowl on a tripod',
          examine='A brazier. Its flames never seem to need more coal.'),
    Decor('COAL_PILE', VO, COAL, doc='a heap of coal',
          examine='A heap of coal for the furnaces.'),
    Decor('TOOL_RACK', VO, TOOL_RACK, doc='smith tools hanging on a charred rack',
          examine='Hammers, tongs and punches, each worn to the shape of the smith\'s hand.'),
    Decor('SALAMANDER_STATUE', VO, salamander_statue(), top='X/.',
          doc='basalt statue of a fire salamander on a plinth (1x2)',
          examine='A basalt salamander. The old smiths say CALDERON sleeps under the volcano.'),
    Decor('SMOKE', VO, frames=smoke_frames(), period=12, top='X', solid='.',
          doc='chimney smoke drifting up (over people, walkable)'),
    Decor('HALL_BANNER', VO, BANNER, top='X/.', doc='Anvil Hall banner, rust cloth with an anvil (1x2)',
          examine='The banner of the ANVIL HALL: an anvil on rust-red cloth.'),
    # --- dream -----------------------------------------------------------------
    Decor('MOON_LANTERN', DR, frames=moon_lantern_frames(), period=14, top='X/.',
          doc='round paper lantern on a plum post (1x2)',
          examine='A paper moon lantern. Its light is soft enough to dream by.'),
    Decor('FLOAT_PAGES', DR, frames=float_pages_frames(), period=16, top='X', solid='.',
          doc='loose pages drifting in the air (over people, walkable)'),
    Decor('BOOK_PILE', DR, BOOK_PILE, doc='a stack of old books',
          examine='A stack of books. The top one is titled "ON THE DREAMING OF KIN".'),
    Decor('READING_DESK', DR, READING_DESK, doc='reading desk with a candle and an open book (2x1)',
          examine='An open book, a guttering candle and a note: "Back soon. Do not wake the pages."'),
    Decor('BOOKCASE', DR, BOOKCASE, top='X/.', doc='freestanding bookcase (1x2)',
          examine='Books about sleep, stars and kin, shelved by the colour of their dreams.'),
    Decor('MOONSTONE', DR, frames=moonstone_frames(), period=10, doc='cluster of glinting moonstone',
          examine='Moonstone. It holds a little moonlight and gives it back at night.'),
    Decor('PETALS', DR, frames=petals_frames(), period=14, top='X', solid='.',
          doc='blossom petals drifting down (over people, walkable)'),
    Decor('STANDING_MIRROR', DR, MIRROR_ART, top='X/.', doc='tall oval mirror in an indigo frame (1x2)',
          examine='You see yourself... and for a moment, your reflection waves first.'),
    Decor('DREAM_STATUE', DR, dream_statue(), top='X/.',
          doc='moonstone statue of a sleeping SLUMBAKU on a plinth (1x2)',
          examine='A sleeping SLUMBAKU carved in moonstone. People leave it their bad dreams to eat.'),
    Decor('SCRIPT_PEDESTAL', DR, frames=script_pedestal_frames(), period=24,
          doc='pedestal holding an open tome whose letters glow',
          examine='An open tome. The letters crawl across the page like sleepy ants.'),
]
