#!/usr/bin/env python3
"""Write src/species_data.h from the kin roster in tools/kin/.

    python3 tools/gen_species.py [--out PATH]

The header holds the SP_* ids, every learnset and the SPECIES[] table. It is
included by src/game/data.h (after the types, traits, items and EVO_ ids).
tools/gen_monsters.py draws the sprites from the same specs.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kin  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def cstr(text):
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def trait_id(name):
    return 'TR_' + name.replace(' ', '_')


def main(argv):
    out_path = os.path.join(ROOT, 'src', 'species_data.h')
    if '--out' in argv:
        out_path = argv[argv.index('--out') + 1]
    specs = kin.load()
    o = ['/* species_data.h -- GENERATED by tools/gen_species.py from tools/kin/. Do not edit.',
         ' * Included by src/game/data.h. */',
         '#ifndef SPECIES_DATA_H', '#define SPECIES_DATA_H', '']
    o.append('enum {')
    for s in specs:
        o.append('    SP_%s,  /* %d %s */' % (s.name, s.id, '/'.join(s.types)))
    o.append('    SP_COUNT')
    o.append('};')
    o.append('typedef char SpeciesFitU8[SP_COUNT <= 255 ? 1 : -1];')
    o.append('')
    o.append('/* Learnsets: level-ordered, level-1 moves first, terminated by {0, 0}. */')
    for s in specs:
        ents = ', '.join('{%d, %s}' % (lv, mv) for (lv, mv) in s.learnset)
        o.append('static const LearnEntry LS_%s[] = { %s, {0, 0} };' % (s.name, ents))
    o.append('')
    o.append('static const Species SPECIES[SP_COUNT] = {')
    for s in specs:
        t1 = 'T_' + s.types[0]
        t2 = 'T_' + s.types[1] if len(s.types) > 1 else 'TYPE_NONE'
        if s.evo:
            kind, param, into = s.evo
            ek = {'LEVEL': 'EVO_LEVEL', 'ITEM': 'EVO_ITEM', 'BOND': 'EVO_BOND'}[kind]
            ep = str(param) if kind != 'ITEM' else 'ITEM_' + param
            ei = 'SP_' + into
        else:
            ek, ep, ei = 'EVO_NONE', '0', '0'
        fa = '|'.join('FA_' + f for f in s.field) or '0'
        fus = ('T_%s, T_%s' % s.fusion) if s.fusion else 'TYPE_NONE, TYPE_NONE'
        o.append('    [SP_%s] = { %s, %s, %s, { %s }, %d, %d, %s, %s, %s,' % (
            s.name, cstr(s.name), t1, t2, ', '.join(str(v) for v in s.base), s.catch, s.xp, ek, ep, ei))
        o.append('        %s, %d, %d, LS_%s,' % (cstr(s.category or 'KIN'), s.height, s.weight, s.name))
        o.append('        %s,' % cstr(s.desc))
        o.append('        { %s, %s }, %s, %s, { %s } },' % (trait_id(s.traits[0]), trait_id(s.traits[1]),
                                                        kin.RARITY[s.rarity], fa, fus))
    o.append('};')
    o.append('')
    o.append('#endif')
    open(out_path, 'w').write('\n'.join(o) + '\n')
    print('wrote %s (%d species)' % (out_path, len(specs)))


if __name__ == '__main__':
    main(sys.argv[1:])
