#!/usr/bin/env python3
"""Generate src/music_data.h: waveforms, drum samples, instruments and every
song for the music engine in src/game/music.c.

Songs live in tools/music/*.py (loaded in file-name order, songs keep the
order they are defined in); each file calls musiclib.song(...).

    python3 tools/gen_music.py            # writes src/music_data.h
    python3 tools/gen_music.py --list     # also prints a table of songs
    python3 tools/gen_music.py --strict   # chord warnings become errors

Standard library only; the output is byte-identical on every platform.
"""

import importlib.util
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import musiclib as M  # noqa: E402

OUT_H = os.path.join(M.ROOT, "src", "music_data.h")
SONG_DIR = os.path.join(M.ROOT, "tools", "music")


def load_songs():
    for fn in sorted(os.listdir(SONG_DIR)):
        if not fn.endswith(".py") or fn.startswith("_"):
            continue
        path = os.path.join(SONG_DIR, fn)
        spec = importlib.util.spec_from_file_location("song_" + fn[:-3], path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)


def c_array(ctype, name, vals, per_line=24, fmt="{}"):
    lines = [f"static const {ctype} {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(fmt.format(v) for v in vals[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    strict = "--strict" in sys.argv
    load_songs()
    warnings = []

    # resources actually referenced
    wave_names = []
    noise_names = []
    sample_names = []
    for ins in M.INSTRUMENTS.values():
        if ins["kind"] == M.MK_WAVE and ins["src"] not in wave_names:
            wave_names.append(ins["src"])
        elif ins["kind"] == M.MK_NOISE and ins["src"] not in noise_names:
            noise_names.append(ins["src"])
        elif ins["kind"] == M.MK_PCM and ins["src"] not in sample_names:
            sample_names.append(ins["src"])
    for _, smp, _, _ in M.KIT:
        if smp not in sample_names:
            sample_names.append(smp)

    instr_index = {name: i for i, name in enumerate(M.INSTR_ORDER)}
    compiled = []
    seen = set()
    for s in M.SONGS:
        if s["ident"] in seen:
            raise SystemExit(f"duplicate song {s['ident']}")
        seen.add(s["ident"])
        compiled.append(M.compile_song(s, instr_index, warnings.append))

    for w in warnings:
        print("warning:", w, file=sys.stderr)
    if strict and warnings:
        raise SystemExit(f"{len(warnings)} warnings")

    out = []
    out.append("/* Generated by tools/gen_music.py -- do not edit. */")
    out.append("")
    out.append(f"#define MUS_RATE_CYCLES {M.RATE_CYCLES}   /* timer 0 period: {M.RATE:.1f} Hz */")
    out.append(f"#define MUS_MIX_LEN {M.MIX_LEN}       /* samples per frame */")
    out.append(f"#define MUS_WAVE_SHIFT 26     /* 64-step waveforms */")
    out.append(f"#define MUS_NOISE_SHIFT 20    /* 4096-step noise loops */")
    out.append("")

    # waveforms
    out.append(f"static const s8 mus_waves[{len(wave_names)}][{M.WAVE_LEN}] = {{")
    for name in wave_names:
        vals = M.WAVES[name]
        out.append(f"    {{ /* {name} */")
        for i in range(0, len(vals), 16):
            out.append("        " + ", ".join(str(v) for v in vals[i:i + 16]) + ",")
        out.append("    },")
    out.append("};")
    out.append("")
    out.append(f"static const s8 mus_noises[{len(noise_names)}][{M.NOISE_LEN}] = {{")
    for name in noise_names:
        vals = M.NOISES[name]
        out.append(f"    {{ /* {name} */")
        for i in range(0, len(vals), 32):
            out.append("        " + ",".join(str(v) for v in vals[i:i + 32]) + ",")
        out.append("    },")
    out.append("};")
    out.append("")

    # samples
    for name in sample_names:
        data, _ = M.SAMPLES[name]
        lines = [f"static const s8 mus_smp_{name}[{len(data)}] = {{"]
        for i in range(0, len(data), 32):
            lines.append("    " + ",".join(str(v) for v in data[i:i + 32]) + ",")
        lines.append("};")
        out.append("\n".join(lines))
    out.append("")
    out.append(f"static const MusSample MUS_SAMPLES[{len(sample_names)}] = {{")
    for name in sample_names:
        data, base = M.SAMPLES[name]
        out.append(f"    {{ mus_smp_{name}, {len(data)}, {base}, 0 }},")
    out.append("};")
    out.append("")
    out.append("/* drum kit slot (the note byte on a kit channel): sample, level, semitones */")
    out.append(f"static const MusDrum MUS_KIT[{len(M.KIT) + 1}] = {{")
    out.append("    { 0, 0, 0, 0 },")
    for letter, smp, vol, pitch in M.KIT:
        out.append(f"    {{ {sample_names.index(smp)}, {vol}, {pitch}, 0 }},   /* {letter} {smp} */")
    out.append("};")
    out.append("")

    # instruments
    kinds = {M.MK_WAVE: "MK_WAVE", M.MK_NOISE: "MK_NOISE", M.MK_PCM: "MK_PCM", M.MK_KIT: "MK_KIT"}
    out.append("/* kind, source, level, sustain, attack, decay, fade, release,")
    out.append(" * vibrato delay/depth/speed, sweep (see MusInstr) */")
    out.append(f"static const MusInstr MUS_INSTRS[{len(M.INSTR_ORDER)}] = {{")
    for name in M.INSTR_ORDER:
        ins = M.INSTRUMENTS[name]
        p = M.instr_c_params(ins)
        if ins["kind"] == M.MK_WAVE:
            src = wave_names.index(ins["src"])
        elif ins["kind"] == M.MK_NOISE:
            src = noise_names.index(ins["src"])
        elif ins["kind"] == M.MK_PCM:
            src = sample_names.index(ins["src"])
        else:
            src = 0
        out.append(f"    {{ {kinds[ins['kind']]}, {src}, {p['vol']}, {p['sus']}, {p['atk']}, {p['dec']}, "
                   f"{p['fade']}, {p['rel']}, {p['vib_delay']}, {p['vib_depth']}, {p['vib_speed']}, "
                   f"{p['sweep']} }},   /* {name} */")
    out.append("};")
    out.append("")

    # pitch table: phase step per sample for C7..B7 in 1/64 semitones
    f_c7 = 440.0 * M.dexp2((96 - 69) / 12.0)
    inc = []
    for k in range(768):
        f = f_c7 * M.dexp2(k / 768.0)
        inc.append(M.rnd(f * 4294967296.0 / M.RATE))
    out.append("/* phase step per output sample for notes C7..B7 in 1/64 semitones;")
    out.append(" * lower octaves shift right (64-step waves: index = phase >> 26) */")
    out.append(c_array("u32", "MUS_OCT_INC", inc, per_line=8, fmt="{}u"))
    out.append("")
    sine = [M.rnd(127 * M.dsin(M.TWO_PI * i / 64)) for i in range(64)]
    out.append(c_array("s8", "MUS_SINE", sine, per_line=16))
    out.append("")

    # songs
    out.append("/* SONG_NONE (0) is silence; in MapDef.song it means \"choose by area\". */")
    out.append("enum {")
    out.append("    SONG_NONE,")
    for c in compiled:
        out.append(f"    SONG_{c['ident']},")
    out.append("    SONG_COUNT")
    out.append("};")
    out.append("")
    total = 0
    for c in compiled:
        for i, (name, code, loop) in enumerate(c["streams"]):
            total += len(code)
            ident = f"mus_{c['ident'].lower()}_{i}"
            out.append(f"/* {c['ident']} / {name} */")
            out.append(c_array("u8", ident, code, per_line=24))
    out.append("")
    out.append(f"static const MusSong MUS_SONGS[SONG_COUNT] = {{")
    out.append("    [SONG_NONE] = { { 0 }, { 0 }, 0, 1, 1, 0 },")
    for c in compiled:
        n = len(c["streams"])
        ptrs = ", ".join(f"mus_{c['ident'].lower()}_{i}" for i in range(n))
        ptrs += ", 0" * (M.MAX_CHANNELS - n)
        loops = ", ".join(str(loop if loop is not None else 0xFFFF) for _, _, loop in c["streams"])
        loops += ", 0xFFFF" * (M.MAX_CHANNELS - n)
        out.append(f"    [SONG_{c['ident']}] = {{ {{ {ptrs} }},")
        out.append(f"        {{ {loops} }}, {n}, {c['num']}, {c['den']}, {c['level']} }},")
    out.append("};")
    out.append("")
    out.append("/* frames for one pass: the intro plus the loop once */")
    out.append("static const u16 MUS_FRAMES[SONG_COUNT] = {")
    for c in compiled:
        frames = -(-c["ticks"] * c["den"] // c["num"])
        out.append(f"    [SONG_{c['ident']}] = {frames},")
    out.append("};")
    out.append("")
    out.append("static const char *const MUS_IDENTS[SONG_COUNT] = {")
    out.append("    [SONG_NONE] = \"NONE\",")
    for c in compiled:
        out.append(f"    [SONG_{c['ident']}] = \"{c['ident']}\",")
    out.append("};")
    out.append("")
    out.append("static const char *const MUS_TITLES[SONG_COUNT] = {")
    out.append("    [SONG_NONE] = \"(silence)\",")
    for c in compiled:
        out.append(f"    [SONG_{c['ident']}] = \"{c['title']}\",")
    out.append("};")
    out.append("")

    text = "\n".join(out)
    with open(OUT_H, "w") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(OUT_H, M.ROOT)}: {len(compiled)} songs, {total} bytes of sequence data, "
          f"{sum(len(M.SAMPLES[s][0]) for s in sample_names)} bytes of samples")
    if "--list" in sys.argv:
        for c in compiled:
            secs = c["ticks"] * c["tempo"] / 12.0 / 60.0
            loop = f"loops at {c['loop_tick'] // (M.PPQ * c['beats']) + 1}" if c["loop"] else "jingle"
            print(f"  {c['ident']:<16} {len(c['streams'])} ch  {M.bpm(c['tempo']):5.1f} bpm  "
                  f"{c['ticks'] // (M.PPQ * c['beats']):3d} bars  {secs:5.1f} s  {loop:<14} {c['title']}")


if __name__ == "__main__":
    main()
