#!/usr/bin/env python3
"""Generate count metadata for the positional world IDs; never change the v5 snapshot."""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORLD = ROOT / 'src/game/world'
GOLDEN = ROOT / 'tools/tests/save_layout.golden'
OUTPUT = WORLD / 'save_layout.inc'
KINDS = ('ids', 'flag_ids', 'satchels', 'trainer_ids', 'quest_ids', 'lore_ids')
PREFIX = ('MAP_', 'FLAG_', '', 'TR_', 'QUEST_', 'LORE_')


def clean(source):
    return re.sub(r'"(?:\\.|[^"\\])*"|/\*.*?\*/|//[^\n]*',
                  lambda m: ' ' if not m.group().startswith('"') else m.group(),
                  source, flags=re.S)


def ids(region, kind, prefix):
    text = clean((WORLD / region / (kind + '.inc')).read_text())
    if kind == 'satchels':
        return [f'{region}:{i}' for i in range(len(re.findall(r'\{\s*MAP_', text)))]
    return re.findall(r'\b' + prefix + r'[A-Z0-9_]+\b', text)


def layout():
    regions = re.findall(r'#include "([^/]+)/ids\.inc"', (WORLD / 'all_ids.inc').read_text())
    for kind in KINDS:
        actual = re.findall(r'#include "([^/]+)/' + kind + r'\.inc"',
                            (WORLD / ('all_' + kind + '.inc')).read_text())
        if actual != regions:
            raise ValueError(f'{kind} region order differs from maps; cannot remap safely')
    builtin_lore = clean((ROOT / 'src/game/lore.h').read_text().split('#include "world/all_lore_ids.inc"')[0])
    builtin = re.findall(r'\bLORE_[A-Z0-9_]+\b', builtin_lore.split('enum {')[-1])
    return {'regions': ['builtin'] + regions,
            'ids': [[builtin if kind == 'lore_ids' else (['QUEST_NONE_ID'] if kind == 'quest_ids' else [])
                     for kind in KINDS]] +
                   [[ids(region, kind, prefix) for kind, prefix in zip(KINDS, PREFIX)]
                    for region in regions]}


def main():
    current = layout()
    v5 = json.loads((ROOT / 'tools/tests/save_layout.v5.json').read_text())
    old = json.loads(GOLDEN.read_text())
    old_regions = old['regions']
    for region in old_regions:
        if region not in current['regions']:
            raise ValueError(f'region removed: {region}')
        before = old['ids'][old_regions.index(region)]
        after = current['ids'][current['regions'].index(region)]
        for kind, saved, now in zip(KINDS, before, after):
            # Asset-viewer map IDs are generated from tileset size and are never saved.
            if region == 'debug' and kind == 'ids':
                continue
            if now[:len(saved)] != saved:
                raise ValueError(f'{region}/{kind}: IDs were deleted or reordered (append only)')
    def lines(rows):
        return ',\n'.join('    {' + ', '.join(str(len(a)) for a in row) + '}' for row in rows)
    def pair_lines(rows):
        return ',\n'.join('    {' + ', '.join(map(str, pair)) + '}' for pair in rows)
    def key(name):
        h = 2166136261
        for byte in name.encode():
            h = ((h ^ byte) * 16777619) & 0xffffffff
        return h
    result = (f'/* Generated by tools/gen_save_layout.py; do not edit. */\n'
              f'#define SAVE_REGION_COUNT {len(current["regions"])}\n'
              f'#define SAVE_V5_REGION_COUNT {len(v5["regions"])}\n'
              f'#define SAVE_V5_MAP_COUNT {len(v5["map_bits"])}\n'
              f'static const u32 SAVE_REGION_KEYS[SAVE_REGION_COUNT] = {{{", ".join(hex(key(n)) + "u" for n in current["regions"])}}};\n'
              f'static const u32 SAVE_V5_KEYS[SAVE_V5_REGION_COUNT] = {{{", ".join(hex(key(n)) + "u" for n in v5["regions"])}}};\n'
              f'static const u16 SAVE_CURRENT_COUNTS[SAVE_REGION_COUNT][6] = {{\n{lines(current["ids"])}\n}};\n'
              f'static const u16 SAVE_V5_COUNTS[SAVE_V5_REGION_COUNT][6] = {{\n{lines(v5["ids"])}\n}};\n'
              f'static const u8 SAVE_V5_MAP_BITS[SAVE_V5_MAP_COUNT][2] = {{\n{pair_lines(v5["map_bits"])}\n}};\n')
    if not OUTPUT.exists() or OUTPUT.read_text() != result:
        OUTPUT.write_text(result)
    if current['ids'] != old['ids'] or current['regions'] != old_regions:
        print('save layout grew; review and accept new golden with --accept-growth')
        if '--accept-growth' in sys.argv:
            GOLDEN.write_text(json.dumps({**current, 'map_bits': old['map_bits']}, indent=2) + '\n')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError) as error:
        sys.exit(f'save layout: {error}')
