#!/usr/bin/env python3
"""Generate src/gfx_keepers.h: the bout portraits (keeper_cast.py).

    20 keeper archetypes x 5 frames (idle, breath, flair, throw, lose)
    the same 20 walking the overworld: 16x32, 9 frames (keeper_ow.py), in
    the portraits' palette slots so a variation matches on the map
    the player: front (idle, breath, wave, cheer) and back (idle, breath,
    wind-up, throw)

Each frame is a 64x64 OBJ (8x8 tiles, row-major, 1D mapping). Keepers
share their tiles across every variation: the palette is built at run time
from the ramp tables below (skin, hair, cloth A, cloth B) and the
archetype's accent, see keeper_palette() in src/game/keeper.c. vary 0 is
the archetype's default look; any other value picks from its pools with
the same hash as keeper_variant() here.

    python3 tools/gen_keeper_gfx.py                 # writes src/gfx_keepers.h
    python3 tools/gen_keeper_gfx.py --preview DIR   # also preview PNGs
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import keeper_art as A  # noqa: E402
import keeper_cast as C  # noqa: E402
import keeper_ow as O  # noqa: E402
from pixelart import c15, write_png, scale_rows  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_H = os.path.join(ROOT, 'src', 'gfx_keepers.h')

HERO_LOOK = dict(skin='light', hair='cocoa', a='orange', b='navy', acc='green')
HERO_PACK = (184, 132, 84)   # the satchel sits in the hair-shine slot


def hero_palette():
    pal = A.palette(HERO_LOOK)
    pal[A.HAIR_L] = HERO_PACK
    return pal


def pools(a):
    p = a['pools']
    look = a['look']
    return ([A.ramp_index(A.HAIRS, n) for n in p.get('hair', (look['hair'],))],
            [A.ramp_index(A.CLOTHS, n) for n in p.get('a', (look['a'],))],
            [A.ramp_index(A.CLOTHS, n) for n in p.get('b', (look['b'],))])


def keeper_variant(a, vary):
    """(skin, hair, a, b) ramp indices: must match keeper_palette() in C"""
    look = a['look']
    skin = A.ramp_index(A.SKINS, look['skin'])
    hair = A.ramp_index(A.HAIRS, look['hair'])
    ca = A.ramp_index(A.CLOTHS, look['a'])
    cb = A.ramp_index(A.CLOTHS, look['b'])
    if vary:
        hp, ap, bp = pools(a)
        h = (vary * 2654435761) & 0xffffffff
        h ^= h >> 15
        h = (h * 2246822519) & 0xffffffff
        h ^= h >> 13
        skin = h % len(A.SKINS)
        hair = hp[(h >> 4) % len(hp)]
        ca = ap[(h >> 9) % len(ap)]
        bi = (h >> 14) % len(bp)
        cb = bp[bi]
        if cb == ca and len(bp) > 1:
            cb = bp[(bi + 1) % len(bp)]
    return skin, hair, ca, cb


def variant_palette(a, vary):
    skin, hair, ca, cb = keeper_variant(a, vary)
    look = dict(skin=A.SKINS[skin][0], hair=A.HAIRS[hair][0], a=A.CLOTHS[ca][0], b=A.CLOTHS[cb][0],
                acc=a['look']['acc'])
    return A.palette(look)


def to_tiles(px):
    words = []
    for ty in range(8):
        for tx in range(8):
            for y in range(8):
                w = 0
                for x in range(8):
                    w |= (px[ty * 8 + y][tx * 8 + x] & 15) << (4 * x)
                words.append(w)
    return words


def to_tiles_ow(px):
    """16x32 -> 8 tiles, 2 wide x 4 tall, row-major (the field's layout)"""
    words = []
    for ty in range(4):
        for tx in range(2):
            for y in range(8):
                w = 0
                for x in range(8):
                    w |= (px[ty * 8 + y][tx * 8 + x] & 15) << (4 * x)
                words.append(w)
    return words


def fmt_u32(words, indent='      '):
    out = []
    for i in range(0, len(words), 8):
        out.append(indent + ', '.join('0x%08X' % w for w in words[i:i + 8]) + ',')
    return '\n'.join(out)


def c15s(rgbs):
    return ', '.join('0x%04X' % c15(c) for c in rgbs)


def build():
    keepers = [[C.person(a, f) for f in C.FRAMES] for a in C.ARCHETYPES]
    front = [C.player_front(f) for f in C.PLAYER_FRONT]
    back = [C.player_back(f) for f in C.PLAYER_BACK]
    walkers = [O.frames_ow(a) for a in C.ARCHETYPES]
    return keepers, front, back, walkers


def write_header(keepers, front, back, walkers):
    L = []
    A_ = L.append
    A_('/* Generated by tools/gen_keeper_gfx.py -- do not edit. */')
    A_('/* Bout portraits: 64x64 OBJ frames (8x8 tiles, row-major) painted in */')
    A_('/* palette slots; keeper colours come from the ramps at run time.    */')
    A_('#ifndef GFX_KEEPERS_H')
    A_('#define GFX_KEEPERS_H')
    A_('')
    A_('#define KEEPER_COUNT %d' % len(C.ARCHETYPES))
    A_('enum { ' + ', '.join('KP_%s' % a['key'] for a in C.ARCHETYPES) + ' };')
    A_('enum { ' + ', '.join('KF_%s' % f for f in C.FRAMES) + ', KF_COUNT };')
    A_('enum { ' + ', '.join('HF_%s' % f for f in C.PLAYER_FRONT) + ', HF_COUNT };')
    A_('enum { ' + ', '.join('HB_%s' % f for f in C.PLAYER_BACK) + ', HB_COUNT };')
    A_('')
    A_('/* palette slots: 1 outline 2 white 3 eyes 4-6 skin (+shade, blush) */')
    A_('/* 7-9 hair (+shade, shine) 10-11 cloth A 12-13 cloth B 14-15 accent */')
    A_('#define KP_SKIN_COUNT %d' % len(A.SKINS))
    A_('#define KP_HAIR_COUNT %d' % len(A.HAIRS))
    A_('#define KP_CLOTH_COUNT %d' % len(A.CLOTHS))
    A_('static const u16 kp_fixed_pal[4] = { 0x0000, %s };  /* 0-3 */' %
       c15s([A.OUTLINE, A.WHITE_C, A.EYE_C]))
    A_('static const u16 kp_skin_ramp[KP_SKIN_COUNT][3] = {')
    for s in A.SKINS:
        A_('    { %s }, /* %s */' % (c15s(s[1:]), s[0]))
    A_('};')
    A_('static const u16 kp_hair_ramp[KP_HAIR_COUNT][3] = {')
    for h in A.HAIRS:
        A_('    { %s }, /* %s */' % (c15s(h[1:]), h[0]))
    A_('};')
    A_('static const u16 kp_cloth_ramp[KP_CLOTH_COUNT][2] = {')
    for c in A.CLOTHS:
        A_('    { %s }, /* %s */' % (c15s(c[1:]), c[0]))
    A_('};')
    A_('')
    A_('/* An archetype\'s default look (ramp indices), its accent and the */')
    A_('/* pools its variations draw from. */')
    A_('typedef struct {')
    A_('    const char *title;')
    A_('    u8 skin, hair, a, b;')
    A_('    u16 acc[2];')
    A_('    u8 nhair, na, nb;')
    A_('    u8 hair_pool[12], a_pool[8], b_pool[8];')
    A_('} KeeperLook;')
    A_('static const KeeperLook KEEPER_LOOK[KEEPER_COUNT] = {')
    for a in C.ARCHETYPES:
        look = a['look']
        hp, ap, bp = pools(a)
        assert len(hp) <= 12 and len(ap) <= 8 and len(bp) <= 8, a['key']
        acc = A.ACCENTS[look['acc']]
        A_('    [KP_%s] = { "%s", %d, %d, %d, %d, { %s }, %d, %d, %d, { %s }, { %s }, { %s } },' % (
            a['key'], a['title'].upper(),
            A.ramp_index(A.SKINS, look['skin']), A.ramp_index(A.HAIRS, look['hair']),
            A.ramp_index(A.CLOTHS, look['a']), A.ramp_index(A.CLOTHS, look['b']),
            c15s(acc), len(hp), len(ap), len(bp),
            ', '.join(map(str, hp)), ', '.join(map(str, ap)), ', '.join(map(str, bp))))
    A_('};')
    A_('')
    A_('static const u32 keeper_gfx[KEEPER_COUNT][KF_COUNT][64 * 8] = {')
    for a, frames in zip(C.ARCHETYPES, keepers):
        A_('  { /* %s: %s */' % (a['key'], a['blurb']))
        for f, px in zip(C.FRAMES, frames):
            A_('    { /* %s */' % f)
            A_(fmt_u32(to_tiles(px)))
            A_('    },')
        A_('  },')
    A_('};')
    A_('')
    A_('/* The keepers on the overworld: 16x32, 9 frames x 8 tiles (2x4, row-major), */')
    A_('/* ordered like char_gfx (0 down, 1-2 down walk, 3 up, 4-5 up walk, 6 left, */')
    A_('/* 7-8 left walk; right = h-flipped left). Same palette slots as above.     */')
    A_('static const u32 keeper_ow_gfx[KEEPER_COUNT][9][8 * 8] = {')
    for a, frames in zip(C.ARCHETYPES, walkers):
        A_('  { /* %s */' % a['key'])
        for px in frames:
            A_('    {')
            A_(fmt_u32(to_tiles_ow(px)))
            A_('    },')
        A_('  },')
    A_('};')
    A_('')
    A_('/* The player, from the front and from behind (the bout view). */')
    A_('static const u16 hero_palette[16] = { %s };' % c15s(hero_palette()))
    for name, frames, labels in (('hero_front_gfx', front, C.PLAYER_FRONT),
                                 ('hero_back_gfx', back, C.PLAYER_BACK)):
        A_('static const u32 %s[%d][64 * 8] = {' % (name, len(frames)))
        for f, px in zip(labels, frames):
            A_('    { /* %s */' % f)
            A_(fmt_u32(to_tiles(px)))
            A_('    },')
        A_('};')
    A_('')
    A_('#endif')
    with open(OUT_H, 'w') as fh:
        fh.write('\n'.join(L) + '\n')


# ---------------------------------------------------------------- previews

def sheet(items, path, cols, scale=3, bg=(150, 196, 140), pad=4):
    rows_n = (len(items) + cols - 1) // cols
    cw = 64 + pad
    Wd, Hd = cols * cw, rows_n * cw
    img = [[bg] * Wd for _ in range(Hd)]
    for i, (px, pal) in enumerate(items):
        ox, oy = (i % cols) * cw + pad // 2, (i // cols) * cw + pad // 2
        for y in range(64):
            for x in range(64):
                s = px[y][x]
                if s:
                    img[oy + y][ox + x] = pal[s]
    write_png(path, Wd * scale, Hd * scale, scale_rows(img, scale))


def previews(out, keepers, front, back, walkers):
    os.makedirs(out, exist_ok=True)
    items = [(fr[0], A.palette(a['look'])) for a, fr in zip(C.ARCHETYPES, keepers)]
    sheet(items, os.path.join(out, 'keepers_cast.png'), 5)
    items = [(px, A.palette(a['look'])) for a, fr in zip(C.ARCHETYPES, keepers) for px in fr]
    sheet(items, os.path.join(out, 'keepers_frames.png'), len(C.FRAMES), scale=2)
    items = [(fr[0], variant_palette(a, v)) for a, fr in zip(C.ARCHETYPES, keepers) for v in range(0, 8)]
    sheet(items, os.path.join(out, 'keepers_variants.png'), 8, scale=2)
    ow = []
    for a, fr in zip(C.ARCHETYPES, walkers):
        pal = A.palette(a['look'])
        ow.append((fr, pal))
    cw, ch = 18, 34
    img = [[(150, 196, 140)] * (9 * cw) for _ in range(len(ow) * ch)]
    for r, (fr, pal) in enumerate(ow):
        for i, px in enumerate(fr):
            for y in range(32):
                for x in range(16):
                    if px[y][x]:
                        img[r * ch + 1 + y][i * cw + 1 + x] = pal[px[y][x]]
    write_png(os.path.join(out, 'keepers_overworld.png'), 9 * cw * 3, len(ow) * ch * 3, scale_rows(img, 3))
    hp = hero_palette()
    sheet([(px, hp) for px in front + back], os.path.join(out, 'hero.png'), 4)


def main():
    keepers, front, back, walkers = build()
    write_header(keepers, front, back, walkers)
    if '--preview' in sys.argv:
        previews(sys.argv[sys.argv.index('--preview') + 1], keepers, front, back, walkers)


if __name__ == '__main__':
    main()
